import type { DayRange, Spot, WeekHours } from "./types";

// Compiled July 2026 from OpenStreetMap (amenity=toilets nodes, Nominatim-verified
// venues) plus local knowledge. `osmToilet` marks restrooms mapped on OSM;
// `verify` marks hours that drift — New Orleans hours always drift.

const T = (hour: number, minute = 0): number => hour * 60 + minute;
const R = (open: number, close: number): DayRange => ({ open, close });

const daily = (open: number, close: number): WeekHours => {
  const day = [R(open, close)];
  return [day, day, day, day, day, day, day];
};

/** Sunday-first week; null = closed that day. */
const week = (...days: (readonly DayRange[] | null)[]): WeekHours => days.map((d) => d ?? []);

export const SPOTS: readonly Spot[] = [
  // ——— French Quarter & Riverfront ———
  {
    id: "washington-artillery-park",
    name: "Washington Artillery Park Restrooms",
    category: "public",
    lat: 29.95681,
    lng: -90.06243,
    address: "Decatur St at St. Ann St, across from Jackson Square",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(18)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Up the steps between Jackson Square and the river, next to Café du Monde — which famously has no restroom of its own. If these are locked, the Dutch Alley restrooms are three blocks downriver.",
  },
  {
    id: "french-market-dutch-alley",
    name: "French Market Restrooms (Dutch Alley)",
    category: "public",
    lat: 29.95871,
    lng: -90.0607,
    address: "Dutch Alley, French Market, near Dumaine St",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(18)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "The official public restrooms of the French Market, tucked into Dutch Alley by the Jazz Museum end. Free, wheelchair accessible, and checked on OpenStreetMap as recently as 2025. The safest bet in the lower Quarter.",
  },
  {
    id: "french-market-flea",
    name: "French Market Restrooms (Flea Market end)",
    category: "public",
    lat: 29.96069,
    lng: -90.05819,
    address: "1235 N Peters St, flea market end",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(17)),
    free: true,
    verify: true,
    tip: "At the flea-market end of the French Market. If you can't spot them, ask any vendor — you will not be the first, or the thousandth.",
  },
  {
    id: "moonwalk-riverfront",
    name: "Moonwalk Riverfront Restrooms",
    category: "public",
    lat: 29.95424,
    lng: -90.06305,
    address: "Moonwalk promenade, near the foot of Toulouse St",
    neighborhood: "French Quarter",
    hours: daily(T(8), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "On the river promenade below the levee. Catch a breeze off the Mississippi while you wait your turn — the view beats every bar bathroom line in the Quarter.",
  },
  {
    id: "jax-brewery",
    name: "The Shops at JAX Brewery",
    category: "public",
    lat: 29.95595,
    lng: -90.06296,
    address: "600 Decatur St",
    neighborhood: "French Quarter",
    hours: daily(T(10), T(19)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "The old Jax beer brewery is now a mall that mostly sells hot sauce and t-shirts — and quietly provides air-conditioned restrooms nobody guards. Head upstairs.",
  },
  {
    id: "canal-place",
    name: "The Shops at Canal Place",
    category: "public",
    lat: 29.95167,
    lng: -90.06525,
    address: "333 Canal St, Level 3",
    neighborhood: "CBD",
    hours: week([R(T(12), T(18))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))]),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "The fancy mall. Ride up to level three by the food court and enjoy the nicest free restrooms on Canal Street. Saks-adjacent marble, zero questions asked.",
  },
  {
    id: "caesars-casino",
    name: "Caesars New Orleans (Casino)",
    category: "public",
    lat: 29.95021,
    lng: -90.06545,
    address: "8 Canal St",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Open 24/7/365 — the single most reliable toilet in New Orleans at 3 a.m. Walk past the slots like you're feeling lucky. 21+ for the gaming floor and they may card at the door late night.",
  },
  {
    id: "royal-sonesta",
    name: "Royal Sonesta Lobby",
    category: "lobby",
    lat: 29.95592,
    lng: -90.0686,
    address: "300 Bourbon St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    osmToilet: true,
    tip: "The mid-Bourbon miracle. A restroom just off the lobby has quietly rescued thousands. Shoulders back, phone out, walk past the concierge like your room key is in your other pocket.",
  },
  {
    id: "hotel-monteleone",
    name: "Hotel Monteleone Lobby",
    category: "lobby",
    lat: 29.95419,
    lng: -90.06794,
    address: "214 Royal St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    tip: "Literary landmark with a rotating Carousel Bar and a lobby restroom that asks no questions. Worth a slow lap past the bar on your way out — it really does spin.",
  },
  {
    id: "ritz-carlton",
    name: "The Ritz-Carlton Lobby",
    category: "lobby",
    lat: 29.95476,
    lng: -90.07093,
    address: "921 Canal St",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    tip: "The nicest emergency of your life. Through the old Maison Blanche doors on Canal, act like you're late for a spa appointment, and follow the marble.",
  },
  {
    id: "historic-no-collection",
    name: "The Historic New Orleans Collection",
    category: "public",
    lat: 29.95669,
    lng: -90.06571,
    address: "520 Royal St",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(10, 30), T(16, 30))],
      null,
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A free museum on Royal with courtyards, air conditioning, and immaculate restrooms. The Quarter's best-kept secret when you need ten civilized minutes. Closed Mondays.",
  },
  {
    id: "cafe-beignet-royal",
    name: "Café Beignet (Royal St)",
    category: "customers",
    lat: 29.95535,
    lng: -90.06685,
    address: "334 Royal St",
    neighborhood: "French Quarter",
    hours: daily(T(8), T(22)),
    free: false,
    verify: true,
    tip: "Beignets are the price of admission, which is hardly a punishment. Shares a courtyard with the NOPD 8th District station — this is the single worst spot in the city to improvise, so use the actual toilet.",
  },
  {
    id: "deja-vu",
    name: "Déjà Vu Bar & Grill",
    category: "customers",
    lat: 29.95692,
    lng: -90.06852,
    address: "400 Dauphine St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A bar and grill that basically never closes, one block off Bourbon. Order a cheeseburger at 4 a.m., use the restroom, question nothing.",
  },
  {
    id: "clover-grill",
    name: "Clover Grill",
    category: "customers",
    lat: 29.96028,
    lng: -90.06403,
    address: "900 Bourbon St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Legendary greasy spoon on lower Bourbon — burgers cooked under a hubcap since forever. Historically 24/7; hours have wobbled in recent years, but late night is usually safe.",
  },
  {
    id: "mollys-at-the-market",
    name: "Molly's at the Market",
    category: "customers",
    lat: 29.96017,
    lng: -90.06002,
    address: "1107 Decatur St",
    neighborhood: "French Quarter",
    hours: daily(T(10), T(28)),
    free: false,
    verify: true,
    tip: "Lower Decatur institution, open deep into the night. The frozen Irish coffee is the toll — pay it gladly.",
  },
  // ——— CBD, Warehouse District & Tremé ———
  {
    id: "riverwalk-outlets",
    name: "The Outlet Collection at Riverwalk",
    category: "public",
    lat: 29.94585,
    lng: -90.06245,
    address: "500 Port of New Orleans Pl",
    neighborhood: "CBD",
    hours: week([R(T(11), T(18))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(20))], [R(T(10), T(20))]),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Outlet mall along the river behind the Hilton. Restrooms on both levels, mapped on OpenStreetMap. Cool, calm, and nobody checks whether you actually bought sneakers.",
  },
  {
    id: "basin-st-station",
    name: "Basin St. Station Visitor Center",
    category: "public",
    lat: 29.95988,
    lng: -90.0708,
    address: "501 Basin St",
    neighborhood: "Tremé",
    hours: daily(T(9), T(17)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "A visitor center in a handsome old railway building at the edge of Tremé, steps from St. Louis Cemetery No. 1 and Armstrong Park. Clean restrooms, free maps, actual chairs.",
  },
  {
    id: "nopl-main-library",
    name: "New Orleans Public Library (Main)",
    category: "public",
    lat: 29.95451,
    lng: -90.07539,
    address: "219 Loyola Ave",
    neighborhood: "CBD",
    hours: week(
      [R(T(12), T(17))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "The main public library. Free, air-conditioned, and nobody has ever once been judged there.",
  },
  {
    id: "union-passenger-terminal",
    name: "Union Passenger Terminal",
    category: "public",
    lat: 29.94631,
    lng: -90.07837,
    address: "1001 Loyola Ave",
    neighborhood: "CBD",
    hours: daily(T(5, 30), T(22)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    tip: "The Amtrak/Greyhound station. Open 5:30 a.m. to 10 p.m. daily — hours confirmed on OpenStreetMap in 2026, which is more than most bars in this town can say.",
  },
  {
    id: "sazerac-house",
    name: "The Sazerac House",
    category: "public",
    lat: 29.95169,
    lng: -90.06756,
    address: "101 Magazine St",
    neighborhood: "CBD",
    hours: week(
      [R(T(10), T(18))],
      null,
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A free museum about drinking that hands out cocktail samples and has spotless restrooms. New Orleans, summarized in one building. Check days before you march over.",
  },
  {
    id: "auction-house-market",
    name: "Auction House Market",
    category: "customers",
    lat: 29.94517,
    lng: -90.0694,
    address: "801 Magazine St",
    neighborhood: "Warehouse District",
    hours: daily(T(8), T(21)),
    free: false,
    verify: true,
    tip: "Warehouse District food hall under chandeliers. Grab a coffee or a cocktail, use the facilities, feel fancy about the whole transaction.",
  },
  {
    id: "ww2-museum",
    name: "National WWII Museum (Lobby)",
    category: "public",
    lat: 29.94214,
    lng: -90.07077,
    address: "945 Magazine St",
    neighborhood: "Warehouse District",
    hours: daily(T(9), T(17)),
    free: true,
    wheelchair: true,
    tip: "Restrooms in the lobby pavilion before the ticket line. It's the top-rated museum in America, not a rest stop — be respectful. But when you gotta, you gotta.",
  },
  {
    id: "the-barnett",
    name: "The Barnett Lobby (ex-Ace Hotel)",
    category: "lobby",
    lat: 29.94832,
    lng: -90.07195,
    address: "600 Carondelet St",
    neighborhood: "Warehouse District",
    hours: "24/7",
    free: true,
    tip: "The hotel formerly known as Ace. Cool-kid lobby, lots of laptops, restrooms past the bar. Nobody at the front desk is paid enough to stop you.",
  },
  // ——— Marigny & Bywater ———
  {
    id: "st-roch-market",
    name: "St. Roch Market",
    category: "customers",
    lat: 29.96959,
    lng: -90.05216,
    address: "2381 St. Claude Ave",
    neighborhood: "Marigny",
    hours: daily(T(9), T(21)),
    free: false,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Airy food hall on St. Claude. Its restrooms are mapped as publicly accessible on OpenStreetMap, but ordering an oyster or two is good manners.",
  },
  {
    id: "dat-dog-frenchmen",
    name: "Dat Dog (Frenchmen St)",
    category: "customers",
    lat: 29.96367,
    lng: -90.05768,
    address: "601 Frenchmen St",
    neighborhood: "Marigny",
    hours: week(
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
    ),
    free: false,
    verify: true,
    tip: "The restroom situation on Frenchmen is dire; Dat Dog is your out. A sausage, a balcony over the street, and facilities that beat every music club on the block.",
  },
  {
    id: "bywater-bakery",
    name: "Bywater Bakery",
    category: "customers",
    lat: 29.963,
    lng: -90.03912,
    address: "3624 Dauphine St",
    neighborhood: "Bywater",
    hours: daily(T(7), T(15)),
    free: false,
    verify: true,
    tip: "King cake all year round and a friendly restroom while your coffee is poured. Deep Bywater — mornings only, so plan accordingly.",
  },
  // ——— Garden District & Uptown ———
  {
    id: "district-donuts",
    name: "District Donuts Sliders Brew",
    category: "customers",
    lat: 29.9295,
    lng: -90.07716,
    address: "2209 Magazine St",
    neighborhood: "Lower Garden District",
    hours: daily(T(7), T(19)),
    free: false,
    verify: true,
    tip: "Donuts, sliders, coffee — and a restroom on the Magazine Street shopping crawl, where options run mysteriously thin.",
  },
  {
    id: "whole-foods-magazine",
    name: "Whole Foods Market (Arabella Station)",
    category: "customers",
    lat: 29.92078,
    lng: -90.11766,
    address: "5600 Magazine St",
    neighborhood: "Uptown",
    hours: daily(T(8), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A grocery store in a converted streetcar barn. Dependable restrooms in the middle of the Magazine Street mile — grab a kombucha if your conscience insists.",
  },
  {
    id: "audubon-park",
    name: "Audubon Park Restrooms",
    category: "public",
    lat: 29.93302,
    lng: -90.12225,
    address: "Audubon Park, near the golf clubhouse, 6500 Magazine St",
    neighborhood: "Uptown",
    hours: daily(T(6), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Free park restrooms near the golf clubhouse, mapped on OpenStreetMap. Live oaks, joggers, zero judgment.",
  },
  {
    id: "the-fly",
    name: "The Fly (Audubon Riverview)",
    category: "public",
    lat: 29.92163,
    lng: -90.13463,
    address: "Riverview Dr, behind Audubon Park",
    neighborhood: "Uptown",
    hours: daily(T(6), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "The riverside back porch of Audubon Park, where locals watch sunsets and container ships. Restrooms by the picnic shelters — unisex, mapped on OSM.",
  },
  // ——— Mid-City & City Park ———
  {
    id: "cafe-du-monde-city-park",
    name: "Café du Monde (City Park)",
    category: "customers",
    lat: 29.98543,
    lng: -90.0951,
    address: "56 Dreyfous Dr, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(20)),
    free: false,
    verify: true,
    tip: "Unlike the famous original — which has no restroom at all — this Café du Monde lives in City Park's historic Casino Building and does. Beignets first, obviously.",
  },
  {
    id: "besthoff-sculpture-garden",
    name: "Besthoff Sculpture Garden",
    category: "public",
    lat: 29.98776,
    lng: -90.0924,
    address: "1 Collins Diboll Cir, City Park",
    neighborhood: "City Park",
    hours: daily(T(10), T(17)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Free to enter and genuinely world-class: eleven acres of sculpture under the live oaks, with restrooms mapped on OSM. Art, shade, and relief, all gratis.",
  },
  {
    id: "city-park-festival-grounds",
    name: "City Park Festival Grounds Restrooms",
    category: "public",
    lat: 29.98771,
    lng: -90.09795,
    address: "Festival Grounds, near Tad Gormley Stadium, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(18)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Out by Tad Gormley Stadium on the Festival Grounds. Most reliable on event and festival days — can be locked on sleepy weekdays, so have a City Park plan B (the Sculpture Garden).",
  },
  {
    id: "whole-foods-broad",
    name: "Whole Foods Market (N Broad)",
    category: "customers",
    lat: 29.96708,
    lng: -90.08444,
    address: "300 N Broad St",
    neighborhood: "Mid-City",
    hours: daily(T(8), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Mid-City's dependable option in the ReFresh Project building, near the Lafitte Greenway. Grocery-store restrooms: never glamorous, always there.",
  },
];
