import type { Spot } from "../types";
import { T, R, daily, week } from "./helpers";

/** Algiers and Algiers Point — the West Bank, a free ferry ride away. */
export const ALGIERS_SPOTS: readonly Spot[] = [
  {
    id: "algiers-regional-library",
    name: "Algiers Regional Library",
    category: "public",
    lat: 29.92425,
    lng: -90.01413,
    address: "3014 Holiday Dr, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A large regional branch on the West Bank, rebuilt as 'a library for the future' with modern facilities. Good option on the Algiers side, away from the ferry landing crowds.",
  },
  {
    id: "george-v-rainey-natatorium",
    name: "George V. Rainey Natatorium",
    category: "public",
    lat: 29.94182,
    lng: -90.03005,
    address: "2529 General Meyer Ave, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(8), T(20))],
      [R(T(7), T(19))],
      [R(T(8), T(20))],
      [R(T(7), T(19))],
      [R(T(8), T(19))],
      [R(T(9), T(14))],
    ),
    free: true,
    wheelchair: true,
    tip: "The West Bank's first indoor pool and the city's first public splash pad, opened 2025 as a brand-new $10 million NORD complex inside Morris F.X. Jeff Sr. Park. Opening-day coverage confirms new bathrooms and disability-accessible locker rooms — fresh construction, not iffy old plumbing. Closed Sundays.",
  },
  {
    id: "racetrac-gen-degaulle",
    name: "RaceTrac (Gen. DeGaulle)",
    category: "customers",
    lat: 29.9263,
    lng: -90.0235,
    address: "3500 General De Gaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A big, bright, 24-hour RaceTrac on the West Bank with indoor seating and restrooms reviewers specifically call out as clean. Grab a drink at the register and duck in without feeling rushed.",
  },
  {
    id: "rouses-general-degaulle",
    name: "Rouses Market #36 (Algiers / General DeGaulle)",
    category: "customers",
    lat: 29.91888,
    lng: -90.01437,
    address: "4001 General DeGaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "The main full-service grocery on the West Bank side of the parish, tucked in Holiday Square with a bakery, deli, seafood, and sushi counter. Handy anchor for anyone stranded on the Algiers side of the river.",
  },
  {
    id: "starbucks-general-de-gaulle-holiday",
    name: "Starbucks (General De Gaulle & Holiday)",
    category: "customers",
    lat: 29.92002,
    lng: -90.01504,
    address: "3400 Holiday Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(4, 30), T(22)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "One of the few reliable coffee-shop restrooms on the West Bank, near the Village Aurora shopping center. Reviewers say it's clean but locked — ask the barista for the door code.",
  },
  {
    id: "waffle-house-general-de-gaulle",
    name: "Waffle House #2072",
    category: "customers",
    lat: 29.92889,
    lng: -90.03195,
    address: "2631 General De Gaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "The West Bank's round-the-clock Waffle House on General De Gaulle Dr — a rare 24-hour restroom option in Algiers proper. A cheap coffee buys you access any hour.",
  },
  {
    id: "walmart-behrman-place",
    name: "Walmart Supercenter (Behrman Place)",
    category: "public",
    lat: 29.91558,
    lng: -90.01757,
    address: "4001 Behrman Pl, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(6), T(23)),
    free: true,
    verify: true,
    tip: "The big Supercenter serving the West Bank, with free restrooms just past the entrance. Open early to late daily, and it's basically the only game in town if you're stuck on the Algiers side of the river.",
  },
  {
    id: "cita-dennis-hubbell-library",
    name: "Cita Dennis Hubbell Branch Library",
    category: "public",
    lat: 29.95308,
    lng: -90.04821,
    address: "725 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    verify: true,
    tip: "The oldest operating branch in the NOPL system, open since 1907, a short walk from the Algiers Point ferry landing. Free, walk-in public restroom, no card or purchase needed.",
  },
  {
    id: "congregation-coffee-algiers-point",
    name: "Congregation Coffee Roasters (Algiers Point)",
    category: "customers",
    lat: 29.95187,
    lng: -90.05346,
    address: "240 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      null,
      null,
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A specialty coffee roaster and cafe steps from the ferry landing, back under new ownership after a 2023 shakeup. Reviewers call the bathroom clean and well-stocked, right down to a diaper-changing station — worth the coffee-shop courtesy of buying something first.",
  },
  {
    id: "old-point-bar-algiers",
    name: "Old Point Bar",
    category: "customers",
    lat: 29.95494,
    lng: -90.05019,
    address: "545 Patterson Dr, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A block or two from the Algiers Point ferry landing, this dive-bar institution has live music most nights and a restroom customers specifically praise as clean. Order at the bar and use the facilities without hassle.",
  },
  {
    id: "crown-and-anchor-algiers",
    name: "The Crown and Anchor English Pub",
    category: "customers",
    lat: 29.95149,
    lng: -90.05426,
    address: "200 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
    ),
    free: false,
    verify: true,
    tip: "New Orleans' only authentic English pub, a block from the Algiers Point ferry landing. Order a pint at this friendly neighborhood spot and the restroom is yours.",
  },
  {
    id: "the-little-house-algiers-point",
    name: "The Little House",
    category: "customers",
    lat: 29.94936,
    lng: -90.05252,
    address: "640 Bouny St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A cozy wine bar set up like a bottle shop, with small plates and a breezy backyard patio in Algiers Point. There's just one restroom for the whole house, so order your glass and be patient.",
  },
  {
    id: "tout-de-suite-cafe-algiers",
    name: "Tout de Suite Cafe",
    category: "customers",
    lat: 29.95209,
    lng: -90.05111,
    address: "347 Verret St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(8), T(13))],
      null,
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
    ),
    free: false,
    verify: true,
    tip: "A longtime organic anchor of Algiers Point, sitting diagonally from the Catholic church on Verret St. Order-at-the-counter coffee or a panini and the restroom comes with it — just know the kitchen stops at 12:30, half an hour before closing.",
  },
  {
    id: "burger-king-de-gaulle",
    name: "Burger King (General De Gaulle)",
    category: "customers",
    lat: 29.92007,
    lng: -90.01161,
    address: "4230 General De Gaulle Dr, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: daily(T(6), T(24)),
    free: false,
    verify: true,
    tip: "Dine-in listed on BK's own locator, deep on the De Gaulle corridor. Hours run early to midnight-ish but wobble — it's fast food, hold it loosely.",
  },
  {
    id: "cut-off-rec-center",
    name: "Cut-Off Recreation Center (NORD)",
    category: "public",
    lat: 29.92354,
    lng: -89.98253,
    address: "6600 Belgrade St, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      null,
    ),
    free: true,
    verify: true,
    tip: "Deep-Algiers city rec center with free-play gym hours, weekday evenings 4 to 9. One of the only free public restrooms on this side of the river.",
  },
  {
    id: "pjs-coffee-algiers",
    name: "PJ's Coffee (Algiers)",
    category: "customers",
    lat: 29.9211,
    lng: -90.0114,
    address: "3070 Holiday Dr, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: daily(T(6), T(19)),
    free: false,
    verify: true,
    tip: "The West Bank's own PJ's, pouring from 6 a.m. on Holiday Drive. A cold brew buys the restroom — deep-Algiers options are thin, so mark this one.",
  },
  {
    id: "popeyes-de-gaulle",
    name: "Popeyes (General De Gaulle)",
    category: "customers",
    lat: 29.92182,
    lng: -90.01662,
    address: "3825 General De Gaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(10), T(24)),
    free: false,
    verify: true,
    tip: "Second anchor on the De Gaulle corridor, open to midnight. Between this and the Burger King up the road, the West Bank drive is covered.",
  },
  {
    id: "nighthawk-napoletana",
    name: "Nighthawk Napoletana",
    category: "customers",
    lat: 29.95217,
    lng: -90.05457,
    address: "141 Delaronde St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
    ),
    free: false,
    verify: true,
    tip: "Wood-fired Neapolitan pies steps from the Algiers ferry landing — crucial intel, since the ferry terminals themselves have no restrooms until the 2027 renovation. Evenings Tuesday through Saturday.",
  },
  {
    id: "algiers-sports-bar",
    name: "Algiers Sports Bar",
    category: "customers",
    lat: 29.93251,
    lng: -90.00462,
    address: "4801 General Meyer Ave, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      [R(T(12), T(23))],
      [R(T(14), T(23))],
      [R(T(14), T(23))],
      [R(T(14), T(23))],
      [R(T(14), T(23))],
      [R(T(14), T(23))],
      [R(T(12), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Neighborhood dive on General Meyer with a pool table, darts, and TVs for the game. 21+, order a drink and the restroom's yours — documented as not wheelchair accessible, so plan accordingly.",
  },
  {
    id: "chick-fil-a-algiers-plaza",
    name: "Chick-fil-A (Village Aurora / Algiers Plaza)",
    category: "customers",
    lat: 29.92135,
    lng: -90.01386,
    address: "4130 General De Gaulle Dr, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(6), T(22))],
      [R(T(6), T(22))],
      [R(T(6), T(22))],
      [R(T(6), T(22))],
      [R(T(6), T(22))],
      [R(T(8), T(22))],
    ),
    free: false,
    verify: true,
    tip: "The West Bank's only Chick-fil-A, anchoring the Algiers Plaza retail strip. Full dine-in seating and long hours make it dependable — just note Saturdays start later at 8 a.m., and it's closed Sundays like every other Chick-fil-A on earth.",
  },
  {
    id: "chubbies-fried-chicken",
    name: "Chubbie's Fried Chicken",
    category: "customers",
    lat: 29.93226,
    lng: -90.00362,
    address: "4850 General Meyer Ave, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      null,
    ),
    free: false,
    verify: true,
    tip: "A West Bank fried chicken institution since 1982, now under new local ownership — small dine-in counter tucked behind the drive-thru on General Meyer Ave. Weekdays only, closed weekends.",
  },
  {
    id: "family-food-store-general-meyer",
    name: "Family Food Store (Algiers Discount Food Store)",
    category: "customers",
    lat: 29.93869,
    lng: -90.01921,
    address: "3549 General Meyer Ave, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(5, 30), T(23)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Neighborhood grocery and breakfast counter on General Meyer Ave slinging liver and grits, pork chop breakfasts, and stewed plates from the deli case. Restrooms are confirmed onsite and wheelchair accessible — grab a plate and use them.",
  },
  {
    id: "firehouse-subs-algiers-plaza",
    name: "Firehouse Subs (Algiers Plaza)",
    category: "customers",
    lat: 29.92079,
    lng: -90.01228,
    address: "4150 General De Gaulle Dr, Ste C, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: daily(T(10), T(21)),
    free: false,
    verify: true,
    tip: "Hot sub chain with dine-in seating inside Algiers Plaza, sharing the lot with Winn-Dixie and Chick-fil-A. Open long hours daily, and a reviewer specifically flagged the restroom as clean.",
  },
  {
    id: "yumi-sushi-hibachi-algiers",
    name: "Yumi Sushi & Hibachi",
    category: "customers",
    lat: 29.91185,
    lng: -90.00048,
    address: "5163 General De Gaulle Dr, Suite N, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      [R(T(11, 30), T(21))],
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21, 30))],
      [R(T(11, 30), T(21, 30))],
    ),
    free: false,
    verify: true,
    tip: "Full table-service sushi and hibachi in the Tall Timbers Hamlet strip, rebranded from the old Oishii Sushi House. A rare sit-down Japanese option on this stretch of General De Gaulle — closed Mondays.",
  },
  {
    id: "algiers-courthouse",
    name: "Algiers Courthouse",
    category: "public",
    lat: 29.95369,
    lng: -90.05408,
    address: "225 Morgan St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      [R(T(9), T(16))],
      [R(T(9), T(16))],
      [R(T(9), T(16))],
      [R(T(9), T(16))],
      [R(T(9), T(16))],
      null,
    ),
    free: true,
    wheelchair: true,
    tip: "An 1896 courthouse on the West Bank handling small claims, marriage licenses, and voter registration — free entry, air conditioning, and confirmed wheelchair access. A dependable stop while wandering Algiers Point on foot.",
  },
];
