import type { Spot } from "../types";
import { T, R, daily, week } from "./helpers";

/** Algiers and Algiers Point — the West Bank, a free ferry ride away. */
export const ALGIERS_SPOTS: readonly Spot[] = [
  {
    id: "algiers-regional-library",
    name: "Algiers Regional Library",
    category: "public",
    lat: 29.92425,
    lng: -90.01413,
    address: "3014 Holiday Dr, New Orleans, LA 70131",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A large regional branch on the West Bank, rebuilt as 'a library for the future' with modern facilities. Good option on the Algiers side, away from the ferry landing crowds.",
  },
  {
    id: "george-v-rainey-natatorium",
    name: "George V. Rainey Natatorium",
    category: "public",
    lat: 29.94182,
    lng: -90.03005,
    address: "2529 General Meyer Ave, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: week(
      null,
      [R(T(8), T(20))],
      [R(T(7), T(19))],
      [R(T(8), T(20))],
      [R(T(7), T(19))],
      [R(T(8), T(19))],
      [R(T(9), T(14))],
    ),
    free: true,
    wheelchair: true,
    tip: "The West Bank's first indoor pool and the city's first public splash pad, opened 2025 as a brand-new $10 million NORD complex inside Morris F.X. Jeff Sr. Park. Opening-day coverage confirms new bathrooms and disability-accessible locker rooms — fresh construction, not iffy old plumbing. Closed Sundays.",
  },
  {
    id: "racetrac-gen-degaulle",
    name: "RaceTrac (Gen. DeGaulle)",
    category: "customers",
    lat: 29.9263,
    lng: -90.0235,
    address: "3500 General De Gaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A big, bright, 24-hour RaceTrac on the West Bank with indoor seating and restrooms reviewers specifically call out as clean. Grab a drink at the register and duck in without feeling rushed.",
  },
  {
    id: "rouses-general-degaulle",
    name: "Rouses Market #36 (Algiers / General DeGaulle)",
    category: "customers",
    lat: 29.91888,
    lng: -90.01437,
    address: "4001 General DeGaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "The main full-service grocery on the West Bank side of the parish, tucked in Holiday Square with a bakery, deli, seafood, and sushi counter. Handy anchor for anyone stranded on the Algiers side of the river.",
  },
  {
    id: "starbucks-general-de-gaulle-holiday",
    name: "Starbucks (General De Gaulle & Holiday)",
    category: "customers",
    lat: 29.92002,
    lng: -90.01504,
    address: "3400 Holiday Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(4, 30), T(22)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "One of the few reliable coffee-shop restrooms on the West Bank, near the Village Aurora shopping center. Reviewers say it's clean but locked — ask the barista for the door code.",
  },
  {
    id: "waffle-house-general-de-gaulle",
    name: "Waffle House #2072",
    category: "customers",
    lat: 29.92889,
    lng: -90.03195,
    address: "2631 General De Gaulle Dr, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "The West Bank's round-the-clock Waffle House on General De Gaulle Dr — a rare 24-hour restroom option in Algiers proper. A cheap coffee buys you access any hour.",
  },
  {
    id: "walmart-behrman-place",
    name: "Walmart Supercenter (Behrman Place)",
    category: "public",
    lat: 29.91558,
    lng: -90.01757,
    address: "4001 Behrman Pl, New Orleans, LA 70114",
    neighborhood: "Algiers",
    hours: daily(T(6), T(23)),
    free: true,
    verify: true,
    tip: "The big Supercenter serving the West Bank, with free restrooms just past the entrance. Open early to late daily, and it's basically the only game in town if you're stuck on the Algiers side of the river.",
  },
  {
    id: "cita-dennis-hubbell-library",
    name: "Cita Dennis Hubbell Branch Library",
    category: "public",
    lat: 29.95308,
    lng: -90.04821,
    address: "725 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    verify: true,
    tip: "The oldest operating branch in the NOPL system, open since 1907, a short walk from the Algiers Point ferry landing. Free, walk-in public restroom, no card or purchase needed.",
  },
  {
    id: "congregation-coffee-algiers-point",
    name: "Congregation Coffee Roasters (Algiers Point)",
    category: "customers",
    lat: 29.95187,
    lng: -90.05346,
    address: "240 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      null,
      null,
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A specialty coffee roaster and cafe steps from the ferry landing, back under new ownership after a 2023 shakeup. Reviewers call the bathroom clean and well-stocked, right down to a diaper-changing station — worth the coffee-shop courtesy of buying something first.",
  },
  {
    id: "old-point-bar-algiers",
    name: "Old Point Bar",
    category: "customers",
    lat: 29.95494,
    lng: -90.05019,
    address: "545 Patterson Dr, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A block or two from the Algiers Point ferry landing, this dive-bar institution has live music most nights and a restroom customers specifically praise as clean. Order at the bar and use the facilities without hassle.",
  },
  {
    id: "crown-and-anchor-algiers",
    name: "The Crown and Anchor English Pub",
    category: "customers",
    lat: 29.95149,
    lng: -90.05426,
    address: "200 Pelican Ave, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
    ),
    free: false,
    verify: true,
    tip: "New Orleans' only authentic English pub, a block from the Algiers Point ferry landing. Order a pint at this friendly neighborhood spot and the restroom is yours.",
  },
  {
    id: "the-little-house-algiers-point",
    name: "The Little House",
    category: "customers",
    lat: 29.94936,
    lng: -90.05252,
    address: "640 Bouny St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      null,
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A cozy wine bar set up like a bottle shop, with small plates and a breezy backyard patio in Algiers Point. There's just one restroom for the whole house, so order your glass and be patient.",
  },
  {
    id: "tout-de-suite-cafe-algiers",
    name: "Tout de Suite Cafe",
    category: "customers",
    lat: 29.95209,
    lng: -90.05111,
    address: "347 Verret St, New Orleans, LA 70114",
    neighborhood: "Algiers Point",
    hours: week(
      [R(T(8), T(13))],
      null,
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
      [R(T(8), T(13))],
    ),
    free: false,
    verify: true,
    tip: "A longtime organic anchor of Algiers Point, sitting diagonally from the Catholic church on Verret St. Order-at-the-counter coffee or a panini and the restroom comes with it — just know the kitchen stops at 12:30, half an hour before closing.",
  },
];
