import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** CBD, Warehouse District, and Tremé. */
export const DOWNTOWN_SPOTS: readonly Spot[] = [
  {
    id: "canal-place",
    name: "The Shops at Canal Place",
    category: "public",
    lat: 29.95167,
    lng: -90.06525,
    address: "333 Canal St, Level 3",
    neighborhood: "CBD",
    hours: week([R(T(12), T(18))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))]),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "The fancy mall. Ride up to level three by the food court and enjoy the nicest free restrooms on Canal Street. Saks-adjacent marble, zero questions asked.",
  },
  {
    id: "caesars-casino",
    name: "Caesars New Orleans (Casino)",
    category: "public",
    lat: 29.95021,
    lng: -90.06545,
    address: "8 Canal St",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Open 24/7/365 — the single most reliable toilet in New Orleans at 3 a.m. Walk past the slots like you're feeling lucky. 21+ for the gaming floor and they may card at the door late night.",
  },
  {
    id: "ritz-carlton",
    name: "The Ritz-Carlton Lobby",
    category: "lobby",
    lat: 29.95476,
    lng: -90.07093,
    address: "921 Canal St",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    tip: "The nicest emergency of your life. Through the old Maison Blanche doors on Canal, act like you're late for a spa appointment, and follow the marble.",
  },
  {
    id: "riverwalk-outlets",
    name: "The Outlet Collection at Riverwalk",
    category: "public",
    lat: 29.94585,
    lng: -90.06245,
    address: "500 Port of New Orleans Pl",
    neighborhood: "CBD",
    hours: week([R(T(11), T(18))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(19))], [R(T(10), T(20))], [R(T(10), T(20))]),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Outlet mall along the river behind the Hilton. Restrooms on both levels, mapped on OpenStreetMap. Cool, calm, and nobody checks whether you actually bought sneakers.",
  },
  {
    id: "basin-st-station",
    name: "Basin St. Station Visitor Center",
    category: "public",
    lat: 29.95988,
    lng: -90.0708,
    address: "501 Basin St",
    neighborhood: "Tremé",
    hours: daily(T(9), T(17)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "A visitor center in a handsome old railway building at the edge of Tremé, steps from St. Louis Cemetery No. 1 and Armstrong Park. Clean restrooms, free maps, actual chairs.",
  },
  {
    id: "nopl-main-library",
    name: "New Orleans Public Library (Main)",
    category: "public",
    lat: 29.95451,
    lng: -90.07539,
    address: "219 Loyola Ave",
    neighborhood: "CBD",
    hours: week(
      [R(T(12), T(17))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "The main public library. Free, air-conditioned, and nobody has ever once been judged there.",
  },
  {
    id: "union-passenger-terminal",
    name: "Union Passenger Terminal",
    category: "public",
    lat: 29.94631,
    lng: -90.07837,
    address: "1001 Loyola Ave",
    neighborhood: "CBD",
    hours: daily(T(5, 30), T(22)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    tip: "The Amtrak/Greyhound station. Open 5:30 a.m. to 10 p.m. daily — hours confirmed on OpenStreetMap in 2026, which is more than most bars in this town can say.",
  },
  {
    id: "sazerac-house",
    name: "The Sazerac House",
    category: "public",
    lat: 29.95169,
    lng: -90.06756,
    address: "101 Magazine St",
    neighborhood: "CBD",
    hours: week(
      [R(T(10), T(18))],
      null,
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A free museum about drinking that hands out cocktail samples and has spotless restrooms. New Orleans, summarized in one building. Check days before you march over.",
  },
  {
    id: "auction-house-market",
    name: "Auction House Market",
    category: "customers",
    lat: 29.94517,
    lng: -90.0694,
    address: "801 Magazine St",
    neighborhood: "Warehouse District",
    hours: daily(T(8), T(21)),
    free: false,
    verify: true,
    tip: "Warehouse District food hall under chandeliers. Grab a coffee or a cocktail, use the facilities, feel fancy about the whole transaction.",
  },
  {
    id: "ww2-museum",
    name: "National WWII Museum (Lobby)",
    category: "public",
    lat: 29.94214,
    lng: -90.07077,
    address: "945 Magazine St",
    neighborhood: "Warehouse District",
    hours: daily(T(9), T(17)),
    free: true,
    wheelchair: true,
    tip: "Restrooms in the lobby pavilion before the ticket line. It's the top-rated museum in America, not a rest stop — be respectful. But when you gotta, you gotta.",
  },
  {
    id: "the-barnett",
    name: "The Barnett Lobby (ex-Ace Hotel)",
    category: "lobby",
    lat: 29.94832,
    lng: -90.07195,
    address: "600 Carondelet St",
    neighborhood: "Warehouse District",
    hours: "24/7",
    free: true,
    tip: "The hotel formerly known as Ace. Cool-kid lobby, lots of laptops, restrooms past the bar. Nobody at the front desk is paid enough to stop you.",
  },
  {
    id: "cleos-canal-st",
    name: "Cleo's Mediterranean Cuisine & Grocery (Canal St)",
    category: "customers",
    lat: 29.95476,
    lng: -90.07192,
    address: "940 Canal St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: "24/7",
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A 24-hour Mediterranean counter and grocery hybrid right on Canal St near the streetcar line. Grab a gyro, use the gender-neutral restroom, and you're back on the street in five minutes flat.",
  },
  {
    id: "daisy-dukes-express-carondelet",
    name: "Daisy Dukes Express (Carondelet)",
    category: "customers",
    lat: 29.95332,
    lng: -90.07063,
    address: "123 Carondelet St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "A 24-hour breakfast and Cajun comfort food counter near Canal and Carondelet, with a restroom for customers (one reviewer's complaint about a broken stall lock is at least proof it exists). Sources disagree hard on hours — some say round-the-clock, others say it closes by early afternoon or evening — so call (504) 522-2218 before making a special trip.",
  },
  {
    id: "french-truck-coffee-poydras",
    name: "French Truck Coffee (Poydras St)",
    category: "customers",
    lat: 29.94892,
    lng: -90.07014,
    address: "650 Poydras St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: week(
      [R(T(8), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(8), T(17))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A Warehouse District outpost of the local roaster, a few blocks from the Convention Center. Grab a New Orleans iced coffee and use the wheelchair-accessible restroom before you head back to the hall.",
  },
  {
    id: "intercontinental-new-orleans-lobby",
    name: "InterContinental New Orleans Lobby",
    category: "lobby",
    lat: 29.95034,
    lng: -90.06971,
    address: "444 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A AAA Four-Diamond hotel two blocks off the French Quarter, right on the St. Charles streetcar line. The expansive lobby is easy to walk into and makes a solid stop between the CBD and the Garden District.",
  },
  {
    id: "le-pavillon-hotel-lobby",
    name: "Le Pavillon Hotel Lobby",
    category: "lobby",
    lat: 29.95061,
    lng: -90.07275,
    address: "833 Poydras St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: UNKNOWN_HOURS,
    free: true,
    verify: true,
    tip: "A grand marble lobby with crystal chandeliers, famous for its free nightly PB&J-and-milk tradition running since 1988 — which makes walking through like you belong there feel completely natural. Restrooms are off the main lobby near the historic public spaces.",
  },
  {
    id: "new-orleans-marriott-lobby",
    name: "New Orleans Marriott Lobby",
    category: "lobby",
    lat: 29.95288,
    lng: -90.06733,
    address: "555 Canal St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A large, 1,300-room hotel lobby on Canal Street with a wheelchair-accessible restroom just off the entrance. The crowds here reportedly rival Bourbon Street, so slipping in unnoticed is easy any hour of the day or night.",
  },
  {
    id: "pjs-coffee-poydras-cbd",
    name: "PJ's Coffee (Poydras St / CBD)",
    category: "customers",
    lat: 29.9522,
    lng: -90.0784,
    address: "1515 Poydras St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: week(
      null,
      [R(T(5), T(16))],
      [R(T(5), T(16))],
      [R(T(5), T(16))],
      [R(T(5), T(16))],
      [R(T(5), T(16))],
      null,
    ),
    free: false,
    verify: true,
    tip: "A CBD coffee shop directly across from the Superdome and Smoothie King Center — the coffeehouse near the dome. Reliable weekday-morning restroom stop for early arrivals to day games or downtown business, but it's closed weekends, so don't count on it before a Saturday event.",
  },
  {
    id: "rouses-baronne-st-cbd",
    name: "Rouses Market (Baronne Street CBD)",
    category: "customers",
    lat: 29.94772,
    lng: -90.07417,
    address: "701 Baronne St, New Orleans, LA 70113",
    neighborhood: "CBD",
    hours: daily(T(6), T(23)),
    free: false,
    verify: true,
    tip: "A 40,000-square-foot supermarket a few blocks from the Superdome, open until 11 p.m. every night. Restrooms are past the produce section if you come in through the Baronne corner. Grab a snack, use the facilities, get back to Champions Square.",
  },
  {
    id: "starbucks-hyatt-regency-loyola",
    name: "Starbucks (Hyatt Regency New Orleans, 2nd Floor)",
    category: "customers",
    lat: 29.94955,
    lng: -90.07727,
    address: "601 Loyola Ave, New Orleans, LA 70113",
    neighborhood: "CBD",
    hours: week(
      [R(T(6), T(15))],
      [R(T(6), T(17))],
      [R(T(6), T(17))],
      [R(T(6), T(17))],
      [R(T(6), T(17))],
      [R(T(6), T(17))],
      [R(T(6), T(15))],
    ),
    free: false,
    verify: true,
    tip: "Tucked inside the Hyatt Regency near City Hall, the Superdome, and Union Passenger Terminal — a solid in-and-out stop for anyone arriving by train or bus. Plentiful seating and free wifi if you need to linger.",
  },
  {
    id: "starbucks-sheraton-canal-st",
    name: "Starbucks (Sheraton New Orleans Lobby)",
    category: "customers",
    lat: 29.95202,
    lng: -90.0678,
    address: "500 Canal St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: daily(T(6), T(17)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Just inside the Sheraton's Canal Street entrance, an easy walk-in for anyone near the foot of Canal, the casino, or the French Quarter. Buy a coffee, then head for the lobby restroom like you're a guest.",
  },
  {
    id: "eliza-jane-lobby",
    name: "The Eliza Jane Lobby",
    category: "lobby",
    lat: 29.9504,
    lng: -90.06774,
    address: "315 Magazine St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    verify: true,
    tip: "A boutique Autograph Collection hotel built from historic warehouse buildings, two blocks off the Quarter. The Press Room lobby bar is open to the public daily with happy hour 2-5pm, so the ground floor stays welcoming — walk in like you're meeting someone for a drink.",
  },
  {
    id: "wendys-st-charles-ave",
    name: "Wendy's (St. Charles Ave)",
    category: "customers",
    lat: 29.94046,
    lng: -90.07495,
    address: "1301 St. Charles Ave, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: week(
      [R(T(6, 30), T(25))],
      [R(T(6), T(25))],
      [R(T(6), T(25))],
      [R(T(6), T(25))],
      [R(T(6), T(25))],
      [R(T(6), T(25))],
      [R(T(6), T(25))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Right on the St. Charles streetcar line at Lee Circle, open until 1 a.m. nightly. A reviewer put it best: for a dollar you can get a Frosty and use a clean bathroom.",
  },
  {
    id: "central-city-library",
    name: "Central City Library",
    category: "public",
    lat: 29.93849,
    lng: -90.08426,
    address: "2020 Jackson Ave, Suite 139, New Orleans, LA 70113",
    neighborhood: "Central City",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    verify: true,
    tip: "A branch tucked inside the Allie Mae Williams Multi-Service Center on Jackson Avenue. Free, walk-in restroom during all open hours, no library card or purchase required.",
  },
  {
    id: "dooky-chases-restaurant",
    name: "Dooky Chase's Restaurant",
    category: "customers",
    lat: 29.96821,
    lng: -90.07849,
    address: "2301 Orleans Ave, New Orleans, LA 70119",
    neighborhood: "Tremé",
    hours: week(
      null,
      null,
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15)), R(T(17, 30), T(21))],
      [R(T(17, 30), T(21))],
    ),
    free: false,
    tip: "The legendary Creole restaurant tied to the civil rights movement and the late Chef Leah Chase. Grab a plate for lunch (or dinner Friday and Saturday) in this walk-in dining room and the restroom is part of the experience.",
  },
  {
    id: "fritai-basin-st",
    name: "Fritai",
    category: "customers",
    lat: 29.96028,
    lng: -90.06945,
    address: "1535 Basin St, New Orleans, LA 70116",
    neighborhood: "Tremé",
    hours: week(
      [R(T(11), T(17))],
      [R(T(16), T(21))],
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "James Beard-recognized Haitian street food near Congo Square, run by chef Charly Pierre. Wheelchair accessible with a gender-neutral restroom, which is more than most small Tremé spots can say. Closed Tuesdays.",
  },
  {
    id: "lil-dizzys-cafe",
    name: "Li'l Dizzy's Cafe",
    category: "customers",
    lat: 29.96866,
    lng: -90.06792,
    address: "1500 Esplanade Ave, New Orleans, LA 70116",
    neighborhood: "Tremé",
    hours: week(
      null,
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A Tremé institution for fried chicken and gumbo right on Esplanade Ave. Order at the counter, grab a table, and you're a paying customer with a real dining-room restroom. Closed Sundays except one a month, so plan around it.",
  },
  {
    id: "treme-coffeehouse-st-philip",
    name: "Treme Coffeehouse",
    category: "customers",
    lat: 29.96542,
    lng: -90.06956,
    address: "1501 St Philip St, New Orleans, LA 70116",
    neighborhood: "Tremé",
    hours: week(
      [R(T(8), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(8), T(14))],
    ),
    free: false,
    tip: "A neighborhood coffee shop a few blocks from Armstrong Park and the Backstreet Cultural Museum. Buy a coffee and the single restroom is right there — reviewers confirm it's clean, though the key sometimes lives at the register.",
  },
  {
    id: "treme-recreation-community-center",
    name: "Treme Recreation Community Center",
    category: "public",
    lat: 29.9645,
    lng: -90.06977,
    address: "900 N Villere St, New Orleans, LA 70116",
    neighborhood: "Tremé",
    hours: week(
      null,
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(9), T(14))],
    ),
    free: true,
    verify: true,
    tip: "A short walk from the French Quarter, with a year-round indoor pool, gym, and locker rooms. Rated 4.6/5 by visitors, with reviewers specifically calling out clean facilities. Closed Sundays.",
  },
  {
    id: "bearcat-baked-julia-st",
    name: "Bearcat Baked",
    category: "customers",
    lat: 29.94599,
    lng: -90.07254,
    address: "726 Julia St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: week(
      [R(T(8), T(15))],
      [R(T(8), T(14))],
      [R(T(8), T(14))],
      [R(T(8), T(14))],
      [R(T(8), T(14))],
      [R(T(8), T(14))],
      [R(T(8), T(15))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A pastry-and-coffee bakery-cafe on gallery row in the Arts/Warehouse District. Small purchase, wheelchair-accessible entrance, clean restroom among the gallery-hopping blocks.",
  },
  {
    id: "cochon-butcher",
    name: "Cochon Butcher",
    category: "customers",
    lat: 29.9422,
    lng: -90.067,
    address: "930 Tchoupitoulas St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "A Warehouse District institution since 2009 — sandwich counter and wine bar next door to Cochon. Grab a muffuletta and check out the Chewbacca wallpaper in the men's room, a small only-in-New-Orleans detail.",
  },
  {
    id: "cac-mr-wolf-espresso",
    name: "Contemporary Arts Center (Mr. Wolf Espresso lobby)",
    category: "customers",
    lat: 29.94378,
    lng: -90.07085,
    address: "900 Camp St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: week(
      null,
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(9), T(14))],
    ),
    free: false,
    wheelchair: true,
    tip: "A coffee counter in the CAC's ground-floor lobby, so you can grab an espresso without buying a gallery ticket. Wheelchair-accessible restrooms are confirmed on the first floor, right off that same lobby.",
  },
  {
    id: "mannings-fulton-st",
    name: "Manning's",
    category: "customers",
    lat: 29.948,
    lng: -90.06538,
    address: "519 Fulton St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: week(
      [R(T(11), T(22))],
      null,
      null,
      null,
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A walk-in sports bar on the pedestrian Fulton Street mall next to Caesars and the Convention Center, with 30+ TVs and a full pub menu. Order a beer or a po'boy in this high-traffic tourist stretch and use the restroom — no need to set foot on the casino floor. Closed Monday through Wednesday.",
  },
  {
    id: "pour-house-at-district",
    name: "Pour House at District",
    category: "customers",
    lat: 29.94753,
    lng: -90.0717,
    address: "735 Girod St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: daily(T(11), T(26)),
    free: false,
    verify: true,
    tip: "A sports bar and grill with a New Orleans pedigree dating to 1952, a short walk from Champions Square and the Superdome's Girod Street entrances. Full bar and food menu, open daily until 2 a.m. — solid pre- or post-game stop for a modest purchase.",
  },
  {
    id: "higgins-hotel-lobby",
    name: "The Higgins Hotel New Orleans (Curio Collection by Hilton) Lobby",
    category: "lobby",
    lat: 29.94216,
    lng: -90.06967,
    address: "1000 Magazine St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: "24/7",
    free: true,
    verify: true,
    tip: "The official hotel of the National WWII Museum, with a grand WWII-themed lobby and Kilroy's Bar & Lounge right off the entrance at Andrew Higgins Blvd and Magazine St. The front desk runs 24/7, so it's an easy walk-in option if you're touring the museum campus across the street.",
  },
  {
    id: "virgin-hotels-baronne-st",
    name: "Virgin Hotels New Orleans Lobby",
    category: "lobby",
    lat: 29.94942,
    lng: -90.07318,
    address: "550 Baronne St, New Orleans, LA 70113",
    neighborhood: "Warehouse District",
    hours: "24/7",
    free: true,
    verify: true,
    tip: "A newer lifestyle hotel a block from the Carondelet streetcar stop, with a lively lobby, coffee shop, and bar/restaurant scene that draws more non-guests than guests. Walk in like you're meeting someone for a drink and the restroom is right there.",
  },
  {
    id: "audubon-aquarium-lobby",
    name: "Audubon Aquarium & Insectarium (Lobby)",
    category: "public",
    lat: 29.95088,
    lng: -90.06321,
    address: "1 Canal St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: daily(T(10), T(17)),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "Audubon's own signs in Woldenberg Park point you here — the riverfront park has no restrooms, so the aquarium lobby serves everyone. The accessible, gender-neutral restrooms sit before the ticket line. Daily 10 to 5.",
  },
  {
    id: "roosevelt-grand-lobby",
    name: "The Roosevelt (Grand Lobby)",
    category: "lobby",
    lat: 29.95449,
    lng: -90.07222,
    address: "130 Roosevelt Way, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    verify: true,
    tip: "The block-long Grand Lobby is a tourist attraction in its own right — walk it end to end like you're headed to the Sazerac Bar and peel off at the restroom sign. Teddy's Café pours coffee until 4 p.m. if you want cover.",
  },
  {
    id: "ashe-cultural-arts-center",
    name: "Ashé Cultural Arts Center",
    category: "public",
    lat: 29.93966,
    lng: -90.08048,
    address: "1712 Oretha Castle Haley Blvd, New Orleans, LA 70113",
    neighborhood: "Central City",
    hours: week(
      null,
      null,
      [R(T(10), T(17, 30))],
      [R(T(10), T(17, 30))],
      [R(T(10), T(17, 30))],
      [R(T(10), T(17, 30))],
      [R(T(10), T(17, 30))],
    ),
    free: true,
    verify: true,
    tip: "Free community arts center and gallery that has anchored Oretha Castle Haley Blvd for decades. Walk in Tuesday through Saturday, see some art, use the facilities, leave better than you arrived.",
  },
  {
    id: "cafe-reconcile",
    name: "Café Reconcile",
    category: "customers",
    lat: 29.93991,
    lng: -90.08034,
    address: "1631 Oretha Castle Haley Blvd, New Orleans, LA 70113",
    neighborhood: "Central City",
    hours: week(
      null,
      null,
      [R(T(11), T(14, 30))],
      [R(T(11), T(14, 30))],
      [R(T(11), T(14, 30))],
      [R(T(11), T(14, 30))],
      null,
    ),
    free: false,
    verify: true,
    tip: "Nonprofit training restaurant that anchors the OC Haley corridor — your lunch money funds job training for young New Orleanians, and the restroom comes with it. Weekday lunch only, Tuesday through Friday.",
  },
  {
    id: "churchs-s-claiborne",
    name: "Church's Texas Chicken (S Claiborne)",
    category: "customers",
    lat: 29.94588,
    lng: -90.08807,
    address: "1600 S Claiborne Ave, New Orleans, LA 70125",
    neighborhood: "Central City",
    hours: daily(T(10), T(23)),
    free: false,
    verify: true,
    tip: "Fried chicken and a dine-in restroom on the S. Claiborne corridor, open until 11 nightly — one of the later options in Central City.",
  },
  {
    id: "magnolia-marketplace",
    name: "Magnolia Marketplace (TJ Maxx / Ross)",
    category: "public",
    lat: 29.94252,
    lng: -90.09509,
    address: "2900 S Claiborne Ave, New Orleans, LA 70125",
    neighborhood: "Central City",
    hours: daily(T(9, 30), T(20)),
    free: true,
    verify: true,
    tip: "The big-box cluster at Claiborne and Toledano — TJ Maxx, Ross, Michaels, PetSmart, Ulta. Nobody in the history of retail has ever been stopped walking to a TJ Maxx restroom.",
  },
  {
    id: "southern-food-beverage-museum",
    name: "Southern Food & Beverage Museum",
    category: "customers",
    lat: 29.94076,
    lng: -90.07905,
    address: "1504 Oretha Castle Haley Blvd, New Orleans, LA 70113",
    neighborhood: "Central City",
    hours: week(
      [R(T(11), T(17))],
      [R(T(11), T(17))],
      null,
      null,
      null,
      [R(T(11), T(17))],
      [R(T(11), T(17))],
    ),
    free: false,
    verify: true,
    tip: "A whole museum about Southern eating and drinking, tickets required — so this is a destination restroom, not an emergency one. Note the odd schedule: open Friday through Monday, closed midweek. The attached Toups South restaurant has closed; the museum carries on.",
  },
  {
    id: "zony-mash-beer-project",
    name: "Zony Mash Beer Project",
    category: "customers",
    lat: 29.95215,
    lng: -90.09759,
    address: "3940 Thalia St, New Orleans, LA 70125",
    neighborhood: "Central City",
    hours: week(
      [R(T(12), T(21))],
      null,
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(12), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A brewery in a resurrected historic movie theater on Thalia St. Taproom pours Wednesday through Sunday — buy a pint and the restroom's yours. Ignore any stale 'closed' flags online; the official site confirms it's alive.",
  },
  {
    id: "four-seasons-lobby",
    name: "Four Seasons Hotel (Lobby)",
    category: "lobby",
    lat: 29.94895,
    lng: -90.06353,
    address: "2 Canal St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "The old World Trade Center tower, now the city's most luxurious lobby — anchored by the Chandelier Bar and its 15,000 crystals. The accessible restroom is on the lobby level; walk in like you're meeting someone at the bar.",
  },
  {
    id: "hilton-riverside-lobby",
    name: "Hilton New Orleans Riverside (Lobby)",
    category: "lobby",
    lat: 29.94729,
    lng: -90.06346,
    address: "2 Poydras St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "The convention-crowd mothership on the river, with Drago's just inside the main entrance. A lobby this size has seen everything; the restrooms are at lobby level and accessible.",
  },
  {
    id: "loews-new-orleans-lobby",
    name: "Loews New Orleans (Lobby)",
    category: "lobby",
    lat: 29.94796,
    lng: -90.06618,
    address: "300 Poydras St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Ground-floor lobby with Bar Peters and live music most evenings — busy enough that nobody clocks a restroom visit. Accessible public washroom confirmed by the hotel itself.",
  },
  {
    id: "nopsi-hotel-lobby",
    name: "NOPSI Hotel (Grand Lobby)",
    category: "lobby",
    lat: 29.95215,
    lng: -90.07303,
    address: "317 Baronne St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "The old New Orleans Public Service headquarters — vaulted ceilings, Henry's Gin Bar right off the entrance, and an ADA-compliant restroom. Where the streetcars were once dispatched, you may now relieve yourself in style.",
  },
  {
    id: "q-and-c-hotel-lobby",
    name: "Q&C Hotel (Lobby)",
    category: "lobby",
    lat: 29.95005,
    lng: -90.069,
    address: "344 Camp St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Living-room-style lobby with a craft cocktail bar in it. Accessibility documentation notes restrooms right in the lobby — small hotel, zero friction.",
  },
  {
    id: "renaissance-pere-marquette-lobby",
    name: "Renaissance Pere Marquette (Lobby)",
    category: "lobby",
    lat: 29.95302,
    lng: -90.07134,
    address: "817 Common St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Marble 1920s lobby with a coffee shop pouring beignets and live jazz some evenings. ADA-compliant public washroom confirmed — the most civilized emergency stop on Common Street.",
  },
  {
    id: "troubadour-hotel-lobby",
    name: "The Troubadour (Lobby)",
    category: "lobby",
    lat: 29.95325,
    lng: -90.07435,
    address: "1111 Gravier St, New Orleans, LA 70112",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Boutique CBD tower whose ground floor is basically a restaurant with a horseshoe bar. Walk toward the Listening Room and the facilities reveal themselves.",
  },
  {
    id: "windsor-court-lobby",
    name: "The Windsor Court (Lobby)",
    category: "lobby",
    lat: 29.94948,
    lng: -90.06635,
    address: "300 Gravier St, New Orleans, LA 70130",
    neighborhood: "CBD",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Grand columned lobby with a cocktail bar and afternoon-tea salon off it. A recent guest review describes the ground-floor lobby restroom in loving detail, which is exactly the kind of evidence this map runs on.",
  },
  {
    id: "old-no-77-lobby",
    name: "The Old No. 77 Hotel (Lobby)",
    category: "lobby",
    lat: 29.94792,
    lng: -90.06748,
    address: "535 Tchoupitoulas St, New Orleans, LA 70130",
    neighborhood: "Warehouse District",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "Exposed-brick lobby that flows into Compère Lapin and a coffee counter. The hotel's own accessibility page lists a wheelchair-accessible lobby restroom — they literally put it in writing.",
  },
];
