import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** Marigny, Bywater, St. Roch, St. Claude, and the 9th Ward. */
export const DOWNRIVER_SPOTS: readonly Spot[] = [
  {
    id: "st-roch-market",
    name: "St. Roch Market",
    category: "customers",
    lat: 29.96959,
    lng: -90.05216,
    address: "2381 St. Claude Ave",
    neighborhood: "Marigny",
    hours: daily(T(9), T(21)),
    free: false,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Airy food hall on St. Claude. Its restrooms are mapped as publicly accessible on OpenStreetMap, but ordering an oyster or two is good manners.",
  },
  {
    id: "dat-dog-frenchmen",
    name: "Dat Dog (Frenchmen St)",
    category: "customers",
    lat: 29.96367,
    lng: -90.05768,
    address: "601 Frenchmen St",
    neighborhood: "Marigny",
    hours: week(
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(23))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
    ),
    free: false,
    verify: true,
    tip: "The restroom situation on Frenchmen is dire; Dat Dog is your out. A sausage, a balcony over the street, and facilities that beat every music club on the block.",
  },
  {
    id: "bywater-bakery",
    name: "Bywater Bakery",
    category: "customers",
    lat: 29.963,
    lng: -90.03912,
    address: "3624 Dauphine St",
    neighborhood: "Bywater",
    hours: daily(T(7), T(15)),
    free: false,
    verify: true,
    tip: "King cake all year round and a friendly restroom while your coffee is poured. Deep Bywater — mornings only, so plan accordingly.",
  },
  {
    id: "circle-food-market-7th-ward",
    name: "Circle Food Store",
    category: "customers",
    lat: 29.97205,
    lng: -90.06557,
    address: "1522 St Bernard Ave, New Orleans, LA 70116",
    neighborhood: "7th Ward",
    hours: week(
      [R(T(8), T(19))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A 1938 grocery landmark at Claiborne and St. Bernard, back open with a bakery and pharmacy counter. The restroom is on a coded lock, so buy something first and ask nicely. Wheelchair-accessible entrance and facilities.",
  },
  {
    id: "pagoda-cafe-dorgenois",
    name: "Pagoda Cafe",
    category: "customers",
    lat: 29.9759,
    lng: -90.07586,
    address: "1430 N Dorgenois St, New Orleans, LA 70119",
    neighborhood: "7th Ward",
    hours: daily(T(7), T(14)),
    free: false,
    wheelchair: true,
    tip: "Worker-owned cafe at Bayou Rd and Kerlerec St, known for breakfast tacos and courtyard seating. Wheelchair accessible, and a dependable daytime coffee-and-restroom stop in the 7th Ward.",
  },
  {
    id: "alvar-library",
    name: "Alvar Library",
    category: "public",
    lat: 29.96391,
    lng: -90.03676,
    address: "913 Alvar St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A small, wheelchair-accessible neighborhood branch a few blocks off St. Claude Ave, convenient for anyone working the Bywater bar and gallery strip. Free restroom during open hours, no card or purchase required.",
  },
  {
    id: "bacchanal-wine-bywater",
    name: "Bacchanal Wine",
    category: "customers",
    lat: 29.95978,
    lng: -90.03324,
    address: "600 Poland Ave, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(23))],
      [R(T(17), T(23))],
    ),
    free: false,
    wheelchair: true,
    tip: "Landmark wine shop and bar with a sprawling backyard patio and live music most nights. Buy a glass or bottle at the counter and the gender-neutral, wheelchair-accessible restrooms are yours — the sign over the sink just says to wash your hands.",
  },
  {
    id: "bjs-lounge-burgundy",
    name: "BJ's Lounge",
    category: "customers",
    lat: 29.96282,
    lng: -90.03309,
    address: "4301 Burgundy St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(13), T(28)),
    free: false,
    verify: true,
    tip: "A classic Bywater dive with a pool table, jukebox, and back patio, pouring drinks into the early morning most days. One of the few late-night options deep in residential Bywater — order something first.",
  },
  {
    id: "elizabeths-restaurant-gallier",
    name: "Elizabeth's Restaurant",
    category: "customers",
    lat: 29.96152,
    lng: -90.04092,
    address: "601 Gallier St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(8), T(14, 30)),
    free: false,
    verify: true,
    tip: "A 20-plus-year Bywater institution known for praline bacon and duck waffle, tucked well away from the riverfront tourist strip. The restaurant's own site lists 8am-2:30pm daily, though other listings mention longer evening hours — worth a quick call before a late visit.",
  },
  {
    id: "parleaux-beer-lab-bywater",
    name: "Parleaux Beer Lab",
    category: "customers",
    lat: 29.96075,
    lng: -90.034,
    address: "634 Lesseps St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(12), T(20))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A neighborhood brewery with an indoor bar and a large fenced backyard beer garden, wheelchair accessible. Good landing spot after a wander through Bywater and the St. Claude corridor.",
  },
  {
    id: "pizza-delicious-bywater",
    name: "Pizza Delicious",
    category: "customers",
    lat: 29.96238,
    lng: -90.04266,
    address: "617 Piety St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(11, 30), T(21))],
      null,
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(22))],
      [R(T(11, 30), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Full-service Bywater pizzeria a couple blocks off the Crescent Park levee trail, with both indoor and patio seating. Grab a slice at the counter if a whole pie feels like overkill for a bathroom break.",
  },
  {
    id: "satsuma-cafe-dauphine",
    name: "Satsuma Cafe (Dauphine St)",
    category: "customers",
    lat: 29.96376,
    lng: -90.04291,
    address: "3218 Dauphine St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(8), T(15)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Beloved Bywater counter-service spot for cold-pressed juice, salads, and avocado toast. Order at the counter and use the restroom — reviewers specifically call out the decor as memorable, which is a high bar for a bathroom.",
  },
  {
    id: "saturn-bar",
    name: "Saturn Bar",
    category: "customers",
    lat: 29.96794,
    lng: -90.04423,
    address: "3067 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(14), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(25))],
      [R(T(14), T(25))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A dive-bar institution on the St. Claude corridor with a wheelchair-accessible entrance. Reviewers are shocked, shocked, to report the bathroom is clean — stocked soap, stocked toilet paper — so buy a cheap drink and go.",
  },
  {
    id: "stuphd-beignets-burgers-st-claude",
    name: "Stuph'D Beignets & Burgers",
    category: "customers",
    lat: 29.96717,
    lng: -90.04081,
    address: "3325 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(10), T(15))],
      null,
      null,
      [R(T(10), T(17))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A locally loved, Black-owned counter-service spot slinging stuffed beignets and burgers in a stretch of St. Claude with few other food options. Grab something sweet or savory and the restroom is yours — wheelchair accessible, and reviewers rave that the bathrooms are huge.",
  },
  {
    id: "vaughans-lounge-bywater",
    name: "Vaughan's Lounge",
    category: "customers",
    lat: 29.96203,
    lng: -90.03414,
    address: "4229 Dauphine St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(12), T(26)),
    free: false,
    verify: true,
    tip: "A 60-plus-year-old Bywater dive bar and live-music room on the corner of Dauphine and Lesseps. Buzz the side door, order a drink, and the restroom is yours — open daily from noon into the wee hours.",
  },
  {
    id: "sanchez-multi-service-center",
    name: "Andrew P. Sanchez & Copelin-Byrd Multi-Service Center",
    category: "public",
    lat: 29.96641,
    lng: -90.01428,
    address: "1616 Fats Domino Ave, New Orleans, LA 70117",
    neighborhood: "Lower Ninth Ward",
    hours: week(
      null,
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(9), T(13))],
    ),
    free: true,
    verify: true,
    tip: "A $20.5 million, two-story city multi-service center with an indoor pool, health clinic, senior center, and NOPD sub-station, so it's staffed and busy all day. Free and public, right in the Lower Ninth Ward.",
  },
  {
    id: "mlk-jr-branch-library-lower-ninth",
    name: "Dr. Martin Luther King, Jr. Branch Library",
    category: "public",
    lat: 29.9664,
    lng: -90.01428,
    address: "1611 Fats Domino Ave, New Orleans, LA 70117",
    neighborhood: "Lower Ninth Ward",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    tip: "The only public library branch inside the Lower 9th Ward, on the street renamed for Fats Domino. Free, air-conditioned, no-questions-asked restroom access during open hours, plus somewhere to sit if you need a break from the heat.",
  },
  {
    id: "bamboulas-frenchmen",
    name: "Bamboula's",
    category: "customers",
    lat: 29.96291,
    lng: -90.05798,
    address: "514 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: daily(T(15), T(26)),
    free: false,
    verify: true,
    tip: "Live music every day starting at 3pm, so you get restroom access earlier in the day than most Frenchmen Street clubs that don't open until night. A working bar-side bathroom for patrons, plain and simple.",
  },
  {
    id: "blue-nile-frenchmen",
    name: "Blue Nile",
    category: "customers",
    lat: 29.96314,
    lng: -90.05786,
    address: "532 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(19), T(24, 30))],
      null,
      null,
      [R(T(20), T(24, 30))],
      [R(T(20, 30), T(27))],
      [R(T(19), T(25))],
      [R(T(19), T(27))],
    ),
    free: false,
    verify: true,
    tip: "Two-room live music venue on Frenchmen with brass, funk, and jazz most nights, plus a balcony room upstairs. Buy a drink at the bar and the restroom is yours — reliable well past midnight when shows run late.",
  },
  {
    id: "brieux-carre-brewing",
    name: "Brieux Carré Brewing Company",
    category: "customers",
    lat: 29.96289,
    lng: -90.05741,
    address: "2115 Decatur St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(23))],
      [R(T(12), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Just past the Quarter's edge on Decatur, with 12 rotating taps and a courtyard. The owner has said staff and customers use the same restrooms — kept incredibly clean on purpose.",
  },
  {
    id: "buffas-bar-esplanade",
    name: "Buffa's Bar & Restaurant",
    category: "customers",
    lat: 29.96541,
    lng: -90.06259,
    address: "1001 Esplanade Ave, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A genuine 24-hour bar and diner on the edge of the Marigny, kitchen included, with a midnight-to-noon breakfast menu for good measure. Order something at the bar and you've got one of the most dependable 3 a.m. restrooms in the neighborhood.",
  },
  {
    id: "cafe-negril-frenchmen",
    name: "Cafe Negril",
    category: "customers",
    lat: 29.96376,
    lng: -90.05795,
    address: "606 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(14), T(26))],
      [R(T(18, 30), T(26))],
      [R(T(19), T(26))],
      [R(T(18, 30), T(25))],
      [R(T(19), T(26))],
      [R(T(16), T(26))],
      [R(T(13, 30), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Reggae, funk, and brass band room open past 2am most nights, a solid late-night backup when Frenchmen Street's smaller clubs are slammed. One drink minimum, no cover, restrooms are single-stall by gender past the bar.",
  },
  {
    id: "city-market-elysian-fields",
    name: "City Market",
    category: "customers",
    lat: 29.96897,
    lng: -90.05647,
    address: "1101 Elysian Fields Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: week(
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(21))],
      [R(T(8), T(21))],
    ),
    free: false,
    verify: true,
    tip: "A newer indoor food hall at Elysian Fields and St. Claude, a short walk from St. Roch Market, with several counter-service vendors under one roof. Buy a snack from any of them and the shared restroom is yours to use.",
  },
  {
    id: "dba-frenchmen",
    name: "d.b.a.",
    category: "customers",
    lat: 29.96394,
    lng: -90.05804,
    address: "618 Frenchmen St, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: week(
      [R(T(18), T(25))],
      [R(T(18), T(25))],
      [R(T(18), T(25))],
      [R(T(18), T(25))],
      [R(T(18), T(25))],
      [R(T(18), T(25))],
      [R(T(14), T(25))],
    ),
    free: false,
    verify: true,
    tip: "A cornerstone Frenchmen St live-music bar with a deep whiskey and craft beer list, open nightly into the early morning. Restrooms are past the bar — buy a drink and slip in during a set.",
  },
  {
    id: "faubourg-wines",
    name: "Faubourg Wines",
    category: "customers",
    lat: 29.96879,
    lng: -90.04792,
    address: "2805 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: week(
      [R(T(12), T(19))],
      null,
      [R(T(12), T(20))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
      [R(T(12), T(21))],
    ),
    free: false,
    verify: true,
    tip: "A casual wine shop and bar on St. Claude Ave with an approachable by-the-glass list and Wednesday tastings. A glass of wine mid-afternoon is a low-key way to use the restroom on this corridor.",
  },
  {
    id: "hotel-peter-and-paul-lobby",
    name: "Hotel Peter & Paul Lobby (The Schoolhouse)",
    category: "lobby",
    lat: 29.96693,
    lng: -90.05494,
    address: "2317 Burgundy St, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: daily(T(7), T(22)),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A 71-room boutique hotel built inside a converted 19th-century schoolhouse, church, and convent just off Frenchmen Street. Guest reviews confirm a single public restroom sits right off the grand lobby staircase near the Elysian Bar and Cafe — expect company, since it draws bar and restaurant traffic too.",
  },
  {
    id: "kajuns-pub",
    name: "Kajun's Pub",
    category: "customers",
    lat: 29.96891,
    lng: -90.05511,
    address: "2256 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: week(
      [R(T(12), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(27))],
      [R(T(12), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A neighborhood karaoke bar open from midday or afternoon into the early morning, with nightly karaoke starting at 9pm. Reviewers specifically call out the clean bathrooms — a cheap drink gets you a stool and the restroom.",
  },
  {
    id: "marigny-brasserie",
    name: "Marigny Brasserie",
    category: "customers",
    lat: 29.9644,
    lng: -90.05794,
    address: "640 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      null,
      [R(T(17), T(23))],
      [R(T(17), T(23))],
      [R(T(17), T(23))],
      [R(T(17), T(23))],
      [R(T(17), T(24))],
      [R(T(12), T(24))],
    ),
    free: false,
    verify: true,
    tip: "A sit-down Creole spot at Frenchmen and Royal with cocktails and live big band music, for when you want a real restroom instead of a club bathroom line. Available to anyone eating or having a drink at the bar.",
  },
  {
    id: "robert-fresh-market-marigny",
    name: "Robért Fresh Market (Marigny)",
    category: "customers",
    lat: 29.96836,
    lng: -90.05609,
    address: "2222 St. Claude Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "A full-service local grocery on St. Claude Ave, well away from the Frenchmen St crush. Grab a coffee or snack and use the clean, well-lit store restroom.",
  },
  {
    id: "snug-harbor-jazz-bistro",
    name: "Snug Harbor Jazz Bistro",
    category: "customers",
    lat: 29.96413,
    lng: -90.05792,
    address: "626 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(23))],
      [R(T(17), T(23))],
    ),
    free: false,
    wheelchair: true,
    tip: "Longtime Frenchmen Street jazz supper club with a full dining room and nightly sets at 7:30 and 9:30. Restrooms are small two-stall rooms but the venue's own FAQ confirms ADA-accessible doorways — a solid early-evening option before the street fills up.",
  },
  {
    id: "allways-lounge-cabaret",
    name: "The AllWays Lounge & Cabaret",
    category: "customers",
    lat: 29.9689,
    lng: -90.05532,
    address: "2240 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: week(
      [R(T(16), T(26))],
      [R(T(18), T(26))],
      [R(T(18), T(26))],
      [R(T(18), T(26))],
      [R(T(18), T(26))],
      [R(T(18), T(26))],
      [R(T(16), T(26))],
    ),
    free: false,
    verify: true,
    tip: "A cabaret hotspot for burlesque, drag, and live music on the St. Claude corridor. A drink at the bar buys you restroom access seven nights a week, in a stretch that's otherwise light on late-night options.",
  },
  {
    id: "the-maison-frenchmen",
    name: "The Maison",
    category: "customers",
    lat: 29.96279,
    lng: -90.05797,
    address: "508 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(10), T(25))],
      [R(T(16), T(25))],
      [R(T(16), T(25))],
      [R(T(16), T(25))],
      [R(T(16), T(25))],
      [R(T(13), T(28))],
      [R(T(13), T(28))],
    ),
    free: false,
    verify: true,
    tip: "Three-floor Frenchmen Street venue with dinner, dancing, and live jazz — and restrooms on both the mezzanine and the penthouse level, so you're rarely stuck in one line. Most shows have no cover, just a one drink or food item minimum, making it an easy walk-in backup when the smaller clubs are packed.",
  },
  {
    id: "spotted-cat-frenchmen",
    name: "The Spotted Cat Music Club",
    category: "customers",
    lat: 29.96408,
    lng: -90.05763,
    address: "623 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(12), T(24, 30))],
      [R(T(14), T(25, 30))],
      [R(T(14), T(25, 30))],
      [R(T(14), T(25, 30))],
      [R(T(14), T(26))],
      [R(T(14), T(26))],
      [R(T(12), T(26))],
    ),
    free: false,
    verify: true,
    tip: "No-cover jazz club open from early afternoon into the small hours, so it doubles as one of the most dependable daytime-through-late-night stops on the block. One-drink minimum gets you in and gets you the bathroom, which regulars will tell you has a piano in it.",
  },
  {
    id: "three-muses-frenchmen",
    name: "Three Muses",
    category: "customers",
    lat: 29.96329,
    lng: -90.05784,
    address: "536 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(16, 30), T(24))],
      [R(T(19), T(23))],
      [R(T(19), T(23))],
      [R(T(19), T(23))],
      [R(T(19), T(23))],
      [R(T(19), T(23))],
      [R(T(18), T(24))],
    ),
    free: false,
    verify: true,
    tip: "Cozy tapas-and-cocktail spot with nightly live music and a first-come-first-served bar. No cover to sit down for a drink, and that drink buys you the restroom — a mellower alternative to the bigger Frenchmen clubs.",
  },
  {
    id: "emporium-arcade-bar-st-claude",
    name: "Emporium Arcade Bar (New Orleans)",
    category: "customers",
    lat: 29.96853,
    lng: -90.05588,
    address: "2231 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "St. Claude",
    hours: week(
      [R(T(15), T(25))],
      [R(T(17), T(25))],
      [R(T(17), T(25))],
      [R(T(17), T(25))],
      [R(T(17), T(25))],
      [R(T(17), T(26))],
      [R(T(15), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Free entry, pool tables, pinball, skeeball, and a full cocktail menu in a big renovated garage space on St. Claude. Reviewers single out the bathrooms as unusually clean for an arcade bar, so grab a token or a drink and settle in.",
  },
  {
    id: "melbas",
    name: "Melba's",
    category: "customers",
    lat: 29.97281,
    lng: -90.05687,
    address: "1525 Elysian Fields Ave, New Orleans, LA 70117",
    neighborhood: "St. Roch",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "The beloved 24-hour po-boy shop at Elysian Fields and N. Claiborne. Full-service counter restaurant, so a fried chicken po-boy at 3 a.m. comes with a real restroom, no questions asked.",
  },
  {
    id: "st-noir-cafe",
    name: "St. Noir Cafe",
    category: "customers",
    lat: 29.96931,
    lng: -90.05198,
    address: "1128 St Roch Ave, New Orleans, LA 70117",
    neighborhood: "St. Roch",
    hours: week(
      [R(T(7), T(16))],
      [R(T(7), T(20))],
      [R(T(7), T(20))],
      [R(T(7), T(20))],
      [R(T(7), T(20))],
      [R(T(7), T(20))],
      [R(T(7), T(20))],
    ),
    free: false,
    verify: true,
    tip: "A Black-owned coffee shop and self-described 'cafe sanctuary' right next to St. Roch Market, pouring coffee, tea, and wine from 7 a.m. daily. A reviewer specifically praised the bathroom's attention to detail — rare enough to mention.",
  },
  {
    id: "st-roch-tavern",
    name: "St. Roch Tavern",
    category: "customers",
    lat: 29.96994,
    lng: -90.05243,
    address: "1200 St Roch Ave, New Orleans, LA 70117",
    neighborhood: "St. Roch",
    hours: daily(T(12), T(26, 30)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A no-frills dive just off St. Claude with cheap drinks, pool, and pinball, open noon to 2:30 a.m. every day. It's cash-only, but there's an ATM on site, so budget accordingly before you order the drink that buys you the restroom.",
  },
  {
    id: "reach-center-7th-ward",
    name: "REACH Center (NOPL)",
    category: "public",
    lat: 29.97673,
    lng: -90.06849,
    address: "2022 St Bernard Ave, New Orleans, LA 70116",
    neighborhood: "7th Ward",
    hours: week(
      null,
      [R(T(10), T(17))],
      [R(T(10), T(14))],
      [R(T(10), T(14))],
      [R(T(10), T(14))],
      [R(T(10), T(16))],
      null,
    ),
    free: true,
    verify: true,
    tip: "The public library's free coworking space and gallery on St. Bernard Ave — the library's own page says no card needed, open to everyone. Weekdays only, shorter midweek hours.",
  },
  {
    id: "waffle-house-1911",
    name: "Waffle House #1911",
    category: "customers",
    lat: 30.00418,
    lng: -90.03566,
    address: "4601 Old Gentilly Rd, New Orleans, LA 70126",
    neighborhood: "Florida Area",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Scattered, smothered, and open around the clock out on Old Gentilly Road. Not a walking district — but if you're driving the Chef Menteur corridor at 4 a.m., it's there for you.",
  },
  {
    id: "mercedes-place-holy-cross",
    name: "Mercedes Place",
    category: "customers",
    lat: 29.95994,
    lng: -90.02116,
    address: "5200 Burgundy St, New Orleans, LA 70117",
    neighborhood: "Holy Cross",
    hours: daily(T(11), T(22, 30)),
    free: false,
    verify: true,
    tip: "Holy Cross's neighborhood bar since 1990 — cheap drinks, old-school jukebox, zero pretense. Buy a beer and the restroom's yours; it's the only reliable option this deep into the neighborhood.",
  },
  {
    id: "all-souls-community-center",
    name: "All Souls Community Center",
    category: "public",
    lat: 29.96109,
    lng: -90.0166,
    address: "5500 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Lower Ninth Ward",
    hours: week(
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      null,
    ),
    free: true,
    verify: true,
    tip: "An Episcopal community center in a former Walgreens, running a food pantry, tutoring, and a computer lab for the neighborhood. Weekdays 10 to 6 — it's a working community resource, so be a guest, not a tourist. Call (504) 218-8995 if unsure.",
  },
  {
    id: "burnells-lower-9th-market",
    name: "Burnell's Lower 9th Ward Market",
    category: "customers",
    lat: 29.97138,
    lng: -90.01285,
    address: "2036 Caffin Ave, New Orleans, LA 70117",
    neighborhood: "Lower Ninth Ward",
    hours: week(
      null,
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(8), T(20))],
      [R(T(9), T(18))],
    ),
    free: false,
    verify: true,
    tip: "Burnell Cotlon's corner institution — the first grocery to return to the Lower 9th after Katrina, with a barbershop and laundromat under the same roof. Buy a cold drink, say thank you, and ask; the laundromat means real facilities on site. Closed Sundays.",
  },
  {
    id: "nola-art-bar-st-claude",
    name: "NOLA Art Bar",
    category: "customers",
    lat: 29.96872,
    lng: -90.05776,
    address: "2128 St Claude Ave, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      null,
      null,
      [R(T(17), T(23))],
      null,
      [R(T(17), T(23))],
      [R(T(17), T(23))],
      [R(T(17), T(23))],
    ),
    free: false,
    verify: true,
    tip: "St. Claude art bar freshly rebranded as a reading lounge — drinks, books, and a restroom from 5 p.m. Closed Wednesdays, Sundays, and Mondays, per its June 2026 relaunch.",
  },
  {
    id: "stallings-st-claude-rec",
    name: "Stallings St. Claude Rec Center (NORD)",
    category: "public",
    lat: 29.96485,
    lng: -90.03246,
    address: "4300 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      null,
    ),
    free: true,
    verify: true,
    tip: "The city rec center on St. Claude — indoor courts, fitness room, weekday evenings 4 to 9. Free, public, and air-conditioned, which in a Bywater July counts double.",
  },
  {
    id: "bullets-sports-bar",
    name: "Bullet's Sports Bar",
    category: "customers",
    lat: 29.98158,
    lng: -90.06758,
    address: "2441 A. P. Tureaud Ave, New Orleans, LA 70119",
    neighborhood: "7th Ward",
    hours: week(
      null,
      [R(T(10), T(23))],
      [R(T(11), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
    ),
    free: false,
    verify: true,
    tip: "A no-frills neighborhood dive run by owner \"Bullet\" Garcia since the '90s, known for its jukebox, pool table, and Tuesday-night sets from Kermit Ruffins. No kitchen of its own, but a setup drink at the bar gets you to the restroom.",
  },
  {
    id: "poor-boys-bar",
    name: "Poor Boys Bar",
    category: "customers",
    lat: 29.96975,
    lng: -90.06418,
    address: "1328 St Bernard Ave, New Orleans, LA 70116",
    neighborhood: "7th Ward",
    hours: daily(T(17), T(23, 59)),
    free: false,
    verify: true,
    tip: "Karaoke, DJ nights, and food pop-ups keep this neighborhood dive going until 4 a.m. most nights and 6 a.m. on weekends — a solid backup when everything else on the corridor has rolled up its sidewalks. Buy a drink, use the room.",
  },
  {
    id: "seals-class-act",
    name: "Seal's Class Act",
    category: "customers",
    lat: 29.97873,
    lng: -90.06865,
    address: "2169 Aubry St, New Orleans, LA 70119",
    neighborhood: "7th Ward",
    hours: week(
      [R(T(18), T(27))],
      [R(T(18), T(27))],
      null,
      [R(T(18), T(27))],
      [R(T(18), T(27))],
      [R(T(18), T(29))],
      [R(T(18), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A 7th Ward dive run as a social and pleasure club outreach spot, with live acts, dancing, and food. Full bar with seating means a real restroom for paying customers — closed Tuesdays, and Friday nights run late. Call ahead to confirm, since hours aren't officially posted.",
  },
  {
    id: "bud-rips-9th-ward",
    name: "Bud Rip's Old 9th Ward Bar",
    category: "customers",
    lat: 29.96498,
    lng: -90.04237,
    address: "900 Piety St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(13), T(23, 59))],
    ),
    free: false,
    verify: true,
    tip: "Slinging frozen cocktails, pool, and video poker on the same corner since 1960 — a genuine Bywater institution, not a themed reproduction of one. Open till 3 a.m. every night (from 1 p.m. Saturdays); buy a drink, use the restroom.",
  },
  {
    id: "jj-sports-lounge",
    name: "J&J's Sports Lounge",
    category: "customers",
    lat: 29.96216,
    lng: -90.03458,
    address: "800 France St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(9), T(23, 59)),
    free: false,
    verify: true,
    tip: "A wall of TVs, a projector for the NFL/MLB package, and a back room with pool and video poker — this is a Bywater local's bar, not a tourist stop. Open 9 a.m. to 4 a.m. daily; order a drink and use the room.",
  },
  {
    id: "petite-clouet-cafe",
    name: "Petite Clouet Café",
    category: "customers",
    lat: 29.96329,
    lng: -90.04542,
    address: "3100 Royal St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: daily(T(7), T(17)),
    free: false,
    tip: "Corner coffee shop at Royal and Clouet in Bywater — espresso, pastries, light lunch, indoor and outdoor seating. Open every day, no exceptions.",
  },
  {
    id: "the-country-club-bywater",
    name: "The Country Club",
    category: "customers",
    lat: 29.96294,
    lng: -90.04403,
    address: "634 Louisa St, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(9, 30), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(9, 30), T(23))],
    ),
    free: false,
    verify: true,
    tip: "A heated saltwater pool club and restaurant/bar in a Creole mansion — $20 day pass gets you pool, hot tub, sauna, and clean unisex bathrooms with separate showers and lockers. Walk-in only for the pool, no reservations, 21+.",
  },
  {
    id: "the-domino-bywater",
    name: "The Domino",
    category: "customers",
    lat: 29.9676,
    lng: -90.04498,
    address: "3044 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "Bywater",
    hours: week(
      [R(T(15), T(23, 59))],
      [R(T(20), T(23, 59))],
      [R(T(20), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
      [R(T(15), T(23, 59))],
    ),
    free: false,
    verify: true,
    tip: "A cozy, dive-y wine and cocktail bar with a vintage board-game shelf and rotating live music or DJ nights. Order a glass of something and use the restroom — casual, no pretense, no cover required just to exist there.",
  },
  {
    id: "adolfos-frenchmen",
    name: "Adolfo's",
    category: "customers",
    lat: 29.96375,
    lng: -90.05766,
    address: "611 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: daily(T(17, 30), T(21, 30)),
    free: false,
    tip: "Upstairs Italian-Creole seafood above the Apple Barrel Bar, first-come-first-served with live music nightly. A real 40-seat dining room means a real restroom — a solid follow-up once you're seated for dinner.",
  },
  {
    id: "ayu-bakehouse",
    name: "Ayu Bakehouse",
    category: "customers",
    lat: 29.96559,
    lng: -90.05784,
    address: "801 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(8), T(15, 30))],
      [R(T(8), T(14))],
      [R(T(8), T(14))],
      [R(T(8), T(15, 30))],
      [R(T(8), T(15, 30))],
      [R(T(8), T(15, 30))],
      [R(T(8), T(15, 30))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Daytime bakery-cafe down past the Frenchmen music-club cluster — handmade croissants, sourdough, and coffee, with indoor seating and restrooms toward the back. A rare morning option on a strip where most bars don't open until dark.",
  },
  {
    id: "baldwin-and-co",
    name: "Baldwin & Co.",
    category: "customers",
    lat: 29.96825,
    lng: -90.05711,
    address: "1030 Elysian Fields Ave, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: daily(T(7), T(18)),
    free: false,
    tip: "Black-owned bookstore-café with an espresso bar and reading nooks scattered through the stacks. Reviewers single out the restrooms as clean and gender-neutral — rare praise, take it.",
  },
  {
    id: "favela-chic",
    name: "Favela Chic",
    category: "customers",
    lat: 29.96335,
    lng: -90.05764,
    address: "525 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "Brazilian-Latin bar, restaurant, and live-music venue steps from the Apple Barrel — three rooms, three bars, and a pizza-and-Latin-food menu, so a seated order gets you inside past the crowd. Hours shift by source, so call ahead if you're cutting it close.",
  },
  {
    id: "mardi-gras-zone",
    name: "Mardi Gras Zone",
    category: "public",
    lat: 29.96448,
    lng: -90.05031,
    address: "2706 Royal St, New Orleans, LA 70117",
    neighborhood: "Marigny",
    hours: daily(T(7), T(25)),
    free: true,
    verify: true,
    tip: "An only-in-New-Orleans hybrid: a real neighborhood supermarket bolted to a Mardi Gras costume shop and a deli slinging wood-fired pizza into the small hours. Sits right on Royal at the Marigny/Bywater line — open daily 7 a.m. to 1 a.m., not the 24-hour rumor some old listings claim.",
  },
  {
    id: "spicy-mango",
    name: "Spicy Mango",
    category: "customers",
    lat: 29.96194,
    lng: -90.05752,
    address: "405 Frenchmen St, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      null,
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(24))],
      [R(T(17), T(24))],
    ),
    free: false,
    verify: true,
    tip: "Larry Morrow's Creole-Caribbean spot at Frenchmen and Esplanade, with a mango tree growing right in the dining room and live music most nights. Closed Tuesdays, and it's a sit-down restaurant, so order something before you ask.",
  },
  {
    id: "sweet-lorraines-jazz-club",
    name: "Sweet Lorraine's Jazz Club",
    category: "customers",
    lat: 29.96849,
    lng: -90.05961,
    address: "1931 St Claude Ave, New Orleans, LA 70116",
    neighborhood: "Marigny",
    hours: week(
      [R(T(17), T(23))],
      null,
      [R(T(17), T(23))],
      null,
      [R(T(17), T(23))],
      [R(T(17), T(23, 59))],
      [R(T(17), T(23, 59))],
    ),
    free: false,
    verify: true,
    tip: "A 50-plus-year jazz institution USA Today once named a top-ten club in the country. Cover usually gets tacked onto the bill rather than collected at the door, and there's a full dinner menu, so a restroom break mid-set is standard operating procedure. Closed Monday and Wednesday.",
  },
  {
    id: "nobl-boulder-lounge",
    name: "New Orleans Boulder Lounge (NOBL)",
    category: "customers",
    lat: 29.96904,
    lng: -90.05295,
    address: "2360 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "St. Claude",
    hours: week(
      [R(T(12), T(19))],
      [R(T(16), T(21))],
      [R(T(7), T(21))],
      [R(T(12), T(21))],
      [R(T(7), T(21))],
      [R(T(12), T(20))],
      [R(T(9), T(19))],
    ),
    free: false,
    verify: true,
    tip: "Bouldering gym on St. Claude with a straightforward walk-in day pass ($20 adult, $15 youth) — just sign a waiver at the front desk, no membership needed, full facility access included.",
  },
  {
    id: "no-dice-st-claude",
    name: "No Dice",
    category: "customers",
    lat: 29.96857,
    lng: -90.0553,
    address: "2239 St. Claude Ave, New Orleans, LA 70117",
    neighborhood: "St. Claude",
    hours: daily(T(18), T(23, 59)),
    free: false,
    verify: true,
    tip: "The old Hi-Ho Lounge got sold and relaunched as No Dice at the same St. Claude address — same dive-bar-with-a-stage energy, same bathroom. Doors open at 6 p.m. every night; order a drink and go.",
  },
  {
    id: "siberia-st-claude",
    name: "Siberia",
    category: "customers",
    lat: 29.96854,
    lng: -90.05576,
    address: "2227 St Claude Ave, New Orleans, LA 70117",
    neighborhood: "St. Claude",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "Russian/Ukrainian-inspired dive with a packed live-music calendar and a bar that opens somewhere in the afternoon-to-early-evening range depending who you ask — the venue's own website can't agree with itself. Cover for a show or a drink at the bar both count; check siberianola.com/calendar before you commit a full bladder to the trip.",
  },
];
