import type { Spot } from "../types";
import { T, R, daily, week } from "./helpers";

/** New Orleans East. */
export const EAST_SPOTS: readonly Spot[] = [
  {
    id: "dong-phuong-bakery-restaurant",
    name: "Dong Phuong Bakery & Restaurant",
    category: "customers",
    lat: 30.03621,
    lng: -89.91508,
    address: "14207 Chef Menteur Hwy, New Orleans, LA 70129",
    neighborhood: "New Orleans East",
    hours: week(
      [R(T(9), T(15))],
      [R(T(9), T(15))],
      null,
      [R(T(9), T(15))],
      [R(T(9), T(15))],
      [R(T(9), T(15))],
      [R(T(9), T(15))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "The James Beard Award-winning Vietnamese-Creole bakery famous citywide for king cakes and banh mi, with a full sit-down dining room attached. Wheelchair accessible, closed Tuesdays; restroom access isn't posted online but a working dining room makes it a safe bet for customers.",
  },
  {
    id: "east-new-orleans-regional-library",
    name: "East New Orleans Regional Library",
    category: "public",
    lat: 30.03234,
    lng: -89.97179,
    address: "5641 Read Blvd, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    verify: true,
    tip: "A 30,000-square-foot regional branch with plenty of parking off Read Boulevard — one of the very few confirmed free public restrooms in New Orleans East.",
  },
  {
    id: "joe-w-brown-park-rec-center",
    name: "Joe W. Brown Park & Recreation Center",
    category: "public",
    lat: 30.03075,
    lng: -89.97172,
    address: "5601 Read Blvd, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: week(
      null,
      [R(T(10), T(20))],
      [R(T(10), T(20))],
      [R(T(10), T(20))],
      [R(T(10), T(20))],
      [R(T(10), T(20))],
      [R(T(10), T(20))],
    ),
    free: true,
    verify: true,
    tip: "One of NORD's flagship complexes, with an indoor pool, tennis center, and stadium inside a big New Orleans East park. Reviewers specifically flag the restrooms as clean, with one comparing the setup favorably to a high school facility. Call (504) 658-3080 to confirm before you go — the rec center is closed Sundays.",
  },
  {
    id: "minh-canh-market",
    name: "Minh Canh Market",
    category: "customers",
    lat: 30.03761,
    lng: -89.91154,
    address: "4661 Alcee Fortier Blvd, New Orleans, LA 70129",
    neighborhood: "New Orleans East",
    hours: daily(T(8), T(18, 30)),
    free: false,
    verify: true,
    tip: "A clean, well-stocked Vietnamese grocery on the Alcee Fortier corridor, the commercial heart of Village de l'Est, with banh mi, produce, and specialty meats and seafood. Two food counters share the building, so a restroom stop is a safe bet with a small purchase.",
  },
  {
    id: "pho-bang-restaurant-nola-east",
    name: "Pho Bang Restaurant",
    category: "customers",
    lat: 30.03646,
    lng: -89.91265,
    address: "14367 Chef Menteur Hwy, New Orleans, LA 70129",
    neighborhood: "New Orleans East",
    hours: week(
      [R(T(8), T(18))],
      [R(T(8), T(18))],
      [R(T(8), T(18))],
      null,
      [R(T(8), T(18))],
      [R(T(8), T(18))],
      [R(T(8), T(18))],
    ),
    free: false,
    tip: "A sit-down pho spot on the Chef Menteur Vietnamese restaurant corridor near Dong Phuong, with a bathroom a reviewer specifically noted was clean. Dine-in customers get restroom access; closed Wednesdays.",
  },
  {
    id: "rouses-chef-menteur",
    name: "Rouses Market #93 (New Orleans East / Chef Menteur Hwy)",
    category: "customers",
    lat: 30.01876,
    lng: -89.97231,
    address: "9701 Chef Menteur Highway, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: daily(T(7), T(20)),
    free: false,
    verify: true,
    tip: "A newer full-line supermarket in the old Winn-Dixie building on Chef Menteur Highway, with bakery, seafood, and café departments — and an NOPD substation next door for good measure. Fills a real amenity gap in a part of the city with few other mapped options.",
  },
  {
    id: "home-depot-i10-bullard",
    name: "The Home Depot (I-10 Bullard)",
    category: "public",
    lat: 30.04978,
    lng: -89.95633,
    address: "12300 I-10 Service Rd, New Orleans, LA 70128",
    neighborhood: "New Orleans East",
    hours: week(
      [R(T(8), T(20))],
      [R(T(6), T(21))],
      [R(T(6), T(21))],
      [R(T(6), T(21))],
      [R(T(6), T(21))],
      [R(T(6), T(21))],
      [R(T(6), T(21))],
    ),
    free: true,
    verify: true,
    tip: "A big-box hardware store right at the Bullard Ave exit off I-10, restrooms near the front registers and garden center. Long hours and easy highway access make it a practical stop for the New Orleans East corridor, though don't be shocked if the paper towels are missing.",
  },
  {
    id: "viet-my-supermarket-village-de-lest",
    name: "Viet My Supermarket",
    category: "customers",
    lat: 30.03731,
    lng: -89.91248,
    address: "4656 Alcee Fortier Blvd, New Orleans, LA 70129",
    neighborhood: "New Orleans East",
    hours: week(
      [R(T(7), T(18))],
      [R(T(8, 30), T(20))],
      [R(T(8, 30), T(20))],
      [R(T(8, 30), T(20))],
      [R(T(8, 30), T(20))],
      [R(T(8, 30), T(18, 30))],
      [R(T(7, 30), T(20))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A well-organized Vietnamese supermarket in the Samson Plaza Shopping Center on the Alcee Fortier corridor, known for fresh produce, seafood, and specialty groceries. Wheelchair-accessible entrance and long daily hours make it a solid restroom stop while browsing the Village de l'Est grocery strip.",
  },
  {
    id: "waffle-house-read-blvd",
    name: "Waffle House #1837",
    category: "customers",
    lat: 30.03545,
    lng: -89.97338,
    address: "5801 Read Blvd, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A 24-hour diner covering New Orleans East, where reliable late-night restroom options are thin on the ground. Standard Waffle House counter-and-booth setup.",
  },
  {
    id: "walmart-supercenter-bullard-ave",
    name: "Walmart Supercenter (Bullard Ave)",
    category: "public",
    lat: 30.04333,
    lng: -89.96187,
    address: "6000 Bullard Ave, New Orleans, LA 70128",
    neighborhood: "New Orleans East",
    hours: daily(T(6), T(22)),
    free: true,
    verify: true,
    tip: "A Supercenter at the Bullard Ave commercial node near I-10, one of the newer retail hubs in New Orleans East. Standard big-box restrooms near customer service, open long daily hours — no purchase required.",
  },
  {
    id: "walmart-chef-menteur",
    name: "Walmart Supercenter (Chef Menteur Hwy)",
    category: "public",
    lat: 30.00592,
    lng: -90.03842,
    address: "4301 Chef Menteur Hwy, New Orleans, LA 70126",
    neighborhood: "New Orleans East",
    hours: daily(T(6), T(22)),
    free: true,
    verify: true,
    tip: "Free public restrooms near the front entrance, open 6am to 10pm daily. Not glamorous, but it's one of the few reliable stops on the far east side of the parish.",
  },
  {
    id: "new-orleans-east-hospital-lobby",
    name: "New Orleans East Hospital (Lobby)",
    category: "public",
    lat: 30.02915,
    lng: -89.97491,
    address: "5620 Read Blvd, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: daily(T(8), T(17)),
    free: true,
    verify: true,
    tip: "The first-floor restroom sits across from the ATM outside Café East — the hospital's own visitor FAQ says so. Lobby hours are 8 to 5 daily; after that, the second-floor ER entrance is the door that never closes.",
  },
  {
    id: "burger-king-chef-menteur",
    name: "Burger King (Chef Menteur)",
    category: "customers",
    lat: 30.00443,
    lng: -90.03761,
    address: "4454 Chef Menteur Hwy, New Orleans, LA 70126",
    neighborhood: "New Orleans East",
    hours: daily(T(6), T(23)),
    free: false,
    verify: true,
    tip: "Chef Menteur corridor backup a few blocks from the Cane's — useful after 5 p.m. when that dining room locks. Standard hours; verify late-night before counting on it.",
  },
  {
    id: "pjs-coffee-read-blvd",
    name: "PJ's Coffee (Read Blvd)",
    category: "customers",
    lat: 30.03331,
    lng: -89.97365,
    address: "5733 Read Blvd, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: daily(T(7), T(15)),
    free: false,
    verify: true,
    tip: "One of the only sit-down coffee shops in New Orleans East. Mornings through mid-afternoon; a small latte is the price of relief on Read Blvd.",
  },
  {
    id: "raising-canes-chef-menteur",
    name: "Raising Cane's (Chef Menteur)",
    category: "customers",
    lat: 30.00556,
    lng: -90.03616,
    address: "4740 Chef Menteur Hwy, New Orleans, LA 70126",
    neighborhood: "New Orleans East",
    hours: daily(T(10), T(17)),
    free: false,
    verify: true,
    tip: "Heads up: the dining room here closes at 5 p.m. even though the drive-thru runs to 10 — Cane's own locator says so. Before five, chicken fingers and a restroom; after five, just chicken fingers.",
  },
  {
    id: "wendys-bullard",
    name: "Wendy's (Bullard Ave)",
    category: "customers",
    lat: 30.04422,
    lng: -89.95924,
    address: "6020 Bullard Ave, New Orleans, LA 70128",
    neighborhood: "New Orleans East",
    hours: daily(T(6), T(26)),
    free: false,
    verify: true,
    tip: "Dine-in confirmed and open 6 a.m. to 2 a.m. — the latest-running indoor option on the Bullard corridor.",
  },
  {
    id: "ba-mien-restaurant",
    name: "Ba Mien Restaurant",
    category: "customers",
    lat: 30.03211,
    lng: -89.92905,
    address: "13235 Chef Menteur Hwy Suite C, New Orleans, LA 70129",
    neighborhood: "New Orleans East",
    hours: week(
      [R(T(8), T(16))],
      null,
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
      [R(T(8), T(16))],
    ),
    free: false,
    verify: true,
    tip: "Dine-in Vietnamese spot covering all three regions of the country's cuisine since 2001, with community-style tables for big groups and tableside beef fondue service. A genuine sit-down restaurant, not a counter operation, so restroom access comes with the assertive pho. Closed Mondays.",
  },
  {
    id: "red-apple-lake-forest",
    name: "Red Apple",
    category: "customers",
    lat: 29.97443,
    lng: -90.0483,
    address: "9954 Lake Forest Blvd, Suite 6, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: week(
      null,
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
    ),
    free: false,
    verify: true,
    tip: "Family-run Chinese dine-in and takeout in a Lake Forest Blvd strip center — easy to miss without GPS, but the combo plates keep it busy. A couple of small tables inside mean a paying customer isn't stuck waiting by the door for the restroom. Closed Sundays.",
  },
  {
    id: "saint-manchu-nola",
    name: "Saint Manchu NOLA",
    category: "customers",
    lat: 30.01806,
    lng: -89.9675,
    address: "10038 Chef Menteur Hwy, New Orleans, LA 70127",
    neighborhood: "New Orleans East",
    hours: daily(T(10), T(19)),
    free: false,
    verify: true,
    tip: "Chinese-Creole counter on the Chef Menteur corridor near Bullard, known for wing dinners and seafood fried rice. Mostly a takeout crowd, but the room is walk-in with a couple of tables, not a walk-up window — order something and duck in.",
  },
];
