import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

export const FRENCH_QUARTER_SPOTS: readonly Spot[] = [
  {
    id: "washington-artillery-park",
    name: "Washington Artillery Park Restrooms",
    category: "public",
    lat: 29.95681,
    lng: -90.06243,
    address: "Decatur St at St. Ann St, across from Jackson Square",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(18)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Up the steps between Jackson Square and the river, next to Café du Monde — which famously has no restroom of its own. If these are locked, the Dutch Alley restrooms are three blocks downriver.",
  },
  {
    id: "french-market-dutch-alley",
    name: "French Market Restrooms (Dutch Alley)",
    category: "public",
    lat: 29.95871,
    lng: -90.0607,
    address: "Dutch Alley, French Market, near Dumaine St",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(18)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "The official public restrooms of the French Market, tucked into Dutch Alley by the Jazz Museum end. Free, wheelchair accessible, and checked on OpenStreetMap as recently as 2025. The safest bet in the lower Quarter.",
  },
  {
    id: "french-market-flea",
    name: "French Market Restrooms (Flea Market end)",
    category: "public",
    lat: 29.96069,
    lng: -90.05819,
    address: "1235 N Peters St, flea market end",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(17)),
    free: true,
    verify: true,
    tip: "At the flea-market end of the French Market. If you can't spot them, ask any vendor — you will not be the first, or the thousandth.",
  },
  {
    id: "moonwalk-riverfront",
    name: "Moonwalk Riverfront Restrooms",
    category: "public",
    lat: 29.95424,
    lng: -90.06305,
    address: "Moonwalk promenade, near the foot of Toulouse St",
    neighborhood: "French Quarter",
    hours: daily(T(8), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "On the river promenade below the levee. Catch a breeze off the Mississippi while you wait your turn — the view beats every bar bathroom line in the Quarter.",
  },
  {
    id: "jax-brewery",
    name: "The Shops at JAX Brewery",
    category: "public",
    lat: 29.95595,
    lng: -90.06296,
    address: "600 Decatur St",
    neighborhood: "French Quarter",
    hours: daily(T(10), T(19)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "The old Jax beer brewery is now a mall that mostly sells hot sauce and t-shirts — and quietly provides air-conditioned restrooms nobody guards. Head upstairs.",
  },
  {
    id: "royal-sonesta",
    name: "Royal Sonesta Lobby",
    category: "lobby",
    lat: 29.95592,
    lng: -90.0686,
    address: "300 Bourbon St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    osmToilet: true,
    tip: "The mid-Bourbon miracle. A restroom just off the lobby has quietly rescued thousands. Shoulders back, phone out, walk past the concierge like your room key is in your other pocket.",
  },
  {
    id: "hotel-monteleone",
    name: "Hotel Monteleone Lobby",
    category: "lobby",
    lat: 29.95419,
    lng: -90.06794,
    address: "214 Royal St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    tip: "Literary landmark with a rotating Carousel Bar and a lobby restroom that asks no questions. Worth a slow lap past the bar on your way out — it really does spin.",
  },
  {
    id: "historic-no-collection",
    name: "The Historic New Orleans Collection",
    category: "public",
    lat: 29.95669,
    lng: -90.06571,
    address: "520 Royal St",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(10, 30), T(16, 30))],
      null,
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A free museum on Royal with courtyards, air conditioning, and immaculate restrooms. The Quarter's best-kept secret when you need ten civilized minutes. Closed Mondays.",
  },
  {
    id: "cafe-beignet-royal",
    name: "Café Beignet (Royal St)",
    category: "customers",
    lat: 29.95535,
    lng: -90.06685,
    address: "334 Royal St",
    neighborhood: "French Quarter",
    hours: daily(T(8), T(22)),
    free: false,
    verify: true,
    tip: "Beignets are the price of admission, which is hardly a punishment. Shares a courtyard with the NOPD 8th District station — this is the single worst spot in the city to improvise, so use the actual toilet.",
  },
  {
    id: "deja-vu",
    name: "Déjà Vu Bar & Grill",
    category: "customers",
    lat: 29.95692,
    lng: -90.06852,
    address: "400 Dauphine St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A bar and grill that basically never closes, one block off Bourbon. Order a cheeseburger at 4 a.m., use the restroom, question nothing.",
  },
  {
    id: "clover-grill",
    name: "Clover Grill",
    category: "customers",
    lat: 29.96028,
    lng: -90.06403,
    address: "900 Bourbon St",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Legendary greasy spoon on lower Bourbon — burgers cooked under a hubcap since forever. Historically 24/7; hours have wobbled in recent years, but late night is usually safe.",
  },
  {
    id: "mollys-at-the-market",
    name: "Molly's at the Market",
    category: "customers",
    lat: 29.96017,
    lng: -90.06002,
    address: "1107 Decatur St",
    neighborhood: "French Quarter",
    hours: daily(T(10), T(28)),
    free: false,
    verify: true,
    tip: "Lower Decatur institution, open deep into the night. The frozen Irish coffee is the toll — pay it gladly.",
  },
  {
    id: "aunt-tikis-decatur",
    name: "Aunt Tiki's",
    category: "customers",
    lat: 29.96094,
    lng: -90.05925,
    address: "1207 Decatur St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A cash-only tiki dive bar that never closes, which in the Quarter is its own kind of miracle. Buy something cheap and the restroom is yours at any hour.",
  },
  {
    id: "bourbon-street-drinkery",
    name: "Bourbon Street Drinkery",
    category: "customers",
    lat: 29.95508,
    lng: -90.06893,
    address: "217 Bourbon St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "Two blocks off Canal, so it's the first realistic bathroom stop as you turn onto Bourbon rather than trekking deep into the strip. Reviewers specifically call out the restrooms near the back patio as some of the cleanest on the street — worth the price of one drink.",
  },
  {
    id: "cafe-envie-decatur",
    name: "Cafe Envie",
    category: "customers",
    lat: 29.96146,
    lng: -90.05871,
    address: "1241 Decatur St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(7), T(23))],
      [R(T(7), T(23))],
      [R(T(7), T(23))],
      [R(T(7), T(23))],
      [R(T(7), T(23))],
      [R(T(7), T(24))],
      [R(T(7), T(24))],
    ),
    free: false,
    verify: true,
    tip: "An open-air corner cafe near the French Market pouring espresso and pastries late into the evening. Handy after dark on lower Decatur when nearby shops have already rolled down their gates.",
  },
  {
    id: "cats-meow-bourbon",
    name: "Cat's Meow",
    category: "customers",
    lat: 29.95872,
    lng: -90.06568,
    address: "701 Bourbon St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "The world-famous karaoke bar right on the Bourbon and St. Peter corner, running 2-for-1 drinks every night from open until 8pm. High foot traffic means staff are used to walk-ins — an easier restroom stop than a cramped shotgun bar.",
  },
  {
    id: "ccs-coffee-royal-st",
    name: "CC's Coffee House (Royal St)",
    category: "customers",
    lat: 29.96048,
    lng: -90.06281,
    address: "941 Royal St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(7), T(20))],
      [R(T(6), T(20))],
      [R(T(6), T(20))],
      [R(T(6), T(20))],
      [R(T(6), T(20))],
      [R(T(6), T(20))],
      [R(T(7), T(20))],
    ),
    free: false,
    verify: true,
    tip: "A regional coffee chain outpost on Royal St between St. Ann and Dumaine, with AC, wifi, and a straightforward counter-service restroom for customers. A calmer coffee-and-bathroom stop than anything facing Bourbon.",
  },
  {
    id: "chateau-lemoyne-holiday-inn-lobby",
    name: "Chateau LeMoyne, French Quarter — A Holiday Inn Hotel Lobby",
    category: "lobby",
    lat: 29.95624,
    lng: -90.06928,
    address: "301 Dauphine St, New Orleans, LA 70112",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    tip: "A bright, chain-hotel lobby a block off Bourbon with a confirmed 24-hour front desk and plenty of lounge seating. As a Holiday Inn it's less precious about walk-in traffic than the boutique places nearby — stroll in like you're headed to the elevators.",
  },
  {
    id: "croissant-dor-ursulines",
    name: "Croissant D'Or Patisserie",
    category: "customers",
    lat: 29.96097,
    lng: -90.06133,
    address: "617 Ursulines Ave, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(7), T(15))],
      [R(T(7), T(14))],
      null,
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A quiet French bakery on Ursulines that's been going since 1983, calmer than the Decatur St scrum. Get a croissant and café au lait, then use the restroom out back before continuing toward Esplanade. Closed Tuesdays.",
  },
  {
    id: "four-points-french-quarter-lobby",
    name: "Four Points by Sheraton French Quarter Lobby",
    category: "lobby",
    lat: 29.95775,
    lng: -90.06665,
    address: "541 Bourbon St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: UNKNOWN_HOURS,
    free: true,
    verify: true,
    tip: "Right at Bourbon and Toulouse, with a lobby bar that opens onto the street and reads more like a public bar than a guarded hotel entrance. The front desk runs 24 hours, but bar service is limited to evenings and weekends, so time it accordingly.",
  },
  {
    id: "french-truck-coffee-chartres",
    name: "French Truck Coffee (Chartres St)",
    category: "customers",
    lat: 29.95386,
    lng: -90.06717,
    address: "217 Chartres St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(8), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(8), T(18))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A roomy, roughly 40-seat French Quarter café a few blocks off Decatur, away from the Jackson Square crush. Ask for the bathroom code while you're in line — a reviewer confirmed it's clean and code-locked to customers.",
  },
  {
    id: "fritzels-jazz-pub",
    name: "Fritzel's European Jazz Pub",
    category: "customers",
    lat: 29.95929,
    lng: -90.06514,
    address: "733 Bourbon St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(11), T(24))],
      [R(T(16), T(24))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Bourbon Street's oldest continually-operating jazz club, with live sets starting most days around 12:30pm. Lower-key than the daiquiri shops next door — one drink at the bar buys you a seat and a restroom out back in the alley, unglamorous but functioning.",
  },
  {
    id: "hotel-de-la-poste-lobby",
    name: "Hotel de la Poste – French Quarter (former W Hotel) Lobby",
    category: "lobby",
    lat: 29.9545,
    lng: -90.06623,
    address: "316 Chartres St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    verify: true,
    tip: "The old W French Quarter got a full renovation and a new name in 2024 — look for \"Hotel de la Poste,\" not the old signage. Small, walk-in-friendly ground-floor lobby just off Chartres near Bourbon and the river.",
  },
  {
    id: "jean-lafitte-nps-visitor-center",
    name: "Jean Lafitte National Historical Park – French Quarter Visitor Center",
    category: "public",
    lat: 29.95485,
    lng: -90.0648,
    address: "419 Decatur St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      null,
      null,
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
      [R(T(9, 30), T(16, 30))],
    ),
    free: true,
    wheelchair: true,
    tip: "A National Park Service visitor center steps from Jackson Square, with a clean, ADA-accessible restroom and a ranger desk to boot. Free admission, no ticket required — just walk in Tuesday through Saturday. Closed Sundays, Mondays, and federal holidays.",
  },
  {
    id: "krazy-korner-bourbon",
    name: "Krazy Korner",
    category: "customers",
    lat: 29.95843,
    lng: -90.06569,
    address: "640 Bourbon St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(14), T(28))],
      [R(T(17), T(28))],
      [R(T(17), T(28))],
      [R(T(17), T(28))],
      [R(T(17), T(28))],
      [R(T(17), T(28))],
      [R(T(14), T(28))],
    ),
    free: false,
    verify: true,
    tip: "Corner bar at Bourbon and St. Peter with a street-level balcony and no cover, leaning on local blues and R&B over piped-in playlists. A $3 shot buys you a legitimate reason to duck into the restroom mid-block.",
  },
  {
    id: "napoleon-house-chartres",
    name: "Napoleon House",
    category: "customers",
    lat: 29.95586,
    lng: -90.06507,
    address: "500 Chartres St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "A 200-year-old bar and restaurant at Chartres and St. Louis, open daily for a Pimm's Cup or a muffaletta. Order something and use the restroom — it's a quieter, more historic alternative to the Bourbon St scrum a few blocks over.",
  },
  {
    id: "omni-royal-orleans-lobby",
    name: "Omni Royal Orleans Lobby",
    category: "lobby",
    lat: 29.95631,
    lng: -90.06569,
    address: "621 St Louis St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: "24/7",
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A grand, marble-floored four-diamond lobby at St. Louis and Royal with a 24-hour front desk and constant foot traffic. Walk in like you're headed to the elevators — restrooms are right there in the lobby and elevator bank, and it's wheelchair accessible.",
  },
  {
    id: "pat-obriens-courtyard-bourbon",
    name: "Pat O'Brien's Courtyard Restaurant",
    category: "customers",
    lat: 29.9581,
    lng: -90.0658,
    address: "624 Bourbon St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(12), T(24))],
      [R(T(16), T(24))],
      null,
      [R(T(12), T(24))],
      [R(T(12), T(24))],
      [R(T(12), T(26))],
      [R(T(12), T(26))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "The Bourbon Street courtyard entrance to the legendary Hurricane bar, complete with a flaming fountain and garden seating. Wheelchair accessible, and a purchase here (even a to-go Hurricane) gets you into a full restaurant-grade restroom rather than a bar-closet situation. Closed Tuesdays.",
  },
  {
    id: "pjs-coffee-decatur-st",
    name: "PJ's Coffee (Decatur St)",
    category: "customers",
    lat: 29.95542,
    lng: -90.06415,
    address: "501 Decatur St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: daily(T(7), T(18)),
    free: false,
    verify: true,
    tip: "Steps from Jackson Square and the French Market, with tables, chairs, and a clean restroom instead of the Café du Monde line. Grab a coffee first — the restroom is for customers.",
  },
  {
    id: "popeyes-canal-st",
    name: "Popeyes (Canal St)",
    category: "customers",
    lat: 29.95284,
    lng: -90.06818,
    address: "621 Canal St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(25))],
      [R(T(10), T(25))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A block off the Quarter on Canal St, staying open past midnight most nights when the Quarter's usual spots have already locked up. Dine-in seating means a real restroom, not just a drive-thru window.",
  },
  {
    id: "rouses-royal-st",
    name: "Rouses Market #30 (French Quarter / Royal St)",
    category: "customers",
    lat: 29.95811,
    lng: -90.06478,
    address: "701 Royal St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "The French Quarter's only full grocery store, wedged into a historic building near Royal & St. Peter with wine, butcher, and seafood counters. When the Quarter's public options run dry, a full-scale supermarket restroom is a genuine relief.",
  },
  {
    id: "bourbon-pub-and-parade",
    name: "The Bourbon Pub and Parade",
    category: "customers",
    lat: 29.9596,
    lng: -90.06491,
    address: "801 Bourbon St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(12), T(27))],
      [R(T(12), T(25))],
      null,
      [R(T(12), T(27))],
      [R(T(12), T(27))],
      [R(T(12), T(29))],
      [R(T(12), T(29))],
    ),
    free: false,
    verify: true,
    tip: "Anchor gay bar and dance club at the quieter St. Ann end of Bourbon, open until 5am Friday and Saturday. It's a big multi-level venue used to walk-in traffic, though the restroom has limited stalls, so expect a line at peak hours.",
  },
  {
    id: "turtle-bay-decatur",
    name: "Turtle Bay",
    category: "customers",
    lat: 29.96043,
    lng: -90.05991,
    address: "1119 Decatur St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "A laid-back Decatur St dive with pizza and a rare thing in the Lower Quarter: round-the-clock hours Thursday through Saturday, plus a bar open until 3 a.m. the rest of the week. Buy a drink or a slice and the restroom is yours.",
  },
  {
    id: "central-grocery-decatur",
    name: "Central Grocery & Deli",
    category: "customers",
    lat: 29.95887,
    lng: -90.06101,
    address: "923 Decatur St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: daily(T(9), T(17)),
    free: false,
    verify: true,
    tip: "Birthplace of the muffuletta, rebuilt after Hurricane Ida and reopened in late 2024. Buy a quarter muff — you were going to anyway — and the restroom follows. Daily 9 to 5.",
  },
  {
    id: "daisy-dukes-french-quarter",
    name: "Daisy Dukes (French Quarter)",
    category: "customers",
    lat: 29.95321,
    lng: -90.06787,
    address: "121 Chartres St, New Orleans, LA 70130",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      null,
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14)), R(T(17), T(22))],
      [R(T(7), T(14)), R(T(17), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Old-school diner breakfast a block off Canal. Ignore the vintage 24-hour signage — these days it's mornings plus weekend dinners — but a 7 a.m. open makes it the early-bird play in the upper Quarter. Closed Tuesdays.",
  },
  {
    id: "the-alibi-iberville",
    name: "The Alibi Bar & Grill",
    category: "customers",
    lat: 29.955,
    lng: -90.06933,
    address: "811 Iberville St, New Orleans, LA 70112",
    neighborhood: "French Quarter",
    hours: daily(T(11), T(28)),
    free: false,
    verify: true,
    tip: "Bar and grill just off Canal serving food deep into the night — open daily from 11 a.m. until the crowd gives out around 4 a.m. Not quite the 24/7 its old signage promised, but at 3 a.m. on Iberville it's close enough.",
  },
  {
    id: "tropical-isle-bourbon",
    name: "Tropical Isle Bourbon",
    category: "customers",
    lat: 29.95919,
    lng: -90.06534,
    address: "721 Bourbon St, New Orleans, LA 70116",
    neighborhood: "French Quarter",
    hours: week(
      [R(T(12), T(26))],
      [R(T(12), T(26))],
      [R(T(12), T(26))],
      [R(T(12), T(26))],
      [R(T(12), T(26))],
      [R(T(12), T(27, 30))],
      [R(T(12), T(27, 30))],
    ),
    free: false,
    verify: true,
    tip: "The Hand Grenade franchise's mid-Bourbon outpost, with the Top of the Trop balcony upstairs. Buy the drink, earn the restroom — the original sits a block away at 600 Bourbon if you're collecting the set.",
  },
];
