import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** Lower Garden District, Garden District, and the Irish Channel. */
export const GARDEN_DISTRICT_SPOTS: readonly Spot[] = [
  {
    id: "pontchartrain-hotel-bayou-bar",
    name: "The Pontchartrain Hotel Lobby (Bayou Bar)",
    category: "lobby",
    lat: 29.93508,
    lng: -90.07969,
    address: "2031 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "Garden District",
    hours: "24/7",
    free: true,
    wheelchair: true,
    verify: true,
    tip: "This 1927 hotel on the St. Charles streetcar line has a wheelchair-accessible washroom with grab rails right off the grand lobby, between the Bayou Bar and Silver Whistle Cafe. Walk in past the chandeliers and checkered floors like you're headed for a cocktail — the lobby reads as a public lounge, not a guests-only zone.",
  },
  {
    id: "touro-infirmary-main-lobby",
    name: "Touro Infirmary Main Lobby",
    category: "public",
    lat: 29.92586,
    lng: -90.09207,
    address: "1401 Foucher St, New Orleans, LA 70115",
    neighborhood: "Garden District",
    hours: daily(T(8), T(20, 30)),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "A staffed hospital lobby with an information desk, Café Touro, a gift shop, and restrooms right off the Foucher Street entrance. Wheelchair accessible throughout, with walkways linking both parking garages during visiting hours.",
  },
  {
    id: "abita-new-orleans-taproom",
    name: "Abita New Orleans Taproom",
    category: "customers",
    lat: 29.92212,
    lng: -90.07451,
    address: "2375 Tchoupitoulas St, New Orleans, LA 70130",
    neighborhood: "Irish Channel",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "Abita's second taproom, opened in 2025 on Tchoupitoulas's brewery row, with 35 taps and a big indoor-outdoor layout. Full restaurant-grade restrooms — buy a beer and you're set.",
  },
  {
    id: "miel-brewery-taproom",
    name: "Miel Brewery & Taproom",
    category: "customers",
    lat: 29.92028,
    lng: -90.07987,
    address: "405 Sixth St, New Orleans, LA 70115",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(20))],
      [R(T(14), T(22))],
      [R(T(14), T(22))],
      [R(T(14), T(22))],
      [R(T(14), T(22))],
      [R(T(14), T(23))],
      [R(T(11), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Half open-air beer garden, half air-conditioned warehouse with pub games and a ping-pong table — dog- and kid-friendly. Buy a pint and the restroom is easy to find inside the warehouse half.",
  },
  {
    id: "nola-brewing-taproom",
    name: "NOLA Brewing Taproom",
    category: "customers",
    lat: 29.91976,
    lng: -90.08173,
    address: "3033 Tchoupitoulas St, New Orleans, LA 70115",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    wheelchair: true,
    tip: "The OG post-Katrina brewery, pouring 16 beers including an Irish Channel Stout named for the neighborhood it sits in. First-floor restrooms are wheelchair accessible — buy a pint or a flight and you're in.",
  },
  {
    id: "parasols-bar-and-restaurant",
    name: "Parasol's Bar and Restaurant",
    category: "customers",
    lat: 29.92642,
    lng: -90.08016,
    address: "2533 Constance St, New Orleans, LA 70130",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(26))],
      [R(T(11), T(26))],
    ),
    free: false,
    verify: true,
    tip: "An Irish Channel dive bar since 1952, famous for roast beef po-boys and a legendary St. Patrick's Day block party. Open past midnight every night of the week, which makes it a solid late-hour option off the main Magazine Street strip.",
  },
  {
    id: "turkey-and-the-wolf",
    name: "Turkey and the Wolf",
    category: "customers",
    lat: 29.92665,
    lng: -90.07438,
    address: "739 Jackson Ave, New Orleans, LA 70130",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(16))],
      [R(T(11), T(16))],
      null,
      [R(T(11), T(16))],
      [R(T(11), T(16))],
      [R(T(11), T(16))],
      [R(T(11), T(16))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "James Beard Award-winning sandwich shop right where Jackson Avenue meets Magazine Street. Order the fried bologna or a collard green melt and use the wheelchair-accessible restroom while you wait — closed Tuesdays, so plan your pee-and-po-boy run accordingly.",
  },
  {
    id: "courtyard-brewery",
    name: "Courtyard Brewery",
    category: "customers",
    lat: 29.94004,
    lng: -90.07196,
    address: "1160 Camp St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(11), T(24))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
    ),
    free: false,
    verify: true,
    tip: "New Orleans' first nanobrewery — a tiny, family-owned neighborhood bar with a namesake courtyard and rotating food trucks. Order a house-brewed beer and the restroom's yours just off the Warehouse District path.",
  },
  {
    id: "french-truck-coffee-magazine-1200",
    name: "French Truck Coffee (Lower Garden District)",
    category: "customers",
    lat: 29.93915,
    lng: -90.07074,
    address: "1200 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: UNKNOWN_HOURS,
    free: false,
    wheelchair: true,
    verify: true,
    tip: "The original French Truck roastery and cafe on Magazine near Felicity. Ask for the bathroom code while you're in line — reviewers say it's kept clean. Hours drift by day and by source, so call ahead if you're cutting it close.",
  },
  {
    id: "garden-district-pub",
    name: "Garden District Pub",
    category: "customers",
    lat: 29.93123,
    lng: -90.07416,
    address: "1916 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(14), T(26))],
      [R(T(17), T(26))],
      [R(T(17), T(26))],
      [R(T(17), T(26))],
      [R(T(17), T(26))],
      [R(T(15), T(26))],
      [R(T(14), T(26))],
    ),
    free: false,
    verify: true,
    tip: "A neighborhood cocktail bar right on Magazine Street with restrooms reviewers actually praise for being clean. Open until 2 a.m. nightly, making it a solid late-night option on the Jackson-to-Louisiana stretch.",
  },
  {
    id: "igors-lounge-st-charles",
    name: "Igor's Lounge & Gameroom",
    category: "customers",
    lat: 29.93457,
    lng: -90.08053,
    address: "2133 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Dive bar, pool hall, and laundromat under one 24-hour roof on the streetcar line. Somebody is always doing a load of wash at 4 a.m., so nobody blinks if you just need the bathroom.",
  },
  {
    id: "lillys-cafe-magazine",
    name: "Lilly's Cafe (Magazine St)",
    category: "customers",
    lat: 29.93208,
    lng: -90.07344,
    address: "1813 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      null,
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Beloved Vietnamese pho spot on Magazine near Jackson Ave, with a wheelchair-accessible entrance. A quick bowl or banh mi buys you restroom access at this sit-down neighborhood favorite. Closed Sundays.",
  },
  {
    id: "mojo-coffee-house-magazine",
    name: "Mojo Coffee House",
    category: "customers",
    lat: 29.93422,
    lng: -90.07231,
    address: "1500 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: daily(T(6), T(19)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Long-running neighborhood coffeehouse whose gender-neutral restroom is locally famous as a tiny hidden museum. Order a coffee or pastry and it's yours to use, with outdoor seating and Wi-Fi if you want to stay a while. Open early to evening, every day.",
  },
  {
    id: "pjs-coffee-magazine-st",
    name: "PJ's Coffee (Magazine St)",
    category: "customers",
    lat: 29.92963,
    lng: -90.07654,
    address: "2140 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: daily(T(6), T(19)),
    free: false,
    verify: true,
    tip: "A sit-down PJ's on the Magazine St antique strip, open 13 hours a day. Multiple reviewers specifically call out how clean the restroom is kept, which is more than most coffee shops earn.",
  },
  {
    id: "popeyes-st-charles",
    name: "Popeyes (St. Charles Ave)",
    category: "customers",
    lat: 29.94074,
    lng: -90.07459,
    address: "1243 St. Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
      [R(T(10), T(25))],
      [R(T(10), T(25))],
    ),
    free: false,
    verify: true,
    tip: "Right on the St. Charles streetcar line near Lee Circle and the Contemporary Arts Center, with a lobby full of dine-in seating for watching the streetcars roll by. Quick stop for museum-goers, small purchase expected for the restroom.",
  },
  {
    id: "raising-canes-st-charles-ave",
    name: "Raising Cane's (St. Charles Ave)",
    category: "customers",
    lat: 29.9394,
    lng: -90.07494,
    address: "1406 St. Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: daily(T(10), T(22)),
    free: false,
    verify: true,
    tip: "Right on the streetcar line across from Lee Circle, with steady 10-to-10 dine-in hours that make it an easy, predictable stop while touring the Garden District.",
  },
  {
    id: "surreys-cafe-lower-garden",
    name: "Surrey's Café & Juice Bar (Lower Garden District)",
    category: "customers",
    lat: 29.93577,
    lng: -90.07183,
    address: "1418 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(8), T(15))],
      [R(T(8), T(15))],
      null,
      null,
      [R(T(8), T(15))],
      [R(T(8), T(15))],
      [R(T(8), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A popular brunch and fresh-juice spot on Magazine Street. The dining room is narrow, but the unisex restroom in back by the ATM is a legitimate stop if you grab a juice or breakfast plate. Open Thursday through Monday only — closed Tuesday and Wednesday.",
  },
  {
    id: "urban-south-brewery-nola",
    name: "Urban South Brewery (New Orleans taproom)",
    category: "customers",
    lat: 29.92966,
    lng: -90.06664,
    address: "1645 Tchoupitoulas St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A big family-friendly taproom near the Convention Center with indoor and outdoor seating and Urban South burgers on site. Grab a pint, then duck in — it's a steady stop for both tourists and locals.",
  },
  {
    id: "walmart-supercenter-tchoupitoulas",
    name: "Walmart Supercenter (Tchoupitoulas)",
    category: "public",
    lat: 29.92512,
    lng: -90.07013,
    address: "1901 Tchoupitoulas St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: daily(T(6), T(23)),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "Big-box restrooms near the front of the store, no purchase needed. A 2024 remodel explicitly included new bathrooms, so this is a dependable stop for anyone walking the riverfront/Tchoupitoulas corridor.",
  },
  {
    id: "district-donuts",
    name: "District Donuts Sliders Brew",
    category: "customers",
    lat: 29.9295,
    lng: -90.07716,
    address: "2209 Magazine St",
    neighborhood: "Lower Garden District",
    hours: daily(T(7), T(19)),
    free: false,
    verify: true,
    tip: "Donuts, sliders, coffee — and a restroom on the Magazine Street shopping crawl, where options run mysteriously thin.",
  },
  {
    id: "mcdonalds-st-charles",
    name: "McDonald's (St. Charles Ave)",
    category: "customers",
    lat: 29.9288,
    lng: -90.09106,
    address: "3321 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Garden District",
    hours: daily(T(6), T(22)),
    free: false,
    verify: true,
    tip: "Right on the streetcar line with a confirmed customer restroom. The drive-thru runs 24/7 but the dining room keeps mortal hours — don't bet your bladder on the lobby after 10 p.m.",
  },
  {
    id: "the-rink-chicory-house",
    name: "The Rink (Chicory House)",
    category: "customers",
    lat: 29.93004,
    lng: -90.0849,
    address: "2727 Prytania St, New Orleans, LA 70130",
    neighborhood: "Garden District",
    hours: week(
      [R(T(8), T(16))],
      [R(T(7), T(16))],
      [R(T(7), T(16))],
      [R(T(7), T(16))],
      [R(T(7), T(16))],
      [R(T(7), T(16))],
      [R(T(8), T(16))],
    ),
    free: false,
    verify: true,
    tip: "Coffee shop inside the old skating-rink shopping center across from Lafayette Cemetery No. 1. A chicory latte buys the café restroom — the mall's separate public toilet famously takes a quarter, so carry change or carry on.",
  },
  {
    id: "juans-flying-burrito-magazine",
    name: "Juan's Flying Burrito (Magazine St)",
    category: "customers",
    lat: 29.93061,
    lng: -90.07499,
    address: "2018 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "Punk-rock burrito institution on lower Magazine, open 11 to 10 daily. Order at the bar if the tables are full — customers get the restroom, no questions.",
  },
  {
    id: "hotel-saint-vincent-lobby",
    name: "Hotel Saint Vincent (Lobby)",
    category: "lobby",
    lat: 29.93423,
    lng: -90.07283,
    address: "1507 Magazine St, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: "24/7",
    free: true,
    wheelchair: true,
    tip: "A restored 1861 orphanage turned scene-y hotel — the lobby opens onto the Paradise Lounge and Chapel Club. Accessible public washroom on the amenity list; the décor alone is worth the detour.",
  },
  {
    id: "ruby-slipper-uptown-magazine",
    name: "Ruby Slipper Cafe (Uptown)",
    category: "customers",
    lat: 29.92599,
    lng: -90.08266,
    address: "2802 Magazine St, New Orleans, LA 70130",
    neighborhood: "Garden District",
    hours: week(
      [R(T(7), T(15))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(14))],
      [R(T(7), T(15))],
    ),
    free: false,
    verify: true,
    tip: "BBQ shrimp and grits, bananas Foster French toast, and a full sit-down dining room on Magazine Street. Expect a wait for brunch, but once you're seated the restroom is fair game.",
  },
  {
    id: "basin-seafood-spirits",
    name: "Basin Seafood and Spirits",
    category: "customers",
    lat: 29.92359,
    lng: -90.08694,
    address: "3222 Magazine St, New Orleans, LA 70115",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11, 30), T(21))],
      null,
      null,
      [R(T(15), T(21))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
    ),
    free: false,
    verify: true,
    tip: "Gulf seafood and lighter Louisiana classics from the Baru chef-owner team, with sidewalk seating on Magazine and a courtyard out back. Closed Tuesday and Wednesday — a sit-down meal or drink the rest of the week gets you in the door.",
  },
  {
    id: "the-bulldog-uptown",
    name: "The Bulldog Uptown",
    category: "customers",
    lat: 29.92348,
    lng: -90.08735,
    address: "3236 Magazine St, New Orleans, LA 70115",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(24))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
    ),
    free: false,
    tip: "Fifty-plus nitrogen drafts and a tree-lined beer garden with a fountain built out of beer taps. Dog-friendly, full pub food menu, open daily into the early morning — order a beer and use the restroom inside.",
  },
  {
    id: "the-rum-house-magazine",
    name: "The Rum House",
    category: "customers",
    lat: 29.92408,
    lng: -90.08603,
    address: "3128 Magazine St, New Orleans, LA 70115",
    neighborhood: "Irish Channel",
    hours: week(
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      null,
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    tip: "Caribbean taqueria and rum bar on Magazine Street — tacos, ceviche, and a serious rum cocktail list. Closed Wednesdays; otherwise buy a taco plate or a drink and use the small bar bathroom.",
  },
  {
    id: "care-forgot-beercraft",
    name: "Care Forgot Beercraft",
    category: "customers",
    lat: 29.93701,
    lng: -90.07674,
    address: "1728 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "The first brewery ever on St. Charles Avenue — house-made beer and handmade pizza across an AC'd indoor room, a shaded back deck, and streetside seating, right on the streetcar line. Hours have shifted around, so call ahead before you plan your bladder's day around it.",
  },
  {
    id: "high-grinds-coffee",
    name: "High Grinds Coffee",
    category: "customers",
    lat: 29.93734,
    lng: -90.07699,
    address: "1722 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      [R(T(8), T(15))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(7), T(18))],
      [R(T(8), T(15))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "New coffee bar right on the St. Charles streetcar line, pairing locally roasted coffee with hemp-derived drinks in a renovated historic building. ADA-compliant entrance and accessible parking are documented, and the sit-down 'community living room' layout makes a restroom stop for customers realistic.",
  },
  {
    id: "hivolt-coffee",
    name: "HiVolt Coffee",
    category: "customers",
    lat: 29.93228,
    lng: -90.07445,
    address: "1829 Sophie Wright Pl, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: week(
      null,
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
    ),
    free: false,
    tip: "Longtime Lower Garden District neighborhood coffee shop with a full breakfast-and-lunch menu, indoor seating, and a shaded patio. Closed Sundays.",
  },
  {
    id: "quartz-bar-quisby",
    name: "Quartz Bar",
    category: "customers",
    lat: 29.94095,
    lng: -90.07454,
    address: "1225 St Charles Ave, New Orleans, LA 70130",
    neighborhood: "Lower Garden District",
    hours: "24/7",
    free: false,
    tip: "The 24/7 bar on the ground floor of The Quisby hotel, right on the St. Charles streetcar line — the hotel's own FAQ says locals are welcome, not just guests. Buy a drink, use the room.",
  },
];
