import type { Spot } from "../types";
import { T, R, daily, week } from "./helpers";

/** Lakeview, West End, the Lakefront, and Gentilly. */
export const LAKEFRONT_SPOTS: readonly Spot[] = [
  {
    id: "fair-grounds-race-course-slots",
    name: "Fair Grounds Race Course & Slots",
    category: "public",
    lat: 29.98476,
    lng: -90.07665,
    address: "1751 Gentilly Blvd, New Orleans, LA 70119",
    neighborhood: "Gentilly",
    hours: week(
      [R(T(10), T(24))],
      [R(T(9), T(24))],
      [R(T(9), T(24))],
      [R(T(9), T(24))],
      [R(T(9), T(24))],
      [R(T(9), T(24))],
      [R(T(9), T(24))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "New Orleans' historic track and 600-plus-machine slots hall, with wheelchair-accessible restrooms in the grandstand and clubhouse. General admission is free most days (21+ for the slots floor); go on an off-peak day, since weekend crowds have been known to run the supplies low.",
  },
  {
    id: "norman-mayer-branch-library",
    name: "Norman Mayer Branch Library",
    category: "public",
    lat: 29.99729,
    lng: -90.06151,
    address: "3001 Gentilly Blvd, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    verify: true,
    tip: "A rebuilt post-Katrina branch on the main Gentilly Boulevard corridor. It closed earlier in 2026 for roof and HVAC repairs but reopened June 22 with full regular hours restored.",
  },
  {
    id: "rouses-market-gentilly",
    name: "Rouses Market (Gentilly)",
    category: "customers",
    lat: 30.02783,
    lng: -90.05457,
    address: "6600 Franklin Ave, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "A full-size Rouses supermarket anchoring Gentilly Terrace, open long hours every day of the week. Grab a snack near the front and use the restroom typical of Rouses locations.",
  },
  {
    id: "taco-bell-robert-e-lee",
    name: "Taco Bell (Robert E. Lee Blvd)",
    category: "customers",
    lat: 30.02248,
    lng: -90.06172,
    address: "2169 Robert E. Lee Blvd, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: week(
      [R(T(10), T(26))],
      [R(T(10), T(26))],
      [R(T(10), T(26))],
      [R(T(10), T(26))],
      [R(T(10), T(26))],
      [R(T(10), T(27))],
      [R(T(10), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A Gentilly fast-food dine-in lobby near Lake Pontchartrain, useful where restroom options thin out. Grab something off the value menu and use the facilities like any other paying customer.",
  },
  {
    id: "lakefront-shelter-2",
    name: "Lakefront Shelter #2 Restrooms",
    category: "public",
    lat: 30.031,
    lng: -90.089,
    address: "Lakeshore Drive at Tern St, New Orleans, LA 70124",
    neighborhood: "Lakefront",
    hours: daily(T(0), T(19, 30)),
    free: true,
    verify: true,
    tip: "A public shelter pavilion on the seawall near Lake Vista, required by the Lakefront Management Authority to keep its restrooms open to everyone until 7:30pm. Good for a walk, bike ride, or fishing trip along the lake — condition can vary, so have a backup in mind.",
  },
  {
    id: "messinas-runway-cafe-lakefront",
    name: "Messina's Runway Cafe (Lakefront Airport Terminal)",
    category: "customers",
    lat: 30.0359,
    lng: -90.02575,
    address: "6001 Stars and Stripes Blvd, New Orleans, LA 70126",
    neighborhood: "Lakefront",
    hours: week(
      [R(T(9), T(15, 30))],
      null,
      [R(T(8, 30), T(15, 30))],
      [R(T(8, 30), T(15, 30))],
      [R(T(8, 30), T(15, 30))],
      [R(T(8, 30), T(15, 30))],
      [R(T(9), T(15, 30))],
    ),
    free: false,
    verify: true,
    tip: "A full sit-down diner inside the restored Art Deco terminal at Lakefront Airport, serving breakfast, lunch, and weekend brunch. Reviewers specifically call the restroom spacious and clean — a solid excuse to also gawk at the murals and travertine staircase on your way in.",
  },
  {
    id: "762-coffee-cocktails-lakeview",
    name: "762 Coffee + Cocktails",
    category: "customers",
    lat: 30.00427,
    lng: -90.1064,
    address: "762 Harrison Ave, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: week(
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(22))],
      [R(T(7), T(22))],
      [R(T(7), T(23))],
      [R(T(7), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Coffee shop by day, cocktail bar by night, right on the main Harrison Ave strip. Open from early morning to late most nights, so it covers you whether you need a restroom stop with your espresso or your nightcap.",
  },
  {
    id: "earl-k-long-library-uno",
    name: "Earl K. Long Library (University of New Orleans)",
    category: "public",
    lat: 30.03058,
    lng: -90.06322,
    address: "2000 Lakeshore Dr, New Orleans, LA 70148",
    neighborhood: "Lakeview",
    hours: week(
      [R(T(13, 30), T(21))],
      [R(T(8), T(21))],
      [R(T(8), T(21))],
      [R(T(8), T(21))],
      [R(T(8), T(21))],
      [R(T(8), T(21))],
      null,
    ),
    free: true,
    verify: true,
    tip: "UNO's main library faces the Library Quad near the lake and is the most prominent public-facing building on campus. No ID check at the door — walk in like you belong, because the public genuinely is welcome. Hours shift by semester, so treat this schedule as a typical example.",
  },
  {
    id: "juniors-on-harrison",
    name: "Junior's on Harrison",
    category: "customers",
    lat: 30.00481,
    lng: -90.10589,
    address: "789 Harrison Ave, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: week(
      [R(T(9), T(15))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A New American restaurant and bar anchoring Harrison Ave's restaurant row, with weekend brunch and a full bar. Its own listing notes a gender-neutral, wheelchair-accessible restroom — grab a coffee or a drink and you're set.",
  },
  {
    id: "parlays-lakeview",
    name: "Parlay's",
    category: "customers",
    lat: 30.00408,
    lng: -90.10425,
    address: "870 Harrison Ave, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: week(
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(25))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
    ),
    free: false,
    verify: true,
    tip: "A no-frills Lakeview dive bar billed as one of the longest bars in Orleans Parish, open late nearly every night. Cheap drink, easy restroom access, zero pretense.",
  },
  {
    id: "robert-fresh-market-lakeview",
    name: "Robért Fresh Market (Lakeview / Lakefront)",
    category: "customers",
    lat: 30.02064,
    lng: -90.1115,
    address: "135 Allen Toussaint Blvd, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "Lakeview's neighborhood grocery, running since 1996 and open into the evening every day. Useful backup when you're out near the lakefront parks or West End and the amenities thin out.",
  },
  {
    id: "landrys-seafood-west-end",
    name: "Landry's Seafood House (Lake Pontchartrain)",
    category: "customers",
    lat: 30.0264,
    lng: -90.11338,
    address: "8000 Lakeshore Dr, New Orleans, LA 70124",
    neighborhood: "West End",
    hours: week(
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21))],
      [R(T(11, 30), T(21, 30))],
      [R(T(11, 30), T(22))],
      [R(T(11, 30), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A big chain seafood house right on the West End marina, with a bar overlooking the boats and the lake. Order a drink and the restroom is yours — long, consistent daily hours make it a reliable stop out here.",
  },
  {
    id: "blue-crab-west-end",
    name: "The Blue Crab Restaurant & Oyster Bar",
    category: "customers",
    lat: 30.02583,
    lng: -90.1134,
    address: "7900 Lakeshore Dr, New Orleans, LA 70124",
    neighborhood: "West End",
    hours: week(
      [R(T(11), T(21))],
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A big lakefront seafood house overlooking Lake Pontchartrain and the West End marina, serving boiled seafood and gumbo with a full bar. Sit-down dining room makes for an easy, view-having restroom stop — closed Mondays.",
  },
  {
    id: "cansecos-filmore-market",
    name: "Canseco's Filmore Market",
    category: "customers",
    lat: 30.01265,
    lng: -90.05987,
    address: "2221 Filmore Ave, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: week(
      [R(T(8), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
      [R(T(7), T(21))],
    ),
    free: false,
    verify: true,
    tip: "Gentilly's full-size neighborhood supermarket at Filmore and Elysian Fields, freshly expanded to 14,500 square feet. A proper grocery this size keeps proper restrooms.",
  },
  {
    id: "milne-rec-center",
    name: "Milne Rec Center (NORD)",
    category: "public",
    lat: 30.01442,
    lng: -90.05103,
    address: "5420 Franklin Ave, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(9), T(14))],
    ),
    free: true,
    verify: true,
    tip: "Gentilly's city rec center with free-play gym time and a fitness center. Summer hours 4–9 weekdays plus Saturday mornings; school-year hours start at 10 a.m.",
  },
  {
    id: "popeyes-elysian-fields",
    name: "Popeyes (Elysian Fields)",
    category: "customers",
    lat: 30.02284,
    lng: -90.06166,
    address: "6232 Elysian Fields Ave, New Orleans, LA 70122",
    neighborhood: "Gentilly",
    hours: daily(T(10), T(24)),
    free: false,
    verify: true,
    tip: "Gentilly's hometown-chain outpost with dine-in until midnight. It's Popeyes in its city of birth — get the biscuit while you're in there.",
  },
  {
    id: "gernon-brown-rec-center",
    name: "Gernon Brown Rec Center (NORD)",
    category: "public",
    lat: 30.00429,
    lng: -90.09943,
    address: "1001 Harrison Ave, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(9), T(14))],
    ),
    free: true,
    verify: true,
    tip: "Lakeview's rec center on Harrison Ave — pickleball and open basketball inside, no appointment, no fee. Summer hours 4–9 weekdays, Saturday mornings too.",
  },
  {
    id: "lakeview-grocery",
    name: "Lakeview Grocery",
    category: "customers",
    lat: 30.00501,
    lng: -90.10541,
    address: "801 Harrison Ave, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "Full-service Harrison Ave grocery with 'The Cove' — an actual dine-in seating area with wifi and a coffee counter. Groceries plus a sit-down corner equals dependable facilities, 7 a.m. to 9 p.m. daily.",
  },
  {
    id: "velvet-cactus-lakeview",
    name: "The Velvet Cactus",
    category: "customers",
    lat: 30.0049,
    lng: -90.10301,
    address: "6300 Argonne Blvd, New Orleans, LA 70124",
    neighborhood: "Lakeview",
    hours: week(
      [R(T(11), T(21))],
      [R(T(16, 30), T(21))],
      [R(T(16, 30), T(21))],
      [R(T(16, 30), T(21))],
      [R(T(16, 30), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Lakeview's margarita patio, with a confirmed wheelchair-accessible restroom, entrance, and seating. Weekday evenings only; weekends from 11.",
  },
];
