import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** Mid-City, City Park, Bayou St. John, and Esplanade Ridge. */
export const MIDCITY_SPOTS: readonly Spot[] = [
  {
    id: "cafe-du-monde-city-park",
    name: "Café du Monde (City Park)",
    category: "customers",
    lat: 29.98543,
    lng: -90.0951,
    address: "56 Dreyfous Dr, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(20)),
    free: false,
    verify: true,
    tip: "Unlike the famous original — which has no restroom at all — this Café du Monde lives in City Park's historic Casino Building and does. Beignets first, obviously.",
  },
  {
    id: "besthoff-sculpture-garden",
    name: "Besthoff Sculpture Garden",
    category: "public",
    lat: 29.98776,
    lng: -90.0924,
    address: "1 Collins Diboll Cir, City Park",
    neighborhood: "City Park",
    hours: daily(T(10), T(17)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Free to enter and genuinely world-class: eleven acres of sculpture under the live oaks, with restrooms mapped on OSM. Art, shade, and relief, all gratis.",
  },
  {
    id: "city-park-festival-grounds",
    name: "City Park Festival Grounds Restrooms",
    category: "public",
    lat: 29.98771,
    lng: -90.09795,
    address: "Festival Grounds, near Tad Gormley Stadium, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(18)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Out by Tad Gormley Stadium on the Festival Grounds. Most reliable on event and festival days — can be locked on sleepy weekdays, so have a City Park plan B (the Sculpture Garden).",
  },
  {
    id: "whole-foods-broad",
    name: "Whole Foods Market (N Broad)",
    category: "customers",
    lat: 29.96708,
    lng: -90.08444,
    address: "300 N Broad St",
    neighborhood: "Mid-City",
    hours: daily(T(8), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Mid-City's dependable option in the ReFresh Project building, near the Lafitte Greenway. Grocery-store restrooms: never glamorous, always there.",
  },
  {
    id: "1000-figs-bayou-st-john",
    name: "1000 Figs",
    category: "customers",
    lat: 29.98053,
    lng: -90.08426,
    address: "3141 Ponce De Leon St, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
    ),
    free: false,
    verify: true,
    tip: "A small, well-loved falafel spot tucked just off Esplanade Avenue in the Bayou St. John area. Dine-in seating and an on-site restroom make it a solid stop between bayou walks. Closed Sundays.",
  },
  {
    id: "parkway-bakery-tavern",
    name: "Parkway Bakery & Tavern",
    category: "customers",
    lat: 29.97364,
    lng: -90.09024,
    address: "538 Hagan Ave, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      [R(T(10), T(18))],
      null,
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
    ),
    free: false,
    verify: true,
    tip: "A legendary po'boy counter near Bayou St. John and the Lafitte Greenway, with high turnover and plenty of indoor seating. Reviewers specifically call out how clean the restroom is, so order your po'boy first and go in peace.",
  },
  {
    id: "carousel-gardens-city-park",
    name: "Carousel Gardens Amusement Park",
    category: "customers",
    lat: 29.98758,
    lng: -90.09864,
    address: "7 Victory Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: week(
      null,
      null,
      null,
      [R(T(10), T(15))],
      null,
      null,
      [R(T(11), T(18))],
    ),
    free: false,
    verify: true,
    tip: "Home to the historic 1906 carousel and other rides inside City Park, with restrooms confirmed on site. It's a gated, ticketed park, so you'll need a wristband to get in — hours run seasonal, so check ahead.",
  },
  {
    id: "city-putt-city-park",
    name: "City Putt",
    category: "customers",
    lat: 29.98501,
    lng: -90.09228,
    address: "33 Dreyfous Dr, New Orleans, LA 70119",
    neighborhood: "City Park",
    hours: week(
      [R(T(10), T(22))],
      null,
      null,
      [R(T(15), T(22))],
      [R(T(15), T(22))],
      [R(T(15), T(22))],
      [R(T(10), T(22))],
    ),
    free: false,
    wheelchair: true,
    tip: "Two 36-hole mini-golf courses in City Park, both ADA accessible, with restrooms confirmed on site. Pay the $10-12 round fee to get past the gate — closed Monday and Tuesday.",
  },
  {
    id: "filmore-in-the-oaks",
    name: "Filmore in the Oaks",
    category: "customers",
    lat: 30.01156,
    lng: -90.09866,
    address: "1040 Filmore Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: daily(T(7), T(19)),
    free: false,
    verify: true,
    tip: "The bar and restaurant inside City Park's South Course golf clubhouse, open to golfers and non-golfers alike. Grab a coffee at the counter and use the restroom guests specifically praise for being clean.",
  },
  {
    id: "storyland-city-park",
    name: "Storyland",
    category: "customers",
    lat: 29.98758,
    lng: -90.09681,
    address: "5 Victory Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: week(
      [R(T(10), T(16, 30))],
      null,
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
    ),
    free: false,
    tip: "A storybook-themed kiddie park inside City Park with restrooms confirmed on site. $8 gets you in if you're 36 inches or taller — free under that height or with a Friends of City Park membership.",
  },
  {
    id: "wheel-fun-rentals-big-lake",
    name: "Wheel Fun Rentals Boat House (Big Lake)",
    category: "customers",
    lat: 29.9899,
    lng: -90.0882,
    address: "7 Friederichs Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "The swan-boat and bike rental kiosk on City Park's Big Lake advertises 'easy access to parking, restrooms, and everything you need.' Hours shift seasonally and with the weather, so rent a bike or just ask at the counter.",
  },
  {
    id: "cafe-degas-esplanade",
    name: "Café Degas",
    category: "customers",
    lat: 29.98032,
    lng: -90.08415,
    address: "3127 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(10, 30), T(15)), R(T(17), T(21))],
      null,
      [R(T(17), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(22))],
      [R(T(10, 30), T(23))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "An oak-shaded French bistro on the historic Esplanade Ridge stretch, with a gender-neutral restroom and a covered outdoor deck. Grab a coffee or pastry at the bar if you don't want a full meal — low pressure, easy stop while walking the avenue. Closed Mondays.",
  },
  {
    id: "cansecos-esplanade-market",
    name: "Canseco's Esplanade Market",
    category: "customers",
    lat: 29.98058,
    lng: -90.08451,
    address: "3135 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "A neighborhood grocery on the Esplanade Ave ridge near Bayou St. John, occupying the old Whole Foods building and popular with joggers and dog walkers. Open every day until 10pm; restroom with a small purchase expected.",
  },
  {
    id: "ccs-coffee-esplanade",
    name: "CC's Coffee House (Esplanade Ave)",
    category: "customers",
    lat: 29.97758,
    lng: -90.08063,
    address: "2800 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
    ),
    free: false,
    verify: true,
    tip: "A neighborhood coffee shop on the Esplanade Ridge streetcar line with indoor and umbrella-shaded outdoor seating, roughly midway between City Park and the Quarter. Reviewers confirm the customer restroom is clean and available — just watch for the 1-2pm midday closure.",
  },
  {
    id: "santa-fe-esplanade",
    name: "Santa Fe",
    category: "customers",
    lat: 29.98089,
    lng: -90.085,
    address: "3201 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(11), T(21))],
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A Southwestern/Mexican spot at the lakeside end of Esplanade near the Fair Grounds, with an open-air garden porch and full bar. Order a margarita and settle in — closed Mondays, otherwise open from late morning into the evening.",
  },
  {
    id: "angelo-brocatos-carrollton",
    name: "Angelo Brocato's Ice Cream & Pastry Shop",
    category: "customers",
    lat: 29.97551,
    lng: -90.09918,
    address: "214 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(21))],
      null,
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
    ),
    free: false,
    wheelchair: true,
    tip: "A Sicilian ice cream and pastry institution since 1905, right at the Canal Street corner. Order a cannoli or spumoni and the wheelchair-accessible restroom is yours — it's busy enough that nobody blinks. Closed Mondays.",
  },
  {
    id: "burger-king-canal-st",
    name: "Burger King (Canal St)",
    category: "customers",
    lat: 29.96624,
    lng: -90.08786,
    address: "2727 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(0), T(23, 59))],
      [R(T(0), T(23, 59))],
      [R(T(0), T(23, 59))],
    ),
    free: false,
    verify: true,
    tip: "A near-24-hour Burger King on the Canal St stretch between the Quarter and City Park, dining room open into the early morning on weekends. A reviewer noted staff expect a purchase before you use the restroom, so grab a fry first.",
  },
  {
    id: "mandinas-canal-street",
    name: "Mandina's Restaurant",
    category: "customers",
    lat: 29.97218,
    lng: -90.09812,
    address: "3800 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
    ),
    free: false,
    wheelchair: true,
    tip: "A Canal Street landmark serving turtle soup and trout amandine since 1932. The ramp, seating, and restroom are all wheelchair accessible, and it's an easy in-and-out for a quick bite plus a bathroom stop.",
  },
  {
    id: "mcdonalds-n-broad-st",
    name: "McDonald's (N Broad St)",
    category: "customers",
    lat: 29.9837,
    lng: -90.07167,
    address: "1918 N Broad St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Open around the clock near the Lafitte Greenway and Bayou St. John, where late-night options in this part of Mid-City are thin. Standard dine-in lobby with a public restroom.",
  },
  {
    id: "rouses-mid-city",
    name: "Rouses Market (Mid-City)",
    category: "customers",
    lat: 29.97635,
    lng: -90.09653,
    address: "400 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(7), T(23)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Full-service, locally-owned grocery store near the Canal streetcar terminus, open long hours every day. Deli, bakery, seafood counter, and a wheelchair-accessible customer restroom — a reliable option well past when the restaurants have stopped serving.",
  },
  {
    id: "sacred-grinds-canal-st",
    name: "Sacred Grinds Coffee House",
    category: "customers",
    lat: 29.98141,
    lng: -90.11025,
    address: "5055 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(7), T(17))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
    ),
    free: false,
    verify: true,
    tip: "The only cafe at the far end of the Canal streetcar line, wedged between two cemeteries near the Katrina Memorial. Small neighborhood spot, but a genuinely useful coffee-and-restroom break if you're out at that end of Canal St.",
  },
  {
    id: "second-line-brewing",
    name: "Second Line Brewing",
    category: "customers",
    lat: 29.98249,
    lng: -90.10525,
    address: "433 N Bernadotte St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(12), T(20))],
      [R(T(16), T(22))],
      [R(T(16), T(21))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
      [R(T(14), T(22))],
      [R(T(12), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A dog-friendly Mid-City taproom with a big covered beer garden and rotating food trucks. Grab a pint and the indoor restroom is right there for customers.",
  },
  {
    id: "toups-meatery-carrollton",
    name: "Toups' Meatery",
    category: "customers",
    lat: 29.98057,
    lng: -90.09456,
    address: "845 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(23))],
      [R(T(11), T(15)), R(T(17), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Isaac Toups' acclaimed Cajun spot on N. Carrollton, known for house-made charcuterie and boudin. A full sit-down restaurant with proper facilities, open for both lunch and dinner most days — a good stop on the walk toward the cemeteries.",
  },
  {
    id: "waffle-house-2500-canal",
    name: "Waffle House #2196",
    category: "customers",
    lat: 29.96384,
    lng: -90.0851,
    address: "2500 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Classic yellow-sign Waffle House right on Canal, open around the clock. Order cheap coffee and hash browns and use the restroom — reviewers specifically call this location's restrooms spotless.",
  },
  {
    id: "acorn-cafe-childrens-museum",
    name: "Acorn Café (Louisiana Children's Museum)",
    category: "customers",
    lat: 29.98995,
    lng: -90.09402,
    address: "15 Henry Thomas Dr, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: week(
      [R(T(9), T(16, 30))],
      null,
      null,
      [R(T(9), T(16, 30))],
      [R(T(9), T(16, 30))],
      [R(T(9), T(16, 30))],
      [R(T(9), T(16, 30))],
    ),
    free: false,
    verify: true,
    tip: "The Dickie Brennan café inside the Children's Museum is officially a 'Community Space' — no museum ticket needed, and it has its own family restroom. Lagoon views in City Park, closed Monday and Tuesday.",
  },
  {
    id: "xavier-university-library",
    name: "University Library (Xavier University)",
    category: "public",
    lat: 29.96389,
    lng: -90.10922,
    address: "1 Drexel Dr, New Orleans, LA 70125",
    neighborhood: "Gert Town",
    hours: UNKNOWN_HOURS,
    free: true,
    verify: true,
    tip: "Xavier's main library lets the general public use the building — no ID checkpoint at the door, per the university's own FAQ. Academic-calendar hours swing hard with semesters; a weekday mid-morning is your safest bet.",
  },
  {
    id: "pals-lounge",
    name: "Pal's Lounge",
    category: "customers",
    lat: 29.97675,
    lng: -90.08638,
    address: "949 N Rendon St, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: daily(T(15), T(27)),
    free: false,
    verify: true,
    tip: "Bayou St. John's dive of record, pouring from 3 p.m. deep into the night. Buy a drink, admire the wallpaper in the restroom — you'll know it when you see it.",
  },
  {
    id: "popeyes-s-carrollton",
    name: "Popeyes (S. Carrollton)",
    category: "customers",
    lat: 29.96152,
    lng: -90.11502,
    address: "3100 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Gert Town",
    hours: week(
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(23))],
      [R(T(10), T(24))],
      [R(T(10), T(24))],
    ),
    free: false,
    verify: true,
    tip: "Mid-Carrollton chicken with a dining room, filling the gap between the university stretch and Xavier. Open late on weekends.",
  },
  {
    id: "banks-street-bar",
    name: "Banks Street Bar & Grill",
    category: "customers",
    lat: 29.97451,
    lng: -90.10646,
    address: "4401 Banks St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(12), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(16), T(26))],
      [R(T(13), T(26))],
      [R(T(12), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Mid-City's live-music dive, open to 2 a.m. nightly with local bands most evenings. A beer is the toll; the music's usually free.",
  },
  {
    id: "bayou-beer-garden",
    name: "Bayou Beer Garden",
    category: "customers",
    lat: 29.97197,
    lng: -90.09167,
    address: "326 N Jefferson Davis Pkwy, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(12), T(22))],
      [R(T(12), T(24))],
      [R(T(12), T(24))],
      [R(T(12), T(24))],
      [R(T(12), T(24))],
      [R(T(12), T(25))],
      [R(T(12), T(25))],
    ),
    free: false,
    verify: true,
    tip: "Four bars, fifty-plus taps, and a deck the size of a city block. Connected by a bridge to its wine-garden sibling next door — between the two, facilities are never far.",
  },
  {
    id: "bayou-wine-garden",
    name: "Bayou Wine Garden",
    category: "customers",
    lat: 29.97155,
    lng: -90.09129,
    address: "315 N Rendon St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(12), T(22))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(15), T(23))],
      [R(T(15), T(23))],
      [R(T(15), T(23))],
      [R(T(12), T(23))],
    ),
    free: false,
    verify: true,
    tip: "The calmer, wine-on-tap half of the Bayou garden complex, linked to the beer side by a courtyard bridge. Note the street: N. Rendon, not Rennes — even locals get it wrong.",
  },
  {
    id: "chickie-wah-wah",
    name: "Chickie Wah Wah",
    category: "customers",
    lat: 29.96675,
    lng: -90.08959,
    address: "2828 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(17), T(26)),
    free: false,
    verify: true,
    tip: "An honest-to-god listening room on Canal — blues and R&B nightly, cover goes straight to the band. The cover is your purchase; the restroom comes with it.",
  },
  {
    id: "katies-restaurant",
    name: "Katie's Restaurant & Bar",
    category: "customers",
    lat: 29.97303,
    lng: -90.09597,
    address: "3701 Iberville St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(17))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Neighborhood Creole standby a block off Canal with a proper bar and a Tuesday-to-Saturday happy hour. Order the boudin egg rolls; the restroom is a given.",
  },
  {
    id: "liuzzas-restaurant",
    name: "Liuzza's Restaurant & Bar",
    category: "customers",
    lat: 29.97341,
    lng: -90.09526,
    address: "3636 Bienville St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Frozen schooners of beer and the Frenchuletta since 1947. Sit at the bar if the dining room's slammed — the restroom works either way.",
  },
  {
    id: "mcdonalds-canal-midcity",
    name: "McDonald's (2757 Canal St)",
    category: "customers",
    lat: 29.96682,
    lng: -90.08817,
    address: "2757 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "A 24-hour McDonald's right on the Canal streetcar line with a real dining room — per its own location page. One of the very few round-the-clock indoor options between downtown and the cemeteries.",
  },
  {
    id: "twelve-mile-limit",
    name: "Twelve Mile Limit",
    category: "customers",
    lat: 29.96825,
    lng: -90.09987,
    address: "500 S Telemachus St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(24))],
      [R(T(17), T(24))],
      [R(T(17), T(24))],
      [R(T(17), T(24))],
      [R(T(17), T(24))],
      [R(T(17), T(26))],
      [R(T(17), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Craft cocktails at dive-bar prices, deep in residential Mid-City. Comedy and trivia nights mean it's busy enough that nobody notices a pit stop.",
  },
  {
    id: "wrong-iron",
    name: "Wrong Iron",
    category: "customers",
    lat: 29.97493,
    lng: -90.09204,
    address: "3532 Toulouse St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(24))],
      [R(T(15), T(23))],
      [R(T(15), T(23))],
      [R(T(15), T(24))],
      [R(T(15), T(24))],
      [R(T(15), T(26))],
      [R(T(11), T(26))],
    ),
    free: false,
    verify: true,
    tip: "The giant beer garden right on the Lafitte Greenway — fifty taps, frozen drinks, and every cyclist on the trail eventually stops here for exactly the reason you're reading this. 21+.",
  },
  {
    id: "deutsches-haus",
    name: "Deutsches Haus",
    category: "customers",
    lat: 29.98604,
    lng: -90.08769,
    address: "1700 Moss St, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      [R(T(13), T(19))],
      null,
      [R(T(16), T(22))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
      [R(T(13), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "German-American club and beer hall on the bayou pouring ~20 taps alongside brats and New Orleans-German fare, with a full bar and onsite restrooms. Order food or a beer and you're set on the Bayou St. John / Moss Street loop. Closed Mondays.",
  },
  {
    id: "lolas-esplanade",
    name: "Lola's",
    category: "customers",
    lat: 29.98073,
    lng: -90.08535,
    address: "3312 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      [R(T(10, 30), T(15)), R(T(17, 30), T(21, 30))],
      null,
      [R(T(18), T(21, 30))],
      [R(T(18), T(21, 30))],
      [R(T(18), T(21, 30))],
      [R(T(17, 30), T(22))],
      [R(T(10, 30), T(15)), R(T(17, 30), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Spanish tapas and paella spot on Esplanade since 1994, with indoor dining, a patio, and a side courtyard. Full bar means a glass of sangria buys you restroom access even without a full meal; closed Mondays now, so don't show up expecting the old schedule.",
  },
  {
    id: "liuzzas-by-the-track",
    name: "Liuzza's by the Track",
    category: "customers",
    lat: 29.9803,
    lng: -90.08312,
    address: "1518 N Lopez St, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      null,
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
      [R(T(11), T(20))],
    ),
    free: false,
    verify: true,
    tip: "A legendary counter-service joint steps from the Fair Grounds gate, famous for its BBQ shrimp po'boy — order, grab a table, and use the restroom while you wait for your number. Closed Sundays except when the Saints are playing. Not to be confused with the other Liuzza's on Bienville.",
  },
  {
    id: "whiskey-and-sticks",
    name: "Whiskey & Sticks",
    category: "customers",
    lat: 29.97628,
    lng: -90.07621,
    address: "2513 Bayou Rd, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      null,
      null,
      null,
      [R(T(18), T(24))],
      [R(T(18), T(24))],
      [R(T(18), T(24))],
      [R(T(18), T(24))],
    ),
    free: false,
    wheelchair: true,
    tip: "A premium whiskey and cigar lounge on the historic Bayou Road corridor, with indoor table seating, small bites, and a patio. Wheelchair-accessible, gender-neutral restrooms confirmed on site — closed Sunday through Tuesday.",
  },
  {
    id: "atelier-vie",
    name: "Atelier Vie",
    category: "customers",
    lat: 29.95575,
    lng: -90.09547,
    address: "1001 S Broad St, New Orleans, LA 70125 (GPS to 3928 Euphrosine St)",
    neighborhood: "Gert Town",
    hours: week(
      [R(T(10), T(14))],
      null,
      null,
      null,
      null,
      null,
      [R(T(10), T(14))],
    ),
    free: false,
    verify: true,
    tip: "New Orleans's oldest continuously operating craft distillery, tucked in the Art Egg industrial building — known for Toulouse absinthe and rice whiskey. Weekend bottle sales run 10-2 with walk-in access; full seated tastings need a text-ahead appointment at 504-534-8590.",
  },
  {
    id: "nice-guys-nola-earhart",
    name: "Nice Guys NOLA",
    category: "customers",
    lat: 29.96003,
    lng: -90.11374,
    address: "7910 Earhart Blvd, New Orleans, LA 70125",
    neighborhood: "Gert Town",
    hours: week(
      [R(T(10), T(17, 30))],
      [R(T(11), T(15)), R(T(16, 30), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(15)), R(T(17), T(23))],
      [R(T(11), T(15)), R(T(17), T(23))],
    ),
    free: false,
    wheelchair: true,
    tip: "A full-service Southern restaurant and lounge on Earhart Blvd with craft cocktails and live entertainment — a rare sit-down option on this corridor. Restroom is confirmed wheelchair-accessible; just be a paying customer to use it.",
  },
  {
    id: "bao-mi-tulane-ave",
    name: "Bao Mi",
    category: "customers",
    lat: 29.95789,
    lng: -90.08294,
    address: "2000 Tulane Ave, Suite B, New Orleans, LA 70112",
    neighborhood: "Mid-City",
    hours: week(
      null,
      [R(T(10, 30), T(15))],
      [R(T(10, 30), T(16))],
      [R(T(10, 30), T(16))],
      [R(T(10, 30), T(16))],
      [R(T(10, 30), T(16))],
      null,
    ),
    free: false,
    verify: true,
    tip: "Vietnamese fusion counter inside the LSU Health Foundation building on Tulane Ave, serving banh mi, bao, and vermicelli bowls with real countertop seating at the window. Weekday lunch only — closed weekends — so it's a sit-and-eat stop, not pure grab-and-go.",
  },
  {
    id: "betsys-pancake-house",
    name: "Betsy's Pancake House",
    category: "customers",
    lat: 29.96421,
    lng: -90.08611,
    address: "2542 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(7), T(14))],
      [R(T(5, 30), T(14))],
      [R(T(5, 30), T(14))],
      [R(T(5, 30), T(14))],
      [R(T(5, 30), T(14))],
      [R(T(5, 30), T(14))],
      null,
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Old-school Canal Street diner slinging Cajun-inflected breakfast since 1986 — it survived a 2022 closure scare and is still slapping down plates with full table service. Sit down, order, and the wheelchair-accessible restroom is right there.",
  },
  {
    id: "boswells-jamaican-grill",
    name: "Boswell's Jamaican Grill",
    category: "customers",
    lat: 29.96589,
    lng: -90.09993,
    address: "3521 Tulane Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      null,
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18))],
      [R(T(11), T(18, 30))],
      [R(T(11), T(19))],
    ),
    free: false,
    verify: true,
    tip: "Long-running Caribbean spot on Tulane Ave near the medical corridor, with dine-in and outdoor patio seating for jerk chicken, oxtail, and curry goat. Closed Sundays, otherwise open daily from 11am.",
  },
  {
    id: "holy-sheets-laundromat",
    name: "Holy Sheets Laundromat",
    category: "customers",
    lat: 29.98198,
    lng: -90.0734,
    address: "1743 N Broad St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(8), T(21)),
    free: false,
    verify: true,
    tip: "A newer wash-dry-fold laundromat on N Broad, open daily 8 a.m. to 9 p.m. with last load at 7:30. It's staffed, not a bare coin-op, so a customer restroom is a reasonable bet — just not a guarantee.",
  },
  {
    id: "ideal-market-s-broad",
    name: "Ideal Market (S Broad)",
    category: "public",
    lat: 29.96412,
    lng: -90.08887,
    address: "250 S Broad St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(6), T(22)),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "Full-service Latin American supermarket on S Broad with produce, a bakery, and a deli counter — long daily hours make it a dependable Mid-City walk-in near Tulane Ave.",
  },
  {
    id: "rock-n-bowl",
    name: "Rock 'n' Bowl (Mid-City Lanes)",
    category: "customers",
    lat: 29.96031,
    lng: -90.11552,
    address: "3016 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Mid-City",
    hours: week(
      null,
      null,
      [R(T(17), T(23))],
      [R(T(17), T(22))],
      [R(T(17), T(23))],
      [R(T(17), T(24))],
      [R(T(16), T(24))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "The legendary Mid-City bowling alley and zydeco dance hall, closed Sundays and Mondays and prone to special hours around July 4th. Full bar and kitchen — order a beer or a plate and the ADA-accessible restrooms are covered.",
  },
  {
    id: "skeeta-hawk-brewing",
    name: "Skeeta Hawk Brewing",
    category: "customers",
    lat: 29.96756,
    lng: -90.08347,
    address: "455 N Dorgenois St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(20))],
      [R(T(15), T(21))],
      null,
      [R(T(15), T(21))],
      [R(T(15), T(21))],
      [R(T(15), T(21))],
      [R(T(11), T(21))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Neighborhood brewery right on the Lafitte Greenway, built with about as many bathrooms as they could fit into the floor plan. Covered beer garden, wheelchair-accessible restrooms and parking — a solid stop for cyclists and walkers passing through. Closed Tuesdays.",
  },
  {
    id: "trader-joes-tulane-ave",
    name: "Trader Joe's (Tulane Ave)",
    category: "public",
    lat: 29.96094,
    lng: -90.08803,
    address: "2501 Tulane Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(9), T(21)),
    free: true,
    verify: true,
    tip: "New Orleans' first-ever Trader Joe's, opened August 2025 right on the Tulane Ave medical corridor across from the VA hospital. Grocery stores are reliable free walk-in restroom stops, and this one's open 9am to 9pm daily with a big parking lot.",
  },
  {
    id: "vandal-hookah-lounge-tulane",
    name: "Vandal Hookah Lounge",
    category: "customers",
    lat: 29.96723,
    lng: -90.10289,
    address: "3835 Tulane Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(26))],
      [R(T(15), T(26))],
      [R(T(15), T(26))],
      [R(T(15), T(26))],
      [R(T(15), T(26))],
      [R(T(11), T(27))],
      [R(T(11), T(27))],
    ),
    free: false,
    verify: true,
    tip: "Stylish Mediterranean lounge on Tulane Ave with a covered patio and full bar, open late nightly (past 2 a.m. on weeknights, past 3 a.m. Fri/Sat). Order a hookah, a shawarma plate, or a drink and the restroom comes with it.",
  },
];
