import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** Mid-City, City Park, Bayou St. John, and Esplanade Ridge. */
export const MIDCITY_SPOTS: readonly Spot[] = [
  {
    id: "cafe-du-monde-city-park",
    name: "Café du Monde (City Park)",
    category: "customers",
    lat: 29.98543,
    lng: -90.0951,
    address: "56 Dreyfous Dr, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(20)),
    free: false,
    verify: true,
    tip: "Unlike the famous original — which has no restroom at all — this Café du Monde lives in City Park's historic Casino Building and does. Beignets first, obviously.",
  },
  {
    id: "besthoff-sculpture-garden",
    name: "Besthoff Sculpture Garden",
    category: "public",
    lat: 29.98776,
    lng: -90.0924,
    address: "1 Collins Diboll Cir, City Park",
    neighborhood: "City Park",
    hours: daily(T(10), T(17)),
    free: true,
    wheelchair: true,
    osmToilet: true,
    verify: true,
    tip: "Free to enter and genuinely world-class: eleven acres of sculpture under the live oaks, with restrooms mapped on OSM. Art, shade, and relief, all gratis.",
  },
  {
    id: "city-park-festival-grounds",
    name: "City Park Festival Grounds Restrooms",
    category: "public",
    lat: 29.98771,
    lng: -90.09795,
    address: "Festival Grounds, near Tad Gormley Stadium, City Park",
    neighborhood: "City Park",
    hours: daily(T(8), T(18)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Out by Tad Gormley Stadium on the Festival Grounds. Most reliable on event and festival days — can be locked on sleepy weekdays, so have a City Park plan B (the Sculpture Garden).",
  },
  {
    id: "whole-foods-broad",
    name: "Whole Foods Market (N Broad)",
    category: "customers",
    lat: 29.96708,
    lng: -90.08444,
    address: "300 N Broad St",
    neighborhood: "Mid-City",
    hours: daily(T(8), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Mid-City's dependable option in the ReFresh Project building, near the Lafitte Greenway. Grocery-store restrooms: never glamorous, always there.",
  },
  {
    id: "1000-figs-bayou-st-john",
    name: "1000 Figs",
    category: "customers",
    lat: 29.98053,
    lng: -90.08426,
    address: "3141 Ponce De Leon St, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
    ),
    free: false,
    verify: true,
    tip: "A small, well-loved falafel spot tucked just off Esplanade Avenue in the Bayou St. John area. Dine-in seating and an on-site restroom make it a solid stop between bayou walks. Closed Sundays.",
  },
  {
    id: "parkway-bakery-tavern",
    name: "Parkway Bakery & Tavern",
    category: "customers",
    lat: 29.97364,
    lng: -90.09024,
    address: "538 Hagan Ave, New Orleans, LA 70119",
    neighborhood: "Bayou St. John",
    hours: week(
      [R(T(10), T(18))],
      null,
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
    ),
    free: false,
    verify: true,
    tip: "A legendary po'boy counter near Bayou St. John and the Lafitte Greenway, with high turnover and plenty of indoor seating. Reviewers specifically call out how clean the restroom is, so order your po'boy first and go in peace.",
  },
  {
    id: "carousel-gardens-city-park",
    name: "Carousel Gardens Amusement Park",
    category: "customers",
    lat: 29.98758,
    lng: -90.09864,
    address: "7 Victory Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: week(
      null,
      null,
      null,
      [R(T(10), T(15))],
      null,
      null,
      [R(T(11), T(18))],
    ),
    free: false,
    verify: true,
    tip: "Home to the historic 1906 carousel and other rides inside City Park, with restrooms confirmed on site. It's a gated, ticketed park, so you'll need a wristband to get in — hours run seasonal, so check ahead.",
  },
  {
    id: "city-putt-city-park",
    name: "City Putt",
    category: "customers",
    lat: 29.98501,
    lng: -90.09228,
    address: "33 Dreyfous Dr, New Orleans, LA 70119",
    neighborhood: "City Park",
    hours: week(
      [R(T(10), T(22))],
      null,
      null,
      [R(T(15), T(22))],
      [R(T(15), T(22))],
      [R(T(15), T(22))],
      [R(T(10), T(22))],
    ),
    free: false,
    wheelchair: true,
    tip: "Two 36-hole mini-golf courses in City Park, both ADA accessible, with restrooms confirmed on site. Pay the $10-12 round fee to get past the gate — closed Monday and Tuesday.",
  },
  {
    id: "filmore-in-the-oaks",
    name: "Filmore in the Oaks",
    category: "customers",
    lat: 30.01156,
    lng: -90.09866,
    address: "1040 Filmore Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: daily(T(7), T(19)),
    free: false,
    verify: true,
    tip: "The bar and restaurant inside City Park's South Course golf clubhouse, open to golfers and non-golfers alike. Grab a coffee at the counter and use the restroom guests specifically praise for being clean.",
  },
  {
    id: "storyland-city-park",
    name: "Storyland",
    category: "customers",
    lat: 29.98758,
    lng: -90.09681,
    address: "5 Victory Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: week(
      [R(T(10), T(16, 30))],
      null,
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
      [R(T(10), T(16, 30))],
    ),
    free: false,
    tip: "A storybook-themed kiddie park inside City Park with restrooms confirmed on site. $8 gets you in if you're 36 inches or taller — free under that height or with a Friends of City Park membership.",
  },
  {
    id: "wheel-fun-rentals-big-lake",
    name: "Wheel Fun Rentals Boat House (Big Lake)",
    category: "customers",
    lat: 29.9899,
    lng: -90.0882,
    address: "7 Friederichs Ave, New Orleans, LA 70124",
    neighborhood: "City Park",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "The swan-boat and bike rental kiosk on City Park's Big Lake advertises 'easy access to parking, restrooms, and everything you need.' Hours shift seasonally and with the weather, so rent a bike or just ask at the counter.",
  },
  {
    id: "cafe-degas-esplanade",
    name: "Café Degas",
    category: "customers",
    lat: 29.98032,
    lng: -90.08415,
    address: "3127 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(10, 30), T(15)), R(T(17), T(21))],
      null,
      [R(T(17), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(22))],
      [R(T(10, 30), T(23))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "An oak-shaded French bistro on the historic Esplanade Ridge stretch, with a gender-neutral restroom and a covered outdoor deck. Grab a coffee or pastry at the bar if you don't want a full meal — low pressure, easy stop while walking the avenue. Closed Mondays.",
  },
  {
    id: "cansecos-esplanade-market",
    name: "Canseco's Esplanade Market",
    category: "customers",
    lat: 29.98058,
    lng: -90.08451,
    address: "3135 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "A neighborhood grocery on the Esplanade Ave ridge near Bayou St. John, occupying the old Whole Foods building and popular with joggers and dog walkers. Open every day until 10pm; restroom with a small purchase expected.",
  },
  {
    id: "ccs-coffee-esplanade",
    name: "CC's Coffee House (Esplanade Ave)",
    category: "customers",
    lat: 29.97758,
    lng: -90.08063,
    address: "2800 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
      [R(T(6), T(13)), R(T(14), T(20))],
    ),
    free: false,
    verify: true,
    tip: "A neighborhood coffee shop on the Esplanade Ridge streetcar line with indoor and umbrella-shaded outdoor seating, roughly midway between City Park and the Quarter. Reviewers confirm the customer restroom is clean and available — just watch for the 1-2pm midday closure.",
  },
  {
    id: "santa-fe-esplanade",
    name: "Santa Fe",
    category: "customers",
    lat: 29.98089,
    lng: -90.085,
    address: "3201 Esplanade Ave, New Orleans, LA 70119",
    neighborhood: "Esplanade Ridge",
    hours: week(
      [R(T(11), T(21))],
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A Southwestern/Mexican spot at the lakeside end of Esplanade near the Fair Grounds, with an open-air garden porch and full bar. Order a margarita and settle in — closed Mondays, otherwise open from late morning into the evening.",
  },
  {
    id: "angelo-brocatos-carrollton",
    name: "Angelo Brocato's Ice Cream & Pastry Shop",
    category: "customers",
    lat: 29.97551,
    lng: -90.09918,
    address: "214 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(21))],
      null,
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
      [R(T(10), T(22))],
    ),
    free: false,
    wheelchair: true,
    tip: "A Sicilian ice cream and pastry institution since 1905, right at the Canal Street corner. Order a cannoli or spumoni and the wheelchair-accessible restroom is yours — it's busy enough that nobody blinks. Closed Mondays.",
  },
  {
    id: "burger-king-canal-st",
    name: "Burger King (Canal St)",
    category: "customers",
    lat: 29.96624,
    lng: -90.08786,
    address: "2727 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(5), T(26))],
      [R(T(0), T(23, 59))],
      [R(T(0), T(23, 59))],
      [R(T(0), T(23, 59))],
    ),
    free: false,
    verify: true,
    tip: "A near-24-hour Burger King on the Canal St stretch between the Quarter and City Park, dining room open into the early morning on weekends. A reviewer noted staff expect a purchase before you use the restroom, so grab a fry first.",
  },
  {
    id: "mandinas-canal-street",
    name: "Mandina's Restaurant",
    category: "customers",
    lat: 29.97218,
    lng: -90.09812,
    address: "3800 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
    ),
    free: false,
    wheelchair: true,
    tip: "A Canal Street landmark serving turtle soup and trout amandine since 1932. The ramp, seating, and restroom are all wheelchair accessible, and it's an easy in-and-out for a quick bite plus a bathroom stop.",
  },
  {
    id: "mcdonalds-n-broad-st",
    name: "McDonald's (N Broad St)",
    category: "customers",
    lat: 29.9837,
    lng: -90.07167,
    address: "1918 N Broad St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Open around the clock near the Lafitte Greenway and Bayou St. John, where late-night options in this part of Mid-City are thin. Standard dine-in lobby with a public restroom.",
  },
  {
    id: "rouses-mid-city",
    name: "Rouses Market (Mid-City)",
    category: "customers",
    lat: 29.97635,
    lng: -90.09653,
    address: "400 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: daily(T(7), T(23)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Full-service, locally-owned grocery store near the Canal streetcar terminus, open long hours every day. Deli, bakery, seafood counter, and a wheelchair-accessible customer restroom — a reliable option well past when the restaurants have stopped serving.",
  },
  {
    id: "sacred-grinds-canal-st",
    name: "Sacred Grinds Coffee House",
    category: "customers",
    lat: 29.98141,
    lng: -90.11025,
    address: "5055 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(7), T(17))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(15))],
      [R(T(7), T(17))],
      [R(T(7), T(17))],
    ),
    free: false,
    verify: true,
    tip: "The only cafe at the far end of the Canal streetcar line, wedged between two cemeteries near the Katrina Memorial. Small neighborhood spot, but a genuinely useful coffee-and-restroom break if you're out at that end of Canal St.",
  },
  {
    id: "second-line-brewing",
    name: "Second Line Brewing",
    category: "customers",
    lat: 29.98249,
    lng: -90.10525,
    address: "433 N Bernadotte St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(12), T(20))],
      [R(T(16), T(22))],
      [R(T(16), T(21))],
      [R(T(16), T(22))],
      [R(T(16), T(22))],
      [R(T(14), T(22))],
      [R(T(12), T(22))],
    ),
    free: false,
    verify: true,
    tip: "A dog-friendly Mid-City taproom with a big covered beer garden and rotating food trucks. Grab a pint and the indoor restroom is right there for customers.",
  },
  {
    id: "toups-meatery-carrollton",
    name: "Toups' Meatery",
    category: "customers",
    lat: 29.98057,
    lng: -90.09456,
    address: "845 N Carrollton Ave, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: week(
      [R(T(10), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(22))],
      [R(T(11), T(15)), R(T(17), T(23))],
      [R(T(11), T(15)), R(T(17), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Isaac Toups' acclaimed Cajun spot on N. Carrollton, known for house-made charcuterie and boudin. A full sit-down restaurant with proper facilities, open for both lunch and dinner most days — a good stop on the walk toward the cemeteries.",
  },
  {
    id: "waffle-house-2500-canal",
    name: "Waffle House #2196",
    category: "customers",
    lat: 29.96384,
    lng: -90.0851,
    address: "2500 Canal St, New Orleans, LA 70119",
    neighborhood: "Mid-City",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Classic yellow-sign Waffle House right on Canal, open around the clock. Order cheap coffee and hash browns and use the restroom — reviewers specifically call this location's restrooms spotless.",
  },
];
