import type { Spot } from "../types";
import { T, R, daily, week, UNKNOWN_HOURS } from "./helpers";

/** Lower Garden District through Audubon, Freret, and Carrollton. */
export const UPTOWN_SPOTS: readonly Spot[] = [
  {
    id: "whole-foods-magazine",
    name: "Whole Foods Market (Arabella Station)",
    category: "customers",
    lat: 29.92078,
    lng: -90.11766,
    address: "5600 Magazine St",
    neighborhood: "Uptown",
    hours: daily(T(8), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A grocery store in a converted streetcar barn. Dependable restrooms in the middle of the Magazine Street mile — grab a kombucha if your conscience insists.",
  },
  {
    id: "audubon-park",
    name: "Audubon Park Restrooms",
    category: "public",
    lat: 29.93302,
    lng: -90.12225,
    address: "Audubon Park, near the golf clubhouse, 6500 Magazine St",
    neighborhood: "Uptown",
    hours: daily(T(6), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "Free park restrooms near the golf clubhouse, mapped on OpenStreetMap. Live oaks, joggers, zero judgment.",
  },
  {
    id: "the-fly",
    name: "The Fly (Audubon Riverview)",
    category: "public",
    lat: 29.92163,
    lng: -90.13463,
    address: "Riverview Dr, behind Audubon Park",
    neighborhood: "Uptown",
    hours: daily(T(6), T(20)),
    free: true,
    osmToilet: true,
    verify: true,
    tip: "The riverside back porch of Audubon Park, where locals watch sunsets and container ships. Restrooms by the picnic shelters — unisex, mapped on OSM.",
  },
  {
    id: "hey-cafe-broadmoor",
    name: "Hey! Café (Broadmoor)",
    category: "customers",
    lat: 29.94126,
    lng: -90.10243,
    address: "4300 S Derbigny St, New Orleans, LA 70125",
    neighborhood: "Broadmoor",
    hours: daily(T(7, 30), T(14)),
    free: false,
    verify: true,
    tip: "A genuine independent coffee shop and roastery built into a renovated historic Broadmoor building, with indoor and outdoor seating — a rare mapped option in this residential stretch. Morning-only hours, roughly 7:30am to 2pm daily; one source says closed Sundays, so worth a quick check first.",
  },
  {
    id: "ochsner-baptist-main-lobby",
    name: "Ochsner Baptist Medical Center Main Lobby",
    category: "public",
    lat: 29.93754,
    lng: -90.10444,
    address: "2700 Napoleon Ave, New Orleans, LA 70115",
    neighborhood: "Broadmoor",
    hours: "24/7",
    free: true,
    tip: "A 182-bed Ochsner campus on Napoleon Avenue with a staffed lobby open around the clock. A dependable backup near Freret Street, well clear of the French Quarter crowds.",
  },
  {
    id: "starbucks-s-claiborne-washington",
    name: "Starbucks (S. Claiborne & Washington)",
    category: "customers",
    lat: 29.94299,
    lng: -90.09532,
    address: "2851 S Claiborne Ave, New Orleans, LA 70125",
    neighborhood: "Broadmoor",
    hours: daily(T(4, 30), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A reliable early-to-late option on the S. Claiborne corridor, where public restroom options in Broadmoor and Central City are otherwise thin. Wheelchair accessible.",
  },
  {
    id: "cooter-browns-carrollton",
    name: "Cooter Brown's Tavern & Oyster Bar",
    category: "customers",
    lat: 29.94253,
    lng: -90.13439,
    address: "509 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: daily(T(11), T(25)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "A sprawling Uptown beer-and-oyster institution near the levee, open 365 days a year until 1 a.m. It's busy enough at all hours that a quick restroom stop blends right in, and the restrooms are wheelchair accessible.",
  },
  {
    id: "jacques-imos-oak-street",
    name: "Jacques-Imo's Cafe",
    category: "customers",
    lat: 29.94907,
    lng: -90.13221,
    address: "8324 Oak Street, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: week(
      null,
      null,
      null,
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(17), T(22))],
      [R(T(16), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Legendary Oak Street Creole spot known for alligator sausage cheesecake and fried chicken. Duck into the walk-in bar area for a seat and a drink even if the dining room has a wait, then find the restroom tucked in the corner by the cornbread oven. Closed Sunday through Tuesday, dinner only the rest of the week — check ahead for holiday closures.",
  },
  {
    id: "nix-library-carrollton",
    name: "Nix Branch Library",
    category: "public",
    lat: 29.94893,
    lng: -90.12827,
    address: "1401 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: week(
      null,
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(19))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    wheelchair: true,
    tip: "A New Orleans Public Library branch right on Carrollton Avenue. A 2022 renovation added an accessible bathroom, wheelchair lift, and automatic doors — no card, no purchase, no questions. Closed Sundays.",
  },
  {
    id: "oak-and-ale-oak-st",
    name: "Oak & Ale",
    category: "customers",
    lat: 29.94763,
    lng: -90.1303,
    address: "8118 Oak St, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: week(
      [R(T(12), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(15), T(24))],
      [R(T(12), T(24))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "The merged wine-and-beer bar that used to be two separate spots on the Oak Street strip, now one connected venue with a popular patio. Order a glass and the restroom is right there for patrons.",
  },
  {
    id: "robert-fresh-market-carrollton",
    name: "Robért Fresh Market (Carrollton)",
    category: "customers",
    lat: 29.95717,
    lng: -90.12059,
    address: "8115 S. Claiborne Ave, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "A full-service Robért Fresh Market outpost on South Claiborne with a hot food bar and prepared meals, a solid backup near the Carrollton/Uptown university stretch when Rouses is out of the way. In-store restroom, small purchase expected.",
  },
  {
    id: "rue-de-la-course-carrollton",
    name: "Rue de la Course",
    category: "customers",
    lat: 29.94738,
    lng: -90.12997,
    address: "1140 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: week(
      [R(T(8), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(7, 30), T(19, 30))],
      [R(T(8), T(19, 30))],
    ),
    free: false,
    verify: true,
    tip: "New Orleans' last surviving Rue de la Course, tucked into a converted 1921 bank building at Oak and Carrollton. Two floors of laptop-friendly seating and a restroom that regulars specifically mention in their reviews, open into the evening every day.",
  },
  {
    id: "camellia-grill-carrollton",
    name: "The Camellia Grill",
    category: "customers",
    lat: 29.94376,
    lng: -90.13389,
    address: "626 S Carrollton Ave, New Orleans, LA 70118",
    neighborhood: "Carrollton",
    hours: daily(T(8), T(23)),
    free: false,
    tip: "A 24-stool counter diner right at the streetcar turnaround, famous for omelets and pecan pie. Order a coffee, then thread your way past the kitchen and storage to the restroom in back — worth it if you're walking the levee or riding the St. Charles line.",
  },
  {
    id: "bearcat-cafe-jena-st",
    name: "Bearcat Cafe",
    category: "customers",
    lat: 29.93564,
    lng: -90.10418,
    address: "2521 Jena St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: week(
      [R(T(8), T(15))],
      null,
      [R(T(8), T(15))],
      [R(T(8), T(15))],
      [R(T(8), T(15))],
      [R(T(8), T(15))],
      [R(T(8), T(15))],
    ),
    free: false,
    verify: true,
    tip: "A brunch cafe a block off Freret with vegan and gluten-free options and a steady breakfast crowd. Closed Mondays, but any other morning it's a solid sit-down stop near Napoleon Ave.",
  },
  {
    id: "cava-freret",
    name: "CAVA (Freret)",
    category: "customers",
    lat: 29.93516,
    lng: -90.10859,
    address: "5001 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(10, 45), T(22)),
    free: false,
    verify: true,
    tip: "The Mediterranean fast-casual chain's first New Orleans location, open daily from 10:45 a.m. to 10 p.m. Newer, well-staffed counter service near Napoleon — grab a bowl and use the restroom.",
  },
  {
    id: "high-hat-cafe-freret",
    name: "High Hat Cafe",
    category: "customers",
    lat: 29.93506,
    lng: -90.10433,
    address: "4500 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(11), T(21)),
    free: false,
    verify: true,
    tip: "A Freret Street mainstay serving Southern and Delta-inspired cooking daily, 11 a.m. to 9 p.m. Sit down for catfish or gumbo and the restroom comes with the meal.",
  },
  {
    id: "midway-pizza-freret",
    name: "Midway Pizza",
    category: "customers",
    lat: 29.93504,
    lng: -90.10715,
    address: "4725 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(12), T(21, 30)),
    free: false,
    verify: true,
    tip: "A full-bar deep-dish pizza and salad spot open daily from noon to 9:30 p.m. Order a pie, grab a beer, and the restroom is a natural mid-corridor stop on Freret.",
  },
  {
    id: "mojo-coffee-house-freret",
    name: "Mojo Coffee House (Freret)",
    category: "customers",
    lat: 29.93491,
    lng: -90.1066,
    address: "4700 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(6), T(19)),
    free: false,
    verify: true,
    tip: "Locally roasted coffee, open daily from 6 a.m. to 7 p.m., a block from Tulane and Loyola foot traffic. Buy a cup and use the restroom at this well-worn Freret cafe.",
  },
  {
    id: "rouses-freret-st",
    name: "Rouses Market #83 (Freret St / Uptown)",
    category: "customers",
    lat: 29.93529,
    lng: -90.10634,
    address: "4645 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(7), T(22)),
    free: false,
    verify: true,
    tip: "Full-service supermarket on the Freret St restaurant row near Tulane and Loyola, with a café, chef's case, sushi counter, and salad bar. A dependable stop for students and visitors working their way down the corridor.",
  },
  {
    id: "starbucks-freret-street",
    name: "Starbucks (Freret Street)",
    category: "customers",
    lat: 29.93527,
    lng: -90.11087,
    address: "5335 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(4, 30), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "On the walkable Freret Street strip near Tulane and Loyola, with upstairs seating and long daily hours. The restroom is code-locked, so you'll need to buy something and ask for the code.",
  },
  {
    id: "the-company-burger-freret",
    name: "The Company Burger (Freret)",
    category: "customers",
    lat: 29.93469,
    lng: -90.10584,
    address: "4600 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "A Freret Street burger fixture since 2011, open daily into the evening. Order at the counter, grab a placard, and the dining room's restroom is right there.",
  },
  {
    id: "the-rook-cafe-freret",
    name: "The Rook Cafe",
    category: "customers",
    lat: 29.93489,
    lng: -90.10471,
    address: "4516 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: week(
      [R(T(6, 30), T(22))],
      [R(T(5, 30), T(18))],
      [R(T(5, 30), T(18))],
      [R(T(5, 30), T(22))],
      [R(T(5, 30), T(18))],
      [R(T(5, 30), T(18))],
      [R(T(6, 30), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Coffee shop, art gallery, and open-mic stage rolled into one, open from 5:30 a.m. most weekdays. Order something and the restroom is yours on your way to look at the art.",
  },
  {
    id: "vals-freret",
    name: "Vals",
    category: "customers",
    lat: 29.93483,
    lng: -90.10617,
    address: "4632 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: week(
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(22, 30))],
      [R(T(11), T(22, 30))],
    ),
    free: false,
    verify: true,
    tip: "Sit-down tacos, seafood, and a full bar with daily happy hour, open late every night of the week. A dependable dinner-hour stop on the Freret corridor.",
  },
  {
    id: "breads-on-oak-riverbend",
    name: "Breads on Oak",
    category: "customers",
    lat: 29.95111,
    lng: -90.13492,
    address: "8640 Oak St, New Orleans, LA 70118",
    neighborhood: "Riverbend",
    hours: daily(T(7, 30), T(15)),
    free: false,
    verify: true,
    tip: "New Orleans' original all-organic bakery and cafe, near the Riverbend end of Oak Street, serving scratch-made breakfast and lunch daily. Get a pastry, use the restroom, nobody blinks.",
  },
  {
    id: "baru-bistro-and-tapas",
    name: "Baru Bistro & Tapas",
    category: "customers",
    lat: 29.92152,
    lng: -90.09334,
    address: "3700 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(17), T(21, 30))],
      [R(T(17), T(21, 30))],
      [R(T(17), T(21, 30))],
      [R(T(17), T(21, 30))],
      [R(T(17), T(22))],
      [R(T(11, 30), T(14, 30)), R(T(17), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Latin-Caribbean tapas bistro popular with gallery-hoppers on this stretch of Magazine, and a New York Times pick. Sit down for tapas or the Saturday lunch service and the restroom is yours — closed Sundays.",
  },
  {
    id: "bouligny-tavern",
    name: "Bouligny Tavern",
    category: "customers",
    lat: 29.92197,
    lng: -90.0929,
    address: "3641 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(16), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(24))],
      [R(T(16), T(25))],
      [R(T(16), T(25))],
      [R(T(16), T(25))],
    ),
    free: false,
    verify: true,
    tip: "Sleek wine and small-plates bar just off the main Magazine strip near Napoleon, with a heated patio and a kitchen that stays open until close. A solid evening backup once the daytime cafes have shut for the night — closed Sundays.",
  },
  {
    id: "breaux-mart-garden-district",
    name: "Breaux Mart (Garden District/Magazine)",
    category: "customers",
    lat: 29.9242,
    lng: -90.08783,
    address: "3233 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "A locally owned neighborhood grocery on Magazine Street, running for over 40 years, with deli, bakery, and produce counters. Grab a snack and duck into the restroom — open early to late, every day.",
  },
  {
    id: "danna-student-center-loyola",
    name: "Danna Student Center (Loyola University New Orleans)",
    category: "public",
    lat: 29.93398,
    lng: -90.12145,
    address: "6363 St Charles Ave, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: daily(T(7), T(26)),
    free: true,
    verify: true,
    tip: "Loyola's freshly renovated student union (reopened August 2025) explicitly serves students, faculty, staff, and community members, seven days a week, 7 a.m. to 2 a.m. First-floor restrooms are near the bookstore, right off the St. Charles streetcar line.",
  },
  {
    id: "dat-dog-magazine-st",
    name: "Dat Dog (Magazine St)",
    category: "customers",
    lat: 29.92302,
    lng: -90.08853,
    address: "3336 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Gourmet hot dogs on the Magazine Street restaurant row between Louisiana and Napoleon, with a lively patio. Order a dog and use the clean, wheelchair-accessible restroom inside — open daily into the evening.",
  },
  {
    id: "french-truck-coffee-dryades",
    name: "French Truck Coffee (Dryades St)",
    category: "customers",
    lat: 29.92916,
    lng: -90.10456,
    address: "4536 Dryades St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "A roastery-cafe in a converted house on the Dryades St strip near Touro, with indoor and outdoor seating and a full food menu. One of the few confirmed customer-restroom options in the area — exact hours vary by source, so check before a late run.",
  },
  {
    id: "howard-tilton-library-tulane",
    name: "Howard-Tilton Memorial Library (Tulane University)",
    category: "public",
    lat: 29.93931,
    lng: -90.12235,
    address: "7001 Freret St, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: week(
      [R(T(9), T(28))],
      [R(T(7, 30), T(28))],
      [R(T(7, 30), T(28))],
      [R(T(7, 30), T(28))],
      [R(T(7, 30), T(28))],
      [R(T(7, 30), T(22))],
      [R(T(9), T(22))],
    ),
    free: true,
    wheelchair: true,
    verify: true,
    tip: "Tulane's main library has an official Public Access Policy: the general public may enter, browse, and use the restrooms any time before 7 p.m. daily. Wheelchair-accessible, with an all-gender restroom in the basement — verify hours around finals or summer break, since they shift by semester.",
  },
  {
    id: "la-boulangerie-magazine",
    name: "La Boulangerie",
    category: "customers",
    lat: 29.92047,
    lng: -90.10395,
    address: "4600 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(7), T(16)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Neighborhood bakery-cafe about a mile above Napoleon, with real dine-in seating for pastries and sandwiches. Listed wheelchair accessible and a solid daytime coffee-and-restroom stop on the corridor.",
  },
  {
    id: "lavin-bernick-tulane",
    name: "Lavin-Bernick Center for University Life (Tulane University)",
    category: "public",
    lat: 29.94122,
    lng: -90.1201,
    address: "6823 St Charles Ave, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: daily(T(7), T(23)),
    free: true,
    tip: "Tulane's student union right on St. Charles Ave, open to students, faculty, and guests alike until 11 p.m. daily. Food court, bookstore, and nine restrooms across three floors — walk in like you belong, because officially, you do.",
  },
  {
    id: "milton-h-latter-memorial-library",
    name: "Milton H. Latter Memorial Library",
    category: "public",
    lat: 29.92664,
    lng: -90.11025,
    address: "5120 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(18))],
      [R(T(10), T(17))],
      [R(T(10), T(17))],
    ),
    free: true,
    tip: "Housed in a landmark 1907 mansion right on the St. Charles streetcar line, one of the most architecturally striking libraries in the city. Free public restroom, no purchase needed, and the grand columned entrance is impossible to miss.",
  },
  {
    id: "monkey-hill-bar",
    name: "Monkey Hill Bar",
    category: "customers",
    lat: 29.92265,
    lng: -90.12363,
    address: "6100 Magazine St, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: week(
      [R(T(12), T(24))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(23))],
      [R(T(16), T(26))],
      [R(T(12), T(26))],
    ),
    free: false,
    verify: true,
    tip: "Neighborhood dive bar a few blocks from Audubon Park's Magazine Street entrance. Open afternoons through the wee hours on weekends, so it's a dependable late-night option once the nearby cafes have gone dark — order a drink first.",
  },
  {
    id: "ms-maes-magazine-st",
    name: "Ms. Mae's",
    category: "customers",
    lat: 29.92065,
    lng: -90.1012,
    address: "4336 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "The classic cheap, cash-only, 24-hour Magazine St dive. A drink is the toll for the bathroom, but it's a cheap toll.",
  },
  {
    id: "pjs-coffee-uptown-state",
    name: "PJ's Coffee (Uptown/State St)",
    category: "customers",
    lat: 29.9208,
    lng: -90.1159,
    address: "5432 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(6), T(21)),
    free: false,
    verify: true,
    tip: "Local coffee chain outpost roughly halfway between Napoleon and Audubon Park, open early to late. Grab an iced coffee and use the restroom on a hot Magazine Street walk.",
  },
  {
    id: "pjs-coffee-willow-st",
    name: "PJ's Coffee (Willow St)",
    category: "customers",
    lat: 29.94484,
    lng: -90.12342,
    address: "6501 Willow St, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: daily(T(7), T(21)),
    free: false,
    verify: true,
    tip: "Right by the Tulane/Loyola campuses with roomy dine-in seating, open until 9pm daily, later than most nearby coffee competitors. Good for a break while touring Audubon Park or the universities. Purchase expected for restroom access.",
  },
  {
    id: "port-orleans-brewing",
    name: "Port Orleans Brewing Co.",
    category: "customers",
    lat: 29.91698,
    lng: -90.09828,
    address: "4124 Tchoupitoulas St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Big, clean Uptown taproom with a full kitchen and an outdoor patio with cornhole and a basketball hoop. Family-friendly enough that nobody blinks at a restroom-only detour after you order something.",
  },
  {
    id: "reginellis-pizzeria-uptown",
    name: "Reginelli's Pizzeria (Uptown)",
    category: "customers",
    lat: 29.92223,
    lng: -90.12127,
    address: "5961 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(11), T(22)),
    free: false,
    verify: true,
    tip: "A New Orleans pizza chain holding the corner of State and Magazine since 1996, near Audubon Park. Open until 10 p.m. daily, so it's a solid dinner-hour restroom stop at the top of the corridor.",
  },
  {
    id: "rouses-tchoupitoulas",
    name: "Rouses Market #26 (Tchoupitoulas)",
    category: "customers",
    lat: 29.91668,
    lng: -90.10307,
    address: "4500 Tchoupitoulas St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(7), T(23)),
    free: false,
    verify: true,
    tip: "A full-line Uptown supermarket at Tchoupitoulas and Napoleon with bakery, seafood counter, and produce departments, open long hours daily. An easy in-and-out between the river and Magazine St.",
  },
  {
    id: "starbucks-magazine-state",
    name: "Starbucks (Magazine & State)",
    category: "customers",
    lat: 29.9223,
    lng: -90.12169,
    address: "6001 Magazine St, New Orleans, LA 70118",
    neighborhood: "Uptown",
    hours: daily(T(4, 30), T(21)),
    free: false,
    wheelchair: true,
    verify: true,
    tip: "Standalone Starbucks at the signalized corner of Magazine and State, a few blocks below Audubon Park. Opens at 4:30 a.m. for the pre-dawn dog-walker crowd, with a documented wheelchair-accessible restroom.",
  },
  {
    id: "the-chloe-lobby-bar",
    name: "The Chloe Lobby Bar",
    category: "lobby",
    lat: 29.9271,
    lng: -90.09931,
    address: "4125 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(10), T(21))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
      [R(T(11), T(23))],
      [R(T(10), T(23))],
    ),
    free: true,
    verify: true,
    tip: "A restored 19th-century Uptown mansion turned 14-room boutique hotel, with a coffered-ceiling lobby bar and famous front porch on St. Charles Ave. The bar welcomes walk-in locals, not just guests, and the restroom sits just off the main bar area.",
  },
  {
    id: "trader-joes-freret-napoleon",
    name: "Trader Joe's (Uptown / Freret)",
    category: "customers",
    lat: 29.93464,
    lng: -90.10269,
    address: "2428 Napoleon Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(9), T(21)),
    free: false,
    verify: true,
    tip: "Orleans Parish's second Trader Joe's, opened June 2026 at Freret and Napoleon in the old Our Lady of Lourdes school building. A small purchase along the Freret corridor buys you a clean restroom between Tulane and Broadmoor.",
  },
  {
    id: "trumpet-and-drum-coffee-house",
    name: "Trumpet and Drum Coffee House",
    category: "customers",
    lat: 29.92153,
    lng: -90.09284,
    address: "3642 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(7), T(19)),
    free: false,
    verify: true,
    tip: "Chandeliers, vintage furniture, and long hours near Napoleon Ave. Buy a coffee and settle into a sit-and-stay space with easy restroom access — a reviewer even called the bathroom elegant.",
  },
  {
    id: "walgreens-magazine-st",
    name: "Walgreens (Magazine St)",
    category: "public",
    lat: 29.92392,
    lng: -90.08703,
    address: "3227 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(8), T(21)),
    free: true,
    verify: true,
    tip: "A full-size drugstore at Magazine and Pleasant, open until 9 p.m. every day. No purchase needed for the restroom near the pharmacy — a local reviewer specifically praised the parking lot and the bathroom, so this one's a known quantity. Just ask an associate if it's locked.",
  },
  {
    id: "cafetomas-carrollton",
    name: "Cafetomas",
    category: "customers",
    lat: 29.94973,
    lng: -90.12746,
    address: "Cafetomas, New Orleans, LA",
    neighborhood: "Carrollton",
    hours: week(
      [R(T(9), T(20))],
      [R(T(10), T(20))],
      [R(T(10), T(20))],
      null,
      [R(T(10), T(20))],
      [R(T(9), T(22))],
      [R(T(9), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Latin café with veranda seating and a streetcar view on the Carrollton bend — coffee by day, open to 10 on weekends. Closed Wednesdays.",
  },
  {
    id: "good-bird-freret",
    name: "Good Bird (Freret St)",
    category: "customers",
    lat: 29.93507,
    lng: -90.10914,
    address: "5041 Freret St, New Orleans, LA 70115",
    neighborhood: "Freret",
    hours: week(
      null,
      [R(T(10), T(16))],
      [R(T(10), T(16))],
      [R(T(10), T(16))],
      [R(T(10), T(16))],
      [R(T(10), T(16))],
      [R(T(10), T(16))],
    ),
    free: false,
    verify: true,
    tip: "Rotisserie-chicken counter on the Freret strip, open 10 to 4, closed Sundays. A quick bird bowl buys the restroom.",
  },
  {
    id: "the-columns-st-charles",
    name: "The Columns",
    category: "customers",
    lat: 29.92744,
    lng: -90.09615,
    address: "3811 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(7), T(22))],
      [R(T(7), T(22))],
      [R(T(7), T(22))],
      [R(T(7), T(22))],
      [R(T(7), T(22))],
      [R(T(7), T(23))],
      [R(T(7), T(23))],
    ),
    free: false,
    verify: true,
    tip: "St. Charles porch royalty. The coffee bar opens at 7 a.m. and the bar pours until 10 or 11 — order something, watch a streetcar roll by, and use the restroom of a Victorian mansion.",
  },
  {
    id: "wendys-tchoupitoulas",
    name: "Wendy's (Tchoupitoulas St)",
    category: "customers",
    lat: 29.91601,
    lng: -90.11863,
    address: "5600 Tchoupitoulas St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: daily(T(10), T(24)),
    free: false,
    verify: true,
    tip: "Riverside Wendy's sharing a lot with a Shell station near the Tchoupitoulas Walmart. Dining room runs 10 a.m. to midnight daily — the dependable late option on this stretch.",
  },
  {
    id: "laurel-street-bakery",
    name: "Laurel Street Bakery",
    category: "customers",
    lat: 29.95157,
    lng: -90.09967,
    address: "2701 S Broad St, New Orleans, LA 70125",
    neighborhood: "Broadmoor",
    hours: week(
      null,
      [R(T(7), T(13))],
      [R(T(7), T(13))],
      [R(T(7), T(13))],
      [R(T(7), T(13))],
      [R(T(7), T(13))],
      [R(T(8), T(13))],
    ),
    free: false,
    verify: true,
    tip: "Twenty-plus years of scratch baking on South Broad. Mornings only — grab a kolache, use the facilities, support Broadmoor.",
  },
  {
    id: "pjs-coffee-s-claiborne",
    name: "PJ's Coffee (S. Claiborne)",
    category: "customers",
    lat: 29.94353,
    lng: -90.09328,
    address: "2616 S Claiborne Ave, New Orleans, LA 70125",
    neighborhood: "Broadmoor",
    hours: daily(T(6), T(18)),
    free: false,
    verify: true,
    tip: "Standalone PJ's on the Claiborne corridor, open from 6 a.m. — the early option in a stretch where mornings are otherwise dry.",
  },
  {
    id: "rosenwald-rec-center",
    name: "Rosenwald Recreation Center (NORD)",
    category: "public",
    lat: 29.95432,
    lng: -90.09627,
    address: "1120 S Broad St, New Orleans, LA 70125",
    neighborhood: "Broadmoor",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(9), T(14))],
    ),
    free: true,
    verify: true,
    tip: "The rec center gym is open and free (weekday evenings, Saturday mornings) even while its outdoor pool sits closed for repairs. Broadmoor's dependable public building.",
  },
  {
    id: "snake-and-jakes",
    name: "Snake and Jake's Christmas Club Lounge",
    category: "customers",
    lat: 29.94413,
    lng: -90.12605,
    address: "7612 Oak St, New Orleans, LA 70118",
    neighborhood: "Riverbend",
    hours: daily(T(19), T(31)),
    free: false,
    verify: true,
    tip: "A shack of Christmas lights near the Riverbend that opens at 7 p.m. and closes at dawn — or earlier if it's dead, so don't bet a full bladder on 6 a.m. The last bar standing on many a night.",
  },
  {
    id: "creole-creamery",
    name: "Creole Creamery",
    category: "customers",
    lat: 29.92446,
    lng: -90.10852,
    address: "4924 Prytania St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(22))],
      [R(T(12), T(23))],
      [R(T(12), T(23))],
    ),
    free: false,
    verify: true,
    tip: "Uptown's ice cream institution in an old pharmacy on Prytania. A single scoop of Creole cream cheese buys you a seat and the restroom — the Tchoupitoulas Challenge buys you legend status.",
  },
  {
    id: "domilises-poboys",
    name: "Domilise's Po-Boy & Bar",
    category: "customers",
    lat: 29.91746,
    lng: -90.11237,
    address: "5240 Annunciation St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(15))],
      [R(T(11), T(17))],
      [R(T(11), T(19))],
      [R(T(11), T(19))],
    ),
    free: false,
    verify: true,
    tip: "A century of fried-shrimp po-boys in a house near the river. There's a tiny bar pouring Barq's and Dixie; order, wait, and the restroom's there when you need it. Closed Sundays.",
  },
  {
    id: "f-and-m-patio-bar",
    name: "F&M Patio Bar",
    category: "customers",
    lat: 29.91684,
    lng: -90.10699,
    address: "4841 Tchoupitoulas St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(19), T(28))],
      [R(T(19), T(28))],
      [R(T(19), T(28))],
      [R(T(19), T(28))],
      [R(T(19), T(28))],
      [R(T(19), T(29, 30))],
      [R(T(19), T(29, 30))],
    ),
    free: false,
    verify: true,
    tip: "Where Uptown ends up after everything else closes — cheese fries, dancing on the pool table, sunrise exits. Restroom line moves faster than the photo-booth line.",
  },
  {
    id: "henrys-uptown-bar",
    name: "Henry's Uptown Bar",
    category: "customers",
    lat: 29.92048,
    lng: -90.11019,
    address: "5101 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: UNKNOWN_HOURS,
    free: false,
    verify: true,
    tip: "One of the oldest neighborhood bars in the city, quietly pouring on Magazine since the 1900s. Hours drift by the day and the bartender — it runs afternoon to late, but call it a pleasant gamble.",
  },
  {
    id: "joey-ks",
    name: "Joey K's",
    category: "customers",
    lat: 29.92506,
    lng: -90.08483,
    address: "3001 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
      [R(T(11), T(21))],
    ),
    free: false,
    verify: true,
    tip: "Red beans, fried pickles, and a full bar on the Magazine shopping strip. Closed Sundays — its own website says so, whatever other listings claim.",
  },
  {
    id: "le-bon-temps-roule",
    name: "Le Bon Temps Roulé",
    category: "customers",
    lat: 29.92054,
    lng: -90.10623,
    address: "4801 Magazine St, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: "24/7",
    free: false,
    verify: true,
    tip: "Magazine Street's no-frills bar that claims to never close — and its own website backs it up. Pool table, late-night sets, and a restroom that has earned its stripes.",
  },
  {
    id: "lyons-rec-center",
    name: "Lyons Recreation Center (NORD)",
    category: "public",
    lat: 29.91921,
    lng: -90.08716,
    address: "624 Louisiana Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(16), T(21))],
      [R(T(9), T(14))],
    ),
    free: true,
    verify: true,
    tip: "City rec center with open-gym hours and a fitness room, free to walk into. Summer hours are 4–9 weekdays; during the school year it opens at 10 a.m. Public building, public restrooms.",
  },
  {
    id: "st-georges-morning-call",
    name: "St. George's Episcopal (Morning Call Outreach)",
    category: "public",
    lat: 29.92603,
    lng: -90.10463,
    address: "4600 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      null,
      [R(T(9), T(10, 30))],
      [R(T(9), T(10, 30))],
      [R(T(9), T(10, 30))],
      [R(T(9), T(10, 30))],
      null,
      null,
    ),
    free: true,
    verify: true,
    tip: "A church outreach program that explicitly offers coffee, fellowship, and clean restrooms in the Parish Hall, weekday mornings 9 to 10:30. It's a ministry, not a rest stop — come as a guest and you'll be welcomed as one.",
  },
  {
    id: "superior-seafood",
    name: "Superior Seafood & Oyster Bar",
    category: "customers",
    lat: 29.92629,
    lng: -90.1017,
    address: "4338 St Charles Ave, New Orleans, LA 70115",
    neighborhood: "Uptown",
    hours: week(
      [R(T(10), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(21, 30))],
      [R(T(11), T(22))],
      [R(T(11), T(22))],
    ),
    free: false,
    verify: true,
    tip: "Oysters and charbroiled everything at St. Charles and Napoleon, right on the streetcar line — the natural pit stop of the Uptown parade route the rest of the year.",
  },
];
